//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAChatSessionCell.h"

@class NSLayoutConstraint, UIButton, UIView, _WAChatSessionCellEditOptionsView;

@interface _WAChatSessionCellModern : WAChatSessionCell
{
    _Bool _removeAllDeleteConfirmationViewsOnReuse;
    NSLayoutConstraint *_containerViewRightToContentViewConstraint;
    UIView *_sideSwipeTouchView;
    _WAChatSessionCellEditOptionsView *_editOptionsView;
    UIButton *_deleteButton;
}

+ (void)initialize;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) _WAChatSessionCellEditOptionsView *editOptionsView; // @synthesize editOptionsView=_editOptionsView;
@property(retain, nonatomic) UIView *sideSwipeTouchView; // @synthesize sideSwipeTouchView=_sideSwipeTouchView;
- (void).cxx_destruct;
- (void)setSideSwipeGestureEnabled:(_Bool)arg1;
- (_Bool)isSideSwipeGestureEnabled;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleSideSwipe:(id)arg1;
- (void)showMoreOptions:(id)arg1;
- (void)swipeToDelete:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addCustomEditButtonsIfNeeded;
- (id)deleteButtonSuperview;
- (void)prepareForReuse;
- (void)setShowExitInsteadOfDelete:(_Bool)arg1;
- (void)setUnreadCount:(long long)arg1;
- (void)reloadMessageText;
- (void)addAutolayoutConstraints;
- (void)reconfigureWithMessage:(id)arg1;
- (void)configureWithChatSession:(id)arg1 message:(id)arg2;
- (void)willTransitionToState:(unsigned long long)arg1;
- (void)tintColorDidChange;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

