//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIActivityIndicatorView;

@interface _WADoneWithSpinnerButton : UIButton
{
    _Bool _rightAligned;
    UIActivityIndicatorView *_spinner;
}

@property(readonly, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(nonatomic) _Bool rightAligned; // @synthesize rightAligned=_rightAligned;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct UIEdgeInsets)alignmentRectInsets;
- (id)initWithFrame:(struct CGRect)arg1;

@end

