//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface _WAGroupMessageDetailsTableHeaderView : UIView
{
    UIView *_topBorder;
    UIView *_bottomBorder;
    _Bool _showTopBorder;
    _Bool _showBottomBorder;
}

@property(nonatomic) _Bool showBottomBorder; // @synthesize showBottomBorder=_showBottomBorder;
@property(nonatomic) _Bool showTopBorder; // @synthesize showTopBorder=_showTopBorder;
- (void).cxx_destruct;
- (void)setBorderColor:(id)arg1;
- (void)setBottomBorderHidden:(_Bool)arg1;
- (void)setTopBorderHidden:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

