//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAHTTPFetcher.h"

#import "NSURLSessionTaskDelegate.h"

@class NSMutableData, NSString, NSURLConnection, NSURLResponse;

@interface _WAHTTPFetcherNSURLConnection : WAHTTPFetcher <NSURLSessionTaskDelegate>
{
    NSURLResponse *_response;
    NSMutableData *_receivedData;
    NSURLConnection *_connection;
    unsigned long long _backgroundTaskIdentifier;
    _Bool _isCancellingChallenge;
    _Bool _connectionHasEnded;
}

- (void).cxx_destruct;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)endBackgroundTask;
- (void)failToBeginFetchWithError:(id)arg1;
- (void)invokeCompletionHanlerWithData:(id)arg1 error:(id)arg2;
- (void)stopFetching;
- (void)beginFetchWithCompletionHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

