//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

@class UIView;

@interface _WAImageSearchBar : UISearchBar
{
    UIView *_backgroundView;
    UIView *_bottomBorderView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

