//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface _WASearchResultSection : NSObject
{
    long long _priority;
    NSString *_title;
    NSArray *_items;
}

@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
- (void).cxx_destruct;
- (void)removeItemsAtIndexes:(id)arg1;
- (id)indexesOfAllItemsContainingChatSessions:(id)arg1;
- (_Bool)removeInvalidContent;

@end

