//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_WAMapButton.h"

@interface _WAStaticPinButton : _WAMapButton
{
    _Bool _staticPinHidden;
}

@property(nonatomic) _Bool staticPinHidden; // @synthesize staticPinHidden=_staticPinHidden;
- (id)accessibilityLabel;
- (void)reloadButtonImage;
- (void)commonInit;

@end

