//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATimelockViewController.h"

@interface _WATimelockViewControllerModern : WATimelockViewController
{
}

+ (id)controller;
- (void)learnMoreAction:(id)arg1;
- (void)reloadHelperText;
- (long long)preferredStatusBarStyle;
- (void)viewDidLoad;

@end

