//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class NSString, UIButton, UILabel, UITextView;

@interface _WATextInputBoxView : UIView <UITextViewDelegate>
{
    UITextView *_textView;
    UILabel *_titleLabel;
    UILabel *_remainingLabel;
    UIView *_separator;
    unsigned long long _maximumLength;
    UIButton *_cancelButton;
    UIButton *_postButton;
}

@property(readonly, nonatomic) UIButton *postButton; // @synthesize postButton=_postButton;
@property(readonly, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) unsigned long long maximumLength; // @synthesize maximumLength=_maximumLength;
- (void).cxx_destruct;
- (void)showKeyboard;
@property(copy, nonatomic) NSString *text;
- (void)updateRemainingCount;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)fontSizeDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

