//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWarningViewController.h"

@class NSDate, NSTimer, UIActivityIndicatorView, UILabel, UIView, WABackupInfoTableCell, WAPreviousBackup, WAProgressHUD;

@interface BackupViewController : WAWarningViewController
{
    WAProgressHUD *_progressHUD;
    NSDate *_hudDisplayedDate;
    NSTimer *_timer;
    WAPreviousBackup *_previousBackup;
    _Bool _registered;
    _Bool _inProgress;
    WABackupInfoTableCell *_cellBackupInfo;
    UIView *_viewTableFooter;
    UILabel *_labelProgressInfo;
    UILabel *_labelFooterText;
    UIActivityIndicatorView *_aiBackup;
}

@property(retain, nonatomic) UIActivityIndicatorView *aiBackup; // @synthesize aiBackup=_aiBackup;
@property(retain, nonatomic) UILabel *labelFooterText; // @synthesize labelFooterText=_labelFooterText;
@property(retain, nonatomic) UILabel *labelProgressInfo; // @synthesize labelProgressInfo=_labelProgressInfo;
@property(retain, nonatomic) UIView *viewTableFooter; // @synthesize viewTableFooter=_viewTableFooter;
@property(retain, nonatomic) WABackupInfoTableCell *cellBackupInfo; // @synthesize cellBackupInfo=_cellBackupInfo;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)wa_tintColorDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)unregisterForBackupNotifications;
- (void)registerForBackupNotifications;
- (void)startBackupAction;
- (void)previousBackupChanged:(id)arg1;
- (void)backupPhaseCompleted:(id)arg1;
- (void)updateBackupDetails;
- (void)setBackupInProgress:(_Bool)arg1;
- (void)layoutFooterView;
- (void)showProgressText:(_Bool)arg1 showFooterText:(_Bool)arg2;
- (void)invalidateProgressTimer;
- (void)scheduleProgressTimer;
- (id)footerTextForBackupUploadProgress:(double)arg1 size:(long long)arg2;
- (id)footerTextForBackupProgress:(double)arg1;
- (void)updateProgress:(id)arg1;
- (void)stopAnimatingGears;
- (void)startAnimatingGears;
- (void)removeHUD:(_Bool)arg1;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)showAutobackupSettings;
- (void)dealloc;
- (void)updateErrorDisplay:(id)arg1;
- (void)backupErrorUpdated:(id)arg1;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

