//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __sFILE {
    char *_field1;
    int _field2;
    int _field3;
    short _field4;
    short _field5;
    struct __sbuf _field6;
    int _field7;
    void *_field8;
    CDUnknownFunctionPointerType _field9;
    CDUnknownFunctionPointerType _field10;
    CDUnknownFunctionPointerType _field11;
    CDUnknownFunctionPointerType _field12;
    struct __sbuf _field13;
    struct __sFILEX *_field14;
    int _field15;
    unsigned char _field16[3];
    unsigned char _field17[1];
    struct __sbuf _field18;
    int _field19;
    long long _field20;
};

struct __sbuf {
    char *_field1;
    int _field2;
};

struct axolotl_crypto_provider {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
    CDUnknownFunctionPointerType _field6;
    CDUnknownFunctionPointerType _field7;
    void *_field8;
};

struct in6_addr {
    union {
        unsigned char _field1[16];
        unsigned short _field2[8];
        unsigned int _field3[4];
    } _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct pj_math_stat {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    float _field6;
    double _field7;
};

struct pj_str_t {
    char *_field1;
    long long _field2;
};

struct pj_time_val {
    long long _field1;
    long long _field2;
};

struct pjmedia_rtcp_sdes {
    struct pj_str_t _field1;
    struct pj_str_t _field2;
    struct pj_str_t _field3;
    struct pj_str_t _field4;
    struct pj_str_t _field5;
    struct pj_str_t _field6;
    struct pj_str_t _field7;
};

struct pjmedia_rtcp_stat {
    struct pj_time_val _field1;
    struct pjmedia_rtcp_stream_stat _field2;
    struct pjmedia_rtcp_stream_stat _field3;
    struct pj_math_stat _field4;
    unsigned int _field5;
    unsigned short _field6;
    struct pjmedia_rtcp_sdes _field7;
    char _field8[64];
    unsigned int _field9;
    unsigned int _field10;
    unsigned int _field11;
};

struct pjmedia_rtcp_stream_stat {
    struct pj_time_val _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    struct pj_math_stat _field9;
    unsigned int _field10;
    struct {
        unsigned int :1;
        unsigned int :1;
    } _field11;
    struct pj_math_stat _field12;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct sockaddr_in6 {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    unsigned int _field4;
    struct in6_addr _field5;
    unsigned int _field6;
};

struct wa_call_relay_addr {
    unsigned int _field1;
    unsigned short _field2;
};

struct wa_call_relay_token {
    unsigned char _field1[128];
    int _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned char _field1;
    char _field2[32];
    char _field3[64];
    unsigned int _field4;
    unsigned short _field5;
    int _field6;
} CDStruct_eb6bed09;

typedef struct {
    unsigned long long _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
} CDStruct_33dcf794;

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
    double _field10;
    double _field11;
    double _field12;
    double _field13;
    double _field14;
    double _field15;
    double _field16;
    double _field17;
    double _field18;
    double _field19;
    double _field20;
    double _field21;
    double _field22;
    double _field23;
    double _field24;
    double _field25;
    double _field26;
    double _field27;
    double _field28;
    double _field29;
    double _field30;
    double _field31;
    double _field32;
    double _field33;
    double _field34;
    double _field35;
    double _field36;
    double _field37;
    double _field38;
    double _field39;
    double _field40;
    double _field41;
    double _field42;
    double _field43;
    double _field44;
    double _field45;
    double _field46;
    double _field47;
    double _field48;
    double _field49;
    double _field50;
    double _field51;
    double _field52;
    double _field53;
    double _field54;
    double _field55;
    double _field56;
    double _field57;
    double _field58;
    double _field59;
    double _field60;
    double _field61;
    double _field62;
    double _field63;
    double _field64;
    char _field65[32];
    double _field66;
    double _field67;
    double _field68;
    double _field69;
    double _field70;
    double _field71;
    double _field72;
    double _field73;
    char _field74[32];
    double _field75;
    double _field76;
    double _field77;
    double _field78;
    double _field79;
    double _field80;
    double _field81;
} CDStruct_4d08f900;

typedef struct {
    long long version;
    void *info;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType copyDescription;
} CDStruct_4210025a;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct {
    long long _field1;
    long long _field2;
} CDStruct_912cb5d2;

typedef struct {
    unsigned char _field1;
    struct {
        unsigned int _field1;
        unsigned short _field2;
        unsigned char _field3;
    } _field2[20];
} CDStruct_7986d824;

typedef struct {
    unsigned char _field1;
    struct {
        unsigned int _field1;
        unsigned short _field2;
        int _field3;
    } _field2[8];
} CDStruct_376acc88;

typedef struct {
    unsigned char _field1;
    struct wa_call_relay_addr _field2[8];
} CDStruct_f4e38589;

typedef struct {
    unsigned char _field1;
    struct wa_call_relay_token _field2[8];
} CDStruct_ad9bf23c;

typedef struct {
    CDStruct_33dcf794 _field1;
    long long _field2;
    long long _field3;
} CDStruct_3e9fb80e;

typedef struct {
    struct {
        double x;
        double y;
    } origin;
    struct {
        double width;
        double height;
    } size;
} CDStruct_02837cd9;

typedef struct {
    struct {
        int _field1;
        int _field2;
        unsigned int _field3;
        unsigned int _field4;
        int _field5;
        int _field6;
        unsigned char _field7;
        int _field8;
    } _field1;
    struct {
        int _field1;
        unsigned char _field2;
        unsigned char _field3;
        unsigned char _field4;
        unsigned char _field5;
    } _field2;
    struct {
        int _field1;
        int _field2;
    } _field3;
    struct {
        unsigned char _field1;
    } _field4;
    struct {
        unsigned char _field1;
        unsigned char _field2;
        unsigned char _field3;
        unsigned char _field4;
        int _field5;
    } _field5;
    struct {
        int _field1;
        unsigned char _field2;
        int _field3;
    } _field6;
    int _field7;
    unsigned char _field8;
    int _field9;
    int _field10;
    int _field11;
    char _field12[32];
    struct wa_call_relay_addr _field13;
    struct {
        unsigned char _field1;
        unsigned char _field2;
        unsigned int _field3;
        unsigned int _field4;
        unsigned int _field5;
        unsigned char _field6;
        unsigned int _field7;
        unsigned int _field8;
    } _field14;
    struct {
        unsigned int _field1;
        unsigned int _field2;
        unsigned int _field3;
    } _field15;
    int _field16;
} CDStruct_de279dd0;

typedef struct {
    CDStruct_1b6d18a9 start;
    CDStruct_1b6d18a9 duration;
} CDStruct_e83c9415;

typedef struct {
    unsigned char _field1;
    char _field2[32];
    char _field3[64];
    unsigned int _field4;
    unsigned char _field5[256];
    int _field6;
    unsigned char _field7[32];
    int _field8;
    CDStruct_7986d824 _field9;
    CDStruct_f4e38589 _field10;
    CDStruct_ad9bf23c _field11;
    CDStruct_de279dd0 _field12;
} CDStruct_4ab296ed;

typedef struct {
    unsigned char _field1;
    char _field2[32];
    char _field3[64];
    unsigned int _field4;
    CDStruct_f4e38589 _field5;
    CDStruct_ad9bf23c _field6;
    CDStruct_de279dd0 _field7;
} CDStruct_6a54d6fe;

// Ambiguous groups
typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

