//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

@class UISwitch, WABadgedTableViewCell, WATableRow;

@interface ChatSettingsViewController : WAStaticTableViewController
{
    UISwitch *_saveReceivedMediaSwitch;
    WATableRow *_blockedRow;
    WATableRow *_textSizeRow;
    WABadgedTableViewCell *_chatBackupCell;
}

- (void).cxx_destruct;
- (void)showFontSizePicker;
- (void)switchSaveReceivedAction:(id)arg1;
- (void)backupErrorBadgeUpdated:(id)arg1;
- (void)updateChatBackupBadge;
- (void)setupTableView;
- (void)wa_fontSizeDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initWithStyle:(long long)arg1;

@end

