//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CrashReport : NSObject
{
}

+ (void)logCriticalEventWithName:(id)arg1 useActiveLog:(_Bool)arg2 skipDateCheck:(_Bool)arg3;
+ (void)logCriticalEventWithName:(id)arg1 useActiveLog:(_Bool)arg2;
+ (void)logCriticalEventWithName:(id)arg1 skipDateCheck:(_Bool)arg2;
+ (void)logCriticalEventWithName:(id)arg1;
+ (void)initializeHandlers;
+ (id)signalNumberToString:(int)arg1;
+ (id)crashInfoWithName:(id)arg1 reason:(id)arg2 addresses:(id)arg3 symbols:(id)arg4;
+ (void)resetModuleAddressedLogged;

@end

