//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CrashLogger : NSObject
{
}

+ (void)uploadDataUsingActiveLog:(_Bool)arg1 skipDateCheck:(_Bool)arg2;
+ (_Bool)crashOccurred;
+ (void)setCrashOccurred:(_Bool)arg1;
+ (_Bool)canUploadLogs;
+ (void)uploadLogData:(id)arg1 filename:(id)arg2;

@end

