//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "NSFetchedResultsControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSArray, NSFetchedResultsController, NSMutableArray, NSString, NSTimer, UIBarButtonItem, UIImageView, UILabel, UIProgressView, UIRefreshControl, UITableView, UITableViewCell, UIView, WADropDownAlertView;

@interface FavoritesViewController : WATableViewController <UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, NSFetchedResultsControllerDelegate>
{
    UIRefreshControl *_refreshControl;
    UIView *_bgView;
    UIBarButtonItem *_barButtonAdd;
    UIBarButtonItem *_barButtonDeleteAll;
    NSArray *_searchResults;
    unsigned long long _numberOfGeneratedFavoritesToNotifyUser;
    UITableViewCell *_inviteCell;
    UITableViewCell *_favoritesCountCell;
    NSFetchedResultsController *_fetchedResultsController;
    NSMutableArray *_insertedFavorites;
    _Bool _ignoreChangeNotifications;
    _Bool _animateChanges;
    _Bool _needsInitialLayout;
    _Bool _refreshingFavoritesInProgress;
    NSTimer *_progressBarTimer;
    double _estimatedLoadTime;
    long long _addressBookContactCount;
    WADropDownAlertView *_retryLaterAlertView;
    UITableView *_tableViewFavorites;
    UITableView *_tableViewButtons;
    UIImageView *_imageNoFavorites;
    UIView *_viewNoFavorites;
    UIView *_progressViewContainer;
    UILabel *_progressViewLabel;
    UIProgressView *_progressView;
}

@property(nonatomic) __weak UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak UILabel *progressViewLabel; // @synthesize progressViewLabel=_progressViewLabel;
@property(retain, nonatomic) UIView *progressViewContainer; // @synthesize progressViewContainer=_progressViewContainer;
@property(retain, nonatomic) UIView *viewNoFavorites; // @synthesize viewNoFavorites=_viewNoFavorites;
@property(retain, nonatomic) UIImageView *imageNoFavorites; // @synthesize imageNoFavorites=_imageNoFavorites;
@property(retain, nonatomic) UITableView *tableViewButtons; // @synthesize tableViewButtons=_tableViewButtons;
@property(retain, nonatomic) UITableView *tableViewFavorites; // @synthesize tableViewFavorites=_tableViewFavorites;
- (void).cxx_destruct;
- (void)wa_applicationDidEnterBackground;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 withFavorite:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerWillChangeContent:(id)arg1;
@property(readonly, nonatomic) unsigned long long favoritesCount;
- (void)faultInAllFavorites;
- (void)prefetchContactAndStatusRelationshipsForPhones:(id)arg1;
- (void)loadInitialFavorites;
- (void)contactsStorageWillReloadAddressBook:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)continueAfterSelectingPerson:(void *)arg1 property:(int)arg2 identifier:(int)arg3;
- (void)wa_fontSizeDidChange;
- (void)wa_tintColorDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)syncManagerDidFinishSync:(id)arg1;
- (void)updateProgressBar:(id)arg1;
- (void)updateProgressBar;
- (void)stopUpdatingProgressBarIfNeeded;
- (void)startUpdatingProgressBarIfNeeded;
- (void)showProgressViewIfNeeded;
- (_Bool)isProgressViewHidden;
- (void)cleanUpAfterLoadingFavorites;
- (void)hideRefreshFailedError;
- (void)showRefreshFailedError;
- (void)contactsStorageDidFailToGenerateFavorites:(id)arg1;
- (void)contactsStorageDidGenerateFavorites:(id)arg1;
- (void)stopLoading;
- (void)refreshFavorites;
- (void)refreshControlAction:(id)arg1;
- (void)deleteAllAction:(id)arg1;
- (void)addNewFavoriteAction:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)inviteContacts;
- (void)leaveSearchMode;
- (void)searchWithCriteria:(id)arg1;
- (void)reloadFavoriteCountLabel;
- (void)notifyUserAfterGeneratingFavorites:(long long)arg1;
- (void)saveTableScrollPosition;
- (void)restoreTableScrollPosition;
- (void)relayoutEmptyTableView;
- (void)updateInterfaceAnimated:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

