//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WAContactsSearchControllerDelegate.h"

@class NSArray, NSString, UILabel, UISegmentedControl, UITableView, UITableViewCell, UIToolbar, UIView, WAChatStorage, WAContactsSearchController, WAContactsStorage;

@interface ForwardPickerViewController : WAViewController <UITableViewDelegate, UITableViewDataSource, WAContactsSearchControllerDelegate>
{
    unsigned long long _sourceIndex;
    NSArray *_recents;
    NSArray *_groups;
    NSArray *_broadcasts;
    NSArray *_contactSections;
    long long _numberOfContacts;
    _Bool _dataAvailable;
    _Bool _viewDidAppear;
    WAContactsSearchController *_searchController;
    NSArray *_searchResults;
    WAChatStorage *_chatStorage;
    WAContactsStorage *_contactsStorage;
    long long _centerRowIndexPortrait;
    long long _centerRowIndexLandscape;
    _Bool _requiresConfirmation;
    CDUnknownBlockType _completionHandler;
    id <ForwardPickerDelegate> _delegate;
    UITableView *_tableViewRecents;
    UIView *_viewNoRecents;
    UITableView *_tableViewGroups;
    UIView *_viewNoGroups;
    UITableView *_tableViewBroadcasts;
    UIView *_viewNoBroadcasts;
    UITableView *_tableViewContacts;
    UIToolbar *_toolbar;
    UISegmentedControl *_segmentedControl;
    UILabel *_labelLoading;
    UITableViewCell *_cellLoading;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellNoContacts;
}

@property(retain, nonatomic) UITableViewCell *cellNoContacts; // @synthesize cellNoContacts=_cellNoContacts;
@property(retain, nonatomic) UILabel *labelNoContacts; // @synthesize labelNoContacts=_labelNoContacts;
@property(retain, nonatomic) UITableViewCell *cellLoading; // @synthesize cellLoading=_cellLoading;
@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UITableView *tableViewContacts; // @synthesize tableViewContacts=_tableViewContacts;
@property(retain, nonatomic) UIView *viewNoBroadcasts; // @synthesize viewNoBroadcasts=_viewNoBroadcasts;
@property(retain, nonatomic) UITableView *tableViewBroadcasts; // @synthesize tableViewBroadcasts=_tableViewBroadcasts;
@property(retain, nonatomic) UIView *viewNoGroups; // @synthesize viewNoGroups=_viewNoGroups;
@property(retain, nonatomic) UITableView *tableViewGroups; // @synthesize tableViewGroups=_tableViewGroups;
@property(retain, nonatomic) UIView *viewNoRecents; // @synthesize viewNoRecents=_viewNoRecents;
@property(retain, nonatomic) UITableView *tableViewRecents; // @synthesize tableViewRecents=_tableViewRecents;
@property(nonatomic) __weak id <ForwardPickerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) _Bool requiresConfirmation; // @synthesize requiresConfirmation=_requiresConfirmation;
- (void).cxx_destruct;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)cancelAction:(id)arg1;
- (void)segmentIndexChanged:(id)arg1;
- (void)contactsSearchControllerDelegateDidInvalidateSearchResults:(id)arg1;
- (void)searchWithCriteria:(id)arg1;
- (id)confirmationButtonTitle;
- (id)confirmationTextForContactInfo:(id)arg1;
- (void)addHelperText:(id)arg1 andImage:(id)arg2 toView:(id)arg3;
- (void)updateSelectedSource;
- (void)checkContactsAvailability:(id)arg1;
- (void)loadContacts;
- (void)loadBroadcasts;
- (void)loadGroups;
- (void)loadRecents;
- (void)updateTableHeader;
- (_Bool)displaySearchBar;
- (id)currentTableView;
- (void)layoutTextToImageInView:(id)arg1;
- (void)dealloc;
- (id)initWithChatStorage:(id)arg1 contactsStorage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

