//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "WAImageToImagePanPopGestureRecognizerDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WANavigationControllerPopFromAnimating.h"
#import "WASinglePhotoPickerControllerDelegate.h"
#import "WebImagePickerDelegate.h"

@class NSString, UIActivityIndicatorView, UIBarButtonItem, UIToolbar, WAActivityLabel, WAImageToImagePanPopGestureRecognizer, WebImagePicker, _WAProfilePictureScrollView;

@interface GroupIconViewController : WAViewController <WASinglePhotoPickerControllerDelegate, WebImagePickerDelegate, WAImageToImageTransitioning, WAImageToImagePanPopGestureRecognizerDelegate, WANavigationControllerPopFromAnimating>
{
    _Bool _ignoreNextProfilePictureUpdateNotification;
    _Bool _displayingPlaceholderImage;
    _Bool _displayingFullsizeImage;
    WAActivityLabel *_activityLabel;
    _WAProfilePictureScrollView *_scrollView;
    UIActivityIndicatorView *_activityIndicator;
    WebImagePicker *_webImagePicker;
    UIToolbar *_toolbar;
    UIBarButtonItem *_bbItemEditPicture;
    UIBarButtonItem *_bbItemPictureAction;
    WAImageToImagePanPopGestureRecognizer *_panPopGesture;
    _Bool _addressBookPictureAllowed;
    _Bool _updating;
    NSString *_jid;
}

+ (id)controllerWithJID:(id)arg1;
@property(readonly, nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(nonatomic) _Bool addressBookPictureAllowed; // @synthesize addressBookPictureAllowed=_addressBookPictureAllowed;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
- (void)profilePictureUpdated:(id)arg1;
- (void)wa_applicationDidEnterBackground;
- (void)webImagePickerDidCancel:(id)arg1;
- (void)webImagePicker:(id)arg1 didSelectImage:(id)arg2;
- (void)singlePhotoPickerControllerDidCancel:(id)arg1;
- (void)singlePhotoPickerController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)gestureRecognizerWillFinishManagingInteractivePopTransition:(id)arg1;
- (void)gestureRecognizerDidBeginManagingInteractivePopTransition:(id)arg1;
- (void)gestureRecognizerWillBeginManagingInteractivePopTransition:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)usesScreenEdgePanGestureRecognizerForCustomPopTransition;
- (id)popFromAnimationIdentifier;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (id)rotatingFooterView;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)pictureAction:(id)arg1;
- (void)editAction:(id)arg1;
- (void)showImageSearchController;
- (void)reallyShowImagePickerForSourceType:(long long)arg1;
- (void)showImagePickerForSourceType:(long long)arg1;
- (void)deletePicture:(_Bool)arg1;
- (void)handleDoubleTapGesture:(id)arg1;
- (void)configureScrollViewForZooming;
- (void)relayout;
- (void)reloadPicture:(_Bool)arg1;
- (void)handleReceivedFullsizeProfilePicture:(id)arg1;
- (void)hideActivityIndicator;
- (void)showActivityIndicator;
- (void)hideActivity;
- (void)showActivity:(id)arg1;
- (void)updateNavigationTitle;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

