//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDateFormatter, NSFileHandle, NSLocale, NSRecursiveLock, NSString;

@interface Logger : NSObject
{
    _Bool _allowGetCurrentQueue;
    unsigned long long _counter;
    NSLocale *_locale;
    NSDateFormatter *_dateFormatter;
    NSFileHandle *_fileHandle;
    unsigned long long _logSize;
    NSDate *_creationDate;
    NSRecursiveLock *_lock;
    NSString *_activeLog;
    NSString *_previousLog;
}

+ (id)colorFormatStringForLevel:(int)arg1;
+ (id)logLevelToString:(int)arg1;
+ (id)header;
+ (id)sharedLogger;
- (void).cxx_destruct;
- (void)fetchCompressedDataFromActiveLog:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)archiveLogsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)removeExpiredLogsInDirectory:(id)arg1;
- (void)removeExpiredLogsAsync;
- (void)write:(int)arg1 format:(id)arg2;
- (id)searchLogsAtPath:(id)arg1 fileManager:(id)arg2;
- (id)format:(id)arg1 level:(int)arg2 inColor:(_Bool)arg3;
- (void)createLogFile;
- (id)logFilePrefix;
- (id)sharedLogsDirectory;
- (id)mainLogsDirectory;
- (id)currentLogsDirectory;
- (id)init;

@end

