//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "SoundPickerDelegate.h"
#import "WALinkLabelDelegate.h"

@class NSString, UILabel, UISwitch, UIView, WAActivityLabel, WALinkLabel, WATableRow;

@interface NotificationsViewController : WAStaticTableViewController <WALinkLabelDelegate, SoundPickerDelegate>
{
    WAActivityLabel *_activityLabel;
    UIView *_headerView;
    UILabel *_headerLabel;
    WATableRow *_rowMessageSound;
    UISwitch *_switchMessageAlerts;
    WATableRow *_rowGroupSound;
    UISwitch *_switchGroupAlerts;
    WATableRow *_rowCallSound;
    UISwitch *_switchCallAlerts;
    UISwitch *_switchPreview;
    WALinkLabel *_noPreviewLinkLabel;
    long long _noPreviewSectionIndex;
    WATableRow *_rowInAppAlerts;
    WATableRow *_rowResetSettings;
    long long _pendingRequestCounter;
}

+ (id)controller;
- (void).cxx_destruct;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)settingsUpdateFailedWithError:(id)arg1;
- (void)settingsUpdateFinished;
- (void)soundPickerDidCancel:(id)arg1;
- (void)soundPicker:(id)arg1 didFinishWithSound:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)wa_fontSizeDidChange;
- (void)wa_applicationWillEnterForeground;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupTableView;
- (void)viewDidLoad;
- (void)showInAppNotificationSettings;
- (void)showPreviewAction:(id)arg1;
- (void)callAlertsAction:(id)arg1;
- (void)groupAlertsAction:(id)arg1;
- (void)messageAlertsAction:(id)arg1;
- (void)showNetworkRequiredAlertWithCompletion:(CDUnknownBlockType)arg1;
- (void)setUIEnabled:(_Bool)arg1;
- (void)reloadData;
- (void)resetNotificationSettings;
- (void)askToResetNotificationSettigs;
- (void)showSoundPickerController:(long long)arg1;
- (void)updateTableViewHeader;
- (void)hideActivity;
- (void)showActivity:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

