//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (WhatsApp)
- (id)wa_URLByAddingParameter:(id)arg1 value:(id)arg2;
- (id)wa_URLByReplacingHost:(id)arg1;
@end

