//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class UIButton, UIImageView, UILabel;

@interface PaymentEduViewController : WAViewController
{
    UIImageView *_imageViewWallpaper;
    struct UIEdgeInsets _greetingTextInsets;
    struct UIEdgeInsets _priceTextInsets;
    UIImageView *_imageServiceInfo;
    UILabel *_labelGreetingTop;
    UILabel *_labelGreetingBottom;
    UIButton *_blogPostButton;
    UIButton *_buttonContinue;
    UIButton *_buttonPayNow;
    UIButton *_buttonPayLater;
    id <PaymentEduControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <PaymentEduControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)blogPostButtonClicked:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)payLaterAction:(id)arg1;
- (void)payNowAction:(id)arg1;
- (void)continueAction:(id)arg1;
- (void)layoutSubviews;
- (void)reloadServiceInfo;
- (id)initWithDelegate:(id)arg1;

@end

