//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "WAContactsSearchControllerDelegate.h"

@class NSArray, NSSet, NSString, UIActivityIndicatorView, UIBarButtonItem, UILabel, UITableView, UITableViewCell, UIToolbar, WAContactsSearchController;

@interface PeopleViewController : WAViewController <WAContactsSearchControllerDelegate>
{
    UIBarButtonItem *_buttonSelectAll;
    NSArray *_sections;
    WAContactsSearchController *_searchController;
    NSArray *_searchResults;
    NSSet *_blockedJIDs;
    long long _numberOfContacts;
    long long _selectedCount;
    _Bool _dataAvailable;
    long long _centerRowIndexPortrait;
    long long _centerRowIndexLandscape;
    int _groupID;
    unsigned long long _pickerMode;
    long long _selectionLimit;
    NSArray *_selectedContacts;
    id <PeopleViewControllerDelegate> _delegate;
    UITableView *_tableViewContacts;
    UILabel *_labelLoading;
    UITableViewCell *_cellLoading;
    UIActivityIndicatorView *_aiLoading;
    UILabel *_labelContactsTotal;
    UITableViewCell *_cellContactsTotal;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellNoContacts;
    UIToolbar *_toolbarBottom;
    UIBarButtonItem *_buttonSelectDone;
    UIBarButtonItem *_buttonCancel;
}

@property(retain, nonatomic) UIBarButtonItem *buttonCancel; // @synthesize buttonCancel=_buttonCancel;
@property(retain, nonatomic) UIBarButtonItem *buttonSelectDone; // @synthesize buttonSelectDone=_buttonSelectDone;
@property(retain, nonatomic) UIToolbar *toolbarBottom; // @synthesize toolbarBottom=_toolbarBottom;
@property(retain, nonatomic) UITableViewCell *cellNoContacts; // @synthesize cellNoContacts=_cellNoContacts;
@property(retain, nonatomic) UILabel *labelNoContacts; // @synthesize labelNoContacts=_labelNoContacts;
@property(retain, nonatomic) UITableViewCell *cellContactsTotal; // @synthesize cellContactsTotal=_cellContactsTotal;
@property(retain, nonatomic) UILabel *labelContactsTotal; // @synthesize labelContactsTotal=_labelContactsTotal;
@property(retain, nonatomic) UIActivityIndicatorView *aiLoading; // @synthesize aiLoading=_aiLoading;
@property(retain, nonatomic) UITableViewCell *cellLoading; // @synthesize cellLoading=_cellLoading;
@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UITableView *tableViewContacts; // @synthesize tableViewContacts=_tableViewContacts;
@property(nonatomic) __weak id <PeopleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *selectedContacts; // @synthesize selectedContacts=_selectedContacts;
@property(nonatomic) long long selectionLimit; // @synthesize selectionLimit=_selectionLimit;
@property(nonatomic) unsigned long long pickerMode; // @synthesize pickerMode=_pickerMode;
@property(nonatomic) int groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayController:(id)arg1 willHideSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)selectAllAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)doneSelectingAction:(id)arg1;
- (void)contactsSearchControllerDelegateDidInvalidateSearchResults:(id)arg1;
- (void)searchWithCriteria:(id)arg1;
- (id)contactInfoForTableIndexPath:(id)arg1;
- (void)adjustSearchbarPositionAndTableviewInsets;
- (void)alignActivityIndicator;
- (void)checkDataAvailability:(id)arg1;
- (void)setupDisplayList;
- (void)updateTableHeader;
- (_Bool)displaySearchBar;
- (void)formatButtonText;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

