//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WANavigationController.h"

@interface SettingsNavigationController : WANavigationController
{
    _Bool _defersPop;
}

@property(nonatomic) _Bool defersPop; // @synthesize defersPop=_defersPop;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)init;
- (void)reloadViewControllers;

@end

