//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumberFormatter.h"

@interface TimePeriodFormatter : NSNumberFormatter
{
}

+ (id)formatWithAppropriateTimeUnit:(long long)arg1;
+ (id)pluralYears:(long long)arg1;
+ (id)pluralMonths:(long long)arg1;
+ (id)pluralDays:(long long)arg1;
+ (id)pluralHours:(long long)arg1;
+ (id)pluralMinutes:(long long)arg1;
+ (id)pluralSeconds:(long long)arg1;
- (id)stringFromTimeInterval:(double)arg1;

@end

