//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (WhatsAppExtras)
+ (id)wa_statusBarView;
+ (_Bool)wa_isProductionBuild;
+ (_Bool)wa_blurEffectsEnabled;
+ (_Bool)iOS8;
+ (_Bool)iOS7;
+ (id)packageHash;
+ (id)wa_cachesDirectory;
+ (id)wa_libraryDirectory;
+ (id)wa_documentsDirectory;
+ (id)wa_httpUserAgentString;
+ (id)wa_versionString;
+ (void)setupEnv;
+ (_Bool)isDirty;
- (id)wa_keyboardImplViewInView:(id)arg1;
- (id)wa_keyboardImplView;
- (id)wa_keyboardView;
- (id)wa_keyboardWindow;
- (double)wa_currentStatusBarHeight;
- (id)topMostWindow;
- (void)wa_clearNotificationCenterAndApplicationBadge;
- (void)showLocalNotification:(id)arg1 hasAction:(_Bool)arg2 alertAction:(id)arg3 fireDate:(id)arg4;
- (_Bool)isActive;
- (_Bool)isBackgrounded;
@end

