//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (machine)
- (_Bool)wa_shouldBeAskedToReview;
- (id)wa_memoryInfo;
- (long long)freeDiskSpace;
- (unsigned long long)totalDiskSpace;
- (double)estimatedMigrationTimeForDatabaseSize:(unsigned long long)arg1;
- (_Bool)wa_hasMulticoreProcessor;
- (id)modelName;
- (id)machine;
- (id)wa_systemBootDate;
- (_Bool)wa_isDeviceSupported;
- (_Bool)wa_isDeviceSuspicious;
- (id)wa_deviceInfoForXMPPAuth;
@end

