//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VerificationEncrypter : NSObject
{
}

+ (void)deleteRecoveryToken;
+ (void)removeRecoveryTokenFile;
+ (_Bool)setRecoveryToken:(id)arg1;
+ (_Bool)setRecoveryToken:(id)arg1 phoneNumber:(id)arg2;
+ (id)generateRecoveryToken;
+ (id)recoveryToken;
+ (id)recoveryToken:(id)arg1;
+ (id)abbreviatedPhoneNumber:(id)arg1;
+ (id)recoveryTokenFilePath;
+ (id)readRecoveryTokenFromFile:(id)arg1;
+ (_Bool)writeRecoveryTokenToFile:(id)arg1 ccAndPhoneNumber:(id)arg2;
+ (id)readRecoveryTokenFromKeychain;
+ (void)writeRecoveryTokenToKeychain:(id)arg1;
+ (id)decryptData:(id)arg1 saltLength:(long long)arg2 encodedSecret:(id)arg3 phoneNumberSecret:(id)arg4;
+ (id)saltAndEncryptData:(id)arg1 saltLength:(long long)arg2 encodedSecret:(id)arg3 phoneNumberSecret:(id)arg4;
+ (id)key:(id)arg1 encodedSecret:(id)arg2 phoneNumberSecret:(id)arg3;

@end

