//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableDictionary, NSOperationQueue, NSPort, NSString, WAFinishOperation;

@interface WAActionManager : NSObject
{
    NSOperationQueue *_queue;
    unsigned long long _options;
    int _canceling;
    int _finishing;
    NSPort *_mainThreadWaitPort;
    NSMutableDictionary *_phaseOperations;
    NSLock *_updatePhaseLock;
    unsigned long long _latestPhase;
    WAFinishOperation *_finish;
    _Bool _started;
    unsigned long long _phase;
    CDUnknownBlockType _completion;
}

@property(readonly, nonatomic) _Bool started; // @synthesize started=_started;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) unsigned long long phase; // @synthesize phase=_phase;
- (void).cxx_destruct;
@property(readonly, nonatomic) double progress;
- (double)progressForOperations:(id)arg1;
- (void)setOperations:(id)arg1 forPhase:(unsigned long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) unsigned long long maximumPhase;
- (void)setPhase:(unsigned long long)arg1;
- (void)manuallyUpdatePhaseTo:(unsigned long long)arg1;
- (void)updatePhase;
- (void)runBlockOnMainThread:(CDUnknownBlockType)arg1 waitUntilDone:(_Bool)arg2;
- (void)runBlock:(CDUnknownBlockType)arg1;
- (void)waitForCompletion;
- (void)runMainThreadRunLoop;
- (_Bool)shouldFinish;
@property(readonly) _Bool canceled;
- (_Bool)shouldCancel;
- (void)cancelWithReason:(unsigned long long)arg1;
- (void)finish;
- (id)errorForCode:(unsigned long long)arg1;
@property(readonly, nonatomic) NSString *errorDomain;
- (void)completeWithReason:(unsigned long long)arg1;
- (void)addOperations:(id)arg1;
- (void)addOperation:(id)arg1;
- (void)start;
- (_Bool)checkOption:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithOptions:(unsigned long long)arg1;

@end

