//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAccessibilityElement.h"

@interface WAAccessibilityElement : UIAccessibilityElement
{
    id _delegate;
    struct CGRect _frame;
}

@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (void).cxx_destruct;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (id)accessibilityValue;

@end

