//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WAAddressBookFieldPicker;

@protocol WAAddressBookFieldPickerDelegate <NSObject>
- (void)addressBookFieldPickerDidCancel:(WAAddressBookFieldPicker *)arg1;
- (void)addressBookFieldPicker:(WAAddressBookFieldPicker *)arg1 didFinishWithABPropertyID:(int)arg2;
@end

