//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAAddressBookUtilities : NSObject
{
}

+ (id)localizedNameOfSocialService:(id)arg1;
+ (id)localizedNameOfIMService:(id)arg1;
+ (id)localizedAddressBookLabel:(id)arg1;
+ (id)predefinedLabelsForABPropertyID:(int)arg1;
+ (id)predefinedSocialServices;
+ (id)predefinedIMServices;
+ (id)predefinedDateLabels;
+ (id)predefinedAddressLabels;
+ (id)predefinedURLLabels;
+ (id)predefinedEmailLabels;
+ (id)predefinedPhoneLabels;

@end

