//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray;

@interface WAAlertStyleTableViewCell : UITableViewCell
{
    NSMutableArray *_optionViews;
    _Bool _disabled;
    unsigned long long _selectedAlertStyle;
    CDUnknownBlockType _handler;
}

+ (long long)sizeOption;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) unsigned long long selectedAlertStyle; // @synthesize selectedAlertStyle=_selectedAlertStyle;
- (void).cxx_destruct;
- (void)tintColorDidChange;
- (double)rowHeight;
- (void)optionViewTapped:(id)arg1;
- (void)layoutSubviews;
- (void)updateSelectionState;
- (void)configure;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

