//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UICollectionViewDataSource.h"

@class ALAssetsGroup, NSArray, NSString, PHAssetCollection, PHFetchResult, UIImage;

@interface WAAssetCollection : NSObject <UICollectionViewDataSource>
{
    unsigned long long _mediaTypes;
    PHAssetCollection *_assetCollection;
    PHFetchResult *_fetchResult;
    ALAssetsGroup *_assetsGroup;
    _Bool _useReverseOrderForCollectionView;
    NSArray *_assets;
}

+ (id)sortedAssetCollectionsWithCollections:(id)arg1;
+ (void)fetchAllCollectionsForMediaTypes:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)fetchAllAssetsFromAssetsGroup:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool useReverseOrderForCollectionView; // @synthesize useReverseOrderForCollectionView=_useReverseOrderForCollectionView;
@property(readonly, nonatomic) NSArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (long long)indexOfCollectionViewMediaPickerAsset:(id)arg1;
- (id)collectionViewMediaPickerAssetAtIndex:(long long)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfVideos;
- (long long)numberOfPhotos;
- (_Bool)canQueryCountOfMediaType;
- (void)storeCountOfVideosInCameraRoll:(long long)arg1;
- (void)storeCountOfPhotosInCameraRoll:(long long)arg1;
- (void)stopCachingThumbnailsOfPixelSize:(struct CGSize)arg1 inRange:(struct _NSRange)arg2;
- (void)startCachingThumbnailsOfPixelSize:(struct CGSize)arg1 inRange:(struct _NSRange)arg2;
- (_Bool)updateWithChangeInstance:(id)arg1;
- (id)phAssetAtIndex:(unsigned long long)arg1;
- (void)fetchAssetsFromPhotosFrameworkWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchAssetsFromAssetsLibraryWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchAssetsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)refreshWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) UIImage *posterImage;
@property(readonly, nonatomic) id localIdentifier;
@property(readonly, nonatomic) unsigned long long assetCount;
@property(readonly, nonatomic) unsigned long long estimatedAssetCount;
@property(readonly, copy, nonatomic) NSString *localizedTitle;
- (id)allAssetCollectionsFromMoments:(id)arg1;
- (id)fetchResultsForAssetsWithMediaTypes:(unsigned long long)arg1 inCollection:(id)arg2;
@property(readonly, nonatomic) PHFetchResult *fetchResult;
- (id)initWithAssetsGroup:(id)arg1 mediaTypes:(unsigned long long)arg2;
- (id)initWithAssetCollection:(id)arg1 mediaTypes:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

