//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetExportSession, NSString, NSTimer, NSURL, UIImage;

@interface WAAudioTrack : NSObject
{
    CDUnknownBlockType _exportCompletionHandler;
    CDUnknownBlockType _exportProgressHandler;
    AVAssetExportSession *_exportSession;
    NSTimer *_progressTimer;
    float _lastProgressValue;
    NSURL *_assetURL;
    UIImage *_artwork;
    NSString *_title;
    NSString *_authorName;
    NSString *_collectionName;
    double _duration;
    NSString *_outputFileType;
    NSURL *_outputMediaURLWithoutFileExtension;
    NSURL *_outputMediaURL;
}

+ (id)audioFileExtensionForFileType:(id)arg1;
+ (id)cachePathForAssetURL:(id)arg1;
+ (void)pruneAudioTrackExportCacheFiles;
+ (id)pathToAudioTrackExportCacheFiles;
+ (_Bool)isMediaItemShareable:(id)arg1 error:(out id *)arg2;
@property(readonly, nonatomic) NSURL *outputMediaURL; // @synthesize outputMediaURL=_outputMediaURL;
@property(retain, nonatomic) NSURL *outputMediaURLWithoutFileExtension; // @synthesize outputMediaURLWithoutFileExtension=_outputMediaURLWithoutFileExtension;
@property(readonly, nonatomic) NSString *outputFileType; // @synthesize outputFileType=_outputFileType;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) NSString *collectionName; // @synthesize collectionName=_collectionName;
@property(readonly, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) UIImage *artwork; // @synthesize artwork=_artwork;
@property(readonly, nonatomic) NSURL *assetURL; // @synthesize assetURL=_assetURL;
- (void).cxx_destruct;
- (void)updateProgress:(id)arg1;
- (void)stopProgressTimer;
- (void)startProgressTimer;
- (void)handleExportCompletionWithSuccessfulOutcome:(_Bool)arg1;
- (void)performExport;
- (void)transferToMediaDirectoryWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addOutputFileToCache;
- (id)pathOfCachedAudioTrackFileForExport;
- (void)prepareWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithMediaItem:(id)arg1;

@end

