//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

@class NSIndexPath, UIImageView, UILabel, UIView;

@interface WAAutobackupSettingsViewController : WATableViewController
{
    double _sideTextMargin;
    _Bool _verificationMode;
    id <WAAutobackupSettingsViewControllerDelegate> _delegate;
    NSIndexPath *_selectedIndexPath;
    UIView *_viewTableFooter;
    UILabel *_labelBottomHelperText;
    UIView *_viewTableHeader;
    UILabel *_labelTopHelperText;
    UILabel *_labelTopTitle;
    UIImageView *_imageBackupLogo;
}

+ (long long)autoBackupFrequencyForIndexPath:(id)arg1;
+ (id)indexForAutoBackupFrequency:(long long)arg1;
@property(retain, nonatomic) UIImageView *imageBackupLogo; // @synthesize imageBackupLogo=_imageBackupLogo;
@property(retain, nonatomic) UILabel *labelTopTitle; // @synthesize labelTopTitle=_labelTopTitle;
@property(retain, nonatomic) UILabel *labelTopHelperText; // @synthesize labelTopHelperText=_labelTopHelperText;
@property(retain, nonatomic) UIView *viewTableHeader; // @synthesize viewTableHeader=_viewTableHeader;
@property(retain, nonatomic) UILabel *labelBottomHelperText; // @synthesize labelBottomHelperText=_labelBottomHelperText;
@property(retain, nonatomic) UIView *viewTableFooter; // @synthesize viewTableFooter=_viewTableFooter;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(nonatomic) _Bool verificationMode; // @synthesize verificationMode=_verificationMode;
@property(nonatomic) __weak id <WAAutobackupSettingsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)layoutHeaderView;
- (void)layoutFooterView;
- (id)bottomHelperText;
- (void)nextAction:(id)arg1;
- (id)init;
- (id)initWithStyle:(long long)arg1;

@end

