//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAActionManager.h"

@class WAChatStorage, WACloudBackupManager, WAFieldStatsEventICloudBackup;

@interface WABackup : WAActionManager
{
    double _startTime;
    _Bool _additionalSpaceRequired;
    _Bool _didTransferToCloud;
    unsigned long long _potentialSize;
    unsigned long long _additionalSpaceAmount;
    unsigned long long _actualSize;
    WACloudBackupManager *_manager;
    WAChatStorage *_storage;
    WAFieldStatsEventICloudBackup *_event;
}

@property _Bool didTransferToCloud; // @synthesize didTransferToCloud=_didTransferToCloud;
@property(readonly, nonatomic) WAFieldStatsEventICloudBackup *event; // @synthesize event=_event;
@property(readonly, nonatomic) WAChatStorage *storage; // @synthesize storage=_storage;
@property(readonly, nonatomic) WACloudBackupManager *manager; // @synthesize manager=_manager;
@property(nonatomic) unsigned long long actualSize; // @synthesize actualSize=_actualSize;
@property(nonatomic) unsigned long long additionalSpaceAmount; // @synthesize additionalSpaceAmount=_additionalSpaceAmount;
@property(nonatomic) _Bool additionalSpaceRequired; // @synthesize additionalSpaceRequired=_additionalSpaceRequired;
@property(nonatomic) unsigned long long potentialSize; // @synthesize potentialSize=_potentialSize;
- (void).cxx_destruct;
- (void)sendFieldStatsWithError:(id)arg1;
- (void)phaseCompleted:(id)arg1;
- (void)initializeFieldStats;
- (_Bool)test:(int)arg1 didPass:(_Bool)arg2;
- (unsigned long long)maximumPhase;
- (id)errorForCode:(unsigned long long)arg1;
- (id)errorDomain;
- (void)start;
- (id)initWithManager:(id)arg1 chatStorage:(id)arg2 options:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;

@end

