//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIFont;

@interface WABadgeView : UIView
{
    UIFont *_font;
    _Bool _highlighted;
    _Bool _selected;
    unsigned long long _badgeValue;
}

@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) unsigned long long badgeValue; // @synthesize badgeValue=_badgeValue;
- (void).cxx_destruct;
- (void)sizeToFit;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) NSString *message;
- (id)initWithFrame:(struct CGRect)arg1;

@end

