//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

#import "UIActionSheetDelegate.h"

@class NSMutableDictionary, NSString;

@interface WABlockBasedActionSheet : UIActionSheet <UIActionSheetDelegate>
{
    NSMutableDictionary *_actionMap;
    CDUnknownBlockType _destructiveActionHandler;
    _Bool _hasCancelButton;
    CDUnknownBlockType _cancelHandler;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _willResignFirstResponderHandler;
}

+ (id)actionSheetWithTitle:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType willResignFirstResponderHandler; // @synthesize willResignFirstResponderHandler=_willResignFirstResponderHandler;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(copy, nonatomic) CDUnknownBlockType cancelHandler; // @synthesize cancelHandler=_cancelHandler;
@property(nonatomic) _Bool hasCancelButton; // @synthesize hasCancelButton=_hasCancelButton;
- (void).cxx_destruct;
- (void)didPresentActionSheet:(id)arg1;
- (_Bool)canResignFirstResponder;
- (_Bool)isCancelButtonTappedOniOS6;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addDestructiveButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)addButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)showInView:(id)arg1;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(_Bool)arg3;
- (void)showFromBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)showFromToolbar:(id)arg1;
- (void)showFromTabBar:(id)arg1;
- (void)addCancelButton;
- (void)applicationWillResetUserInterface:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

