//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "SinglePersonPickerDelegate.h"

@class NSMutableArray, NSString, UITableViewCell;

@interface WABlacklistViewController : WATableViewController <SinglePersonPickerDelegate>
{
    NSMutableArray *_blockedContacts;
    UITableViewCell *_addNewCell;
}

+ (id)controller;
- (void).cxx_destruct;
- (id)excludedJIDsForSinglePersonPicker:(id)arg1;
- (void)singlePersonPicker:(id)arg1 didSelectContactInfo:(id)arg2;
- (void)singlePersonPickerDidCancel:(id)arg1;
- (void)addPerson;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)removeBlacklistItem:(id)arg1;
- (void)addBlacklistItem:(id)arg1;
- (void)showUnableToMakeChangesError;
- (_Bool)canMakeChanges;
- (void)updateInterface;
- (void)reloadBlacklistItems;
- (void)xmppConnectionStateDidChange:(id)arg1;
- (void)wa_tintColorDidChange;
- (void)wa_fontSizeDidChange;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

