//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface WABlockedContact : NSObject <NSCoding>
{
    _Bool _spam;
    _Bool _unblockPending;
    NSString *_jid;
}

@property(nonatomic) _Bool unblockPending; // @synthesize unblockPending=_unblockPending;
@property(nonatomic) _Bool spam; // @synthesize spam=_spam;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
- (_Bool)isEqualToBlockedContact:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJID:(id)arg1;

@end

