//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"

@class NSArray, NSCharacterSet, NSString, UIBarButtonItem, UISegmentedControl, UITextView, UIView;

@interface WACallHistoryViewController : WATableViewController <UISearchDisplayDelegate, UISearchBarDelegate>
{
    UISegmentedControl *_callFilterSegmentedControl;
    _Bool _showMissedCallsOnly;
    UIBarButtonItem *_clearAllButton;
    _Bool _editingSingleRow;
    NSArray *_searchResults;
    NSCharacterSet *_symbolsInPhoneNumberSet;
    NSCharacterSet *_nonNumbersSet;
    UIView *_emptyListView;
    UITextView *_emptyListViewTextView;
}

+ (id)tabBarItem;
- (void).cxx_destruct;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)showContactInfoScreenForAggregateCallEvent:(id)arg1;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (id)aggregateCallEventAtIndexPath:(id)arg1;
- (void)callFilterDidChange:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)reload;
- (void)callLoggerDidUpdateEvents:(id)arg1;
- (void)clearAll:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)editButtonTapped:(id)arg1;
- (void)reloadEmptyListView;
- (id)tableOverlayView;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)hideSearchBarIfNeeded;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

