//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface WACallEventsHeaderView : UIView
{
    UIView *_topLine;
    UIView *_topLineShadow;
    UIView *_bottomLine;
    UIView *_bottomLineShadow;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)appendEvents:(id)arg1 startingAtOffset:(double)arg2 includeDate:(_Bool)arg3;
- (id)initWithAggregateCallEvent:(id)arg1;

@end

