//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABasicCameraViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WACameraButtonViewDelegate.h"
#import "WACameraControllerDelegate.h"
#import "WACameraRollStripViewDelegate.h"
#import "WAImageToImageTransitioning.h"

@class MPVolumeView, NSMutableArray, NSObject<OS_dispatch_group>, NSString, NSTimer, UIButton, UIImage, UIImageView, UILabel, UIPinchGestureRecognizer, UISwipeGestureRecognizer, UIView, WACameraButtonView, WACameraFlashSelector, WACameraFocusBoxView, WACameraRecordingTimeView, WACameraRollStripView, WACameraWellView, WACameraZoomSlider, WAMediaPickerAsset;

@interface WACameraViewController : WABasicCameraViewController <WACameraControllerDelegate, WACameraButtonViewDelegate, WACameraRollStripViewDelegate, WAImageToImageTransitioning, UIGestureRecognizerDelegate>
{
    WACameraFocusBoxView *_focusBoxView;
    double _bottomBarHeight;
    NSMutableArray *_mediaItems;
    NSObject<OS_dispatch_group> *_processingDispatchGroup;
    WACameraFlashSelector *_flashSelector;
    UIImageView *_flashBadgeView;
    long long _suppressFlashBadgeViewCounter;
    WACameraZoomSlider *_zoomSlider;
    UIPinchGestureRecognizer *_zoomPinchGesture;
    double _zoomFactorBeforePinching;
    long long _lastBackCameraFlashMode;
    long long _lastFrontCameraFlashMode;
    NSMutableArray *_faceViews;
    _Bool _initialResetFocusBoxShown;
    _Bool _statusBarShouldReallyBeHidden;
    MPVolumeView *_hiddenVolumeView;
    float _originalVolumeLevel;
    long long _suppressVolumeTriggerCounter;
    WACameraRollStripView *_cameraRollPicker;
    UISwipeGestureRecognizer *_cameraRollSwipeUpGesture;
    UISwipeGestureRecognizer *_cameraRollSwipeDownGesture;
    long long _initialDeviceOrientation;
    WAMediaPickerAsset *_selectedMediaPickerAsset;
    NSTimer *_recordingTimer;
    WACameraRecordingTimeView *_recordingTimeView;
    UIView *_releaseToCancelOverlayView;
    _Bool _includesCameraRollPicker;
    id <WACameraViewControllerDelegate> _delegate;
    unsigned long long _initialWellCount;
    unsigned long long _maximumWellCount;
    UIImage *_initialWellPreviewImage;
    UIButton *_changeCameraButton;
    UIView *_topBarView;
    UIView *_bottomBarView;
    UIView *_bottomBarMainView;
    WACameraButtonView *_cameraButtonView;
    UIButton *_doneButton;
    WACameraWellView *_wellView;
    UILabel *_recordingHintLabel;
}

@property(nonatomic) __weak UILabel *recordingHintLabel; // @synthesize recordingHintLabel=_recordingHintLabel;
@property(nonatomic) __weak WACameraWellView *wellView; // @synthesize wellView=_wellView;
@property(nonatomic) __weak UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(nonatomic) __weak WACameraButtonView *cameraButtonView; // @synthesize cameraButtonView=_cameraButtonView;
@property(nonatomic) __weak UIView *bottomBarMainView; // @synthesize bottomBarMainView=_bottomBarMainView;
@property(retain, nonatomic) UIView *bottomBarView; // @synthesize bottomBarView=_bottomBarView;
@property(nonatomic) __weak UIView *topBarView; // @synthesize topBarView=_topBarView;
@property(nonatomic) __weak UIButton *changeCameraButton; // @synthesize changeCameraButton=_changeCameraButton;
@property(nonatomic) _Bool includesCameraRollPicker; // @synthesize includesCameraRollPicker=_includesCameraRollPicker;
@property(retain, nonatomic) UIImage *initialWellPreviewImage; // @synthesize initialWellPreviewImage=_initialWellPreviewImage;
@property(nonatomic) unsigned long long maximumWellCount; // @synthesize maximumWellCount=_maximumWellCount;
@property(nonatomic) unsigned long long initialWellCount; // @synthesize initialWellCount=_initialWellCount;
@property(nonatomic) __weak id <WACameraViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleCameraRollSwipeDown:(id)arg1;
- (void)handleCameraRollSwipeUp:(id)arg1;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)cameraRollStripViewDidChangePresentationState:(id)arg1;
- (void)cameraRollStripView:(id)arg1 didSelectMediaPickerAsset:(id)arg2;
- (void)cameraControllerDidChangeFlashActiveState:(id)arg1;
- (void)cameraControllerDidUpdateFaceObjects:(id)arg1;
- (void)cameraControllerDidChangePreviewImageSize:(id)arg1;
- (void)cameraControllerDidResetPointOfInterest:(id)arg1;
- (void)cameraControllerSessionDidStopRunning:(id)arg1;
- (void)cameraControllerSessionDidBeginRunning:(id)arg1;
@property(nonatomic, getter=isReleaseToCancelHintHidden) _Bool releaseToCancelHintHidden;
- (void)cameraButtonViewDidChangeCancelsOnRelease:(id)arg1;
- (void)cameraButtonViewDidCancelLongPress:(id)arg1;
- (void)cameraButtonViewDidReceiveTouch:(id)arg1;
- (void)cameraButtonViewDidEndLongPress:(id)arg1;
- (void)cameraButtonViewDidBeginLongPress:(id)arg1;
- (void)cameraButtonViewDidReceiveTap:(id)arg1;
- (id)sliderInVolumeView:(id)arg1;
- (void)setAudioVolume:(float)arg1;
- (void)handleAudioRouteChangeNotification:(id)arg1;
- (void)volumeDidChange:(id)arg1;
- (void)removeHiddenVolumeView;
- (void)setUpHiddenVolumeView;
- (void)updateFaces;
- (void)clearAllFaces;
- (void)handleTapToFocus:(id)arg1;
- (void)showResetFocusBox;
- (void)showFocusBoxOfWidth:(double)arg1 atPoint:(struct CGPoint)arg2;
- (void)deviceOrientationDidChangeWithAnimation:(_Bool)arg1;
- (void)recordingTimerDidFire:(id)arg1;
- (void)videoRecordingDidCancel;
- (void)videoRecordingDidFinishRecordingToFile:(id)arg1;
- (void)videoRecordingDidFailWithError:(id)arg1;
- (void)didStopVideoRecording;
- (void)willStartVideoRecording;
- (void)cancelVideoRecording;
- (void)stopVideoRecording;
- (void)startVideoRecording;
- (void)pinchGestureChanged:(id)arg1;
- (void)zoomSliderChanged:(id)arg1;
- (void)updateZoomInterfaceForCurrentCameraSettings;
- (void)updateFlashBadge;
- (void)updateFlashInterfaceForCurrentCameraSettingsWithAnimation:(_Bool)arg1;
- (void)flashModeChanged:(id)arg1;
- (void)updateCameraButtonAccessibilityValue;
- (void)changeCamera:(id)arg1;
- (void)wellTapped:(id)arg1;
- (void)updateTotalMediaCount;
- (void)captureImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)takeStillPhotoWithRepeat:(_Bool)arg1;
- (void)updateWithCurrentDeviceOrientationForCapture;
- (void)doneTakingPhotos;
- (void)done:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)updateRecordingHintLabel;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didCreateCameraController;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)wa_applicationDidEnterBackground;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

