//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "_WACameraRollStripScrollViewDelegate.h"

@class NSString, UIColor, WAAssetCollection, _WACameraRollStripScrollView;

@interface WACameraRollStripView : UIView <_WACameraRollStripScrollViewDelegate, UIGestureRecognizerDelegate>
{
    _WACameraRollStripScrollView *_scrollView;
    WAAssetCollection *_assetCollection;
    id <WACameraRollStripViewDelegate> _delegate;
    double _imageRotationAngle;
}

+ (double)preferredHeight;
@property(nonatomic) double imageRotationAngle; // @synthesize imageRotationAngle=_imageRotationAngle;
@property(nonatomic) __weak id <WACameraRollStripViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAAssetCollection *assetCollection; // @synthesize assetCollection=_assetCollection;
- (void).cxx_destruct;
- (void)cameraRollStripScrollView:(id)arg1 didDeselectItemAtIndex:(long long)arg2;
- (void)cameraRollStripScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)cameraRollStripScrollView:(id)arg1 didUnhighlightItemAtIndex:(long long)arg2;
- (void)cameraRollStripScrollView:(id)arg1 didHighlightItemAtIndex:(long long)arg2;
- (void)cameraRollStripScrollView:(id)arg1 willDisplayCell:(id)arg2 atIndex:(long long)arg3;
- (long long)numberOfItemsInCameraRollStripScrollView:(id)arg1;
- (id)viewForMediaPickerAsset:(id)arg1;
- (void)setPresentationState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setPresentationState:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long presentationState;
- (void)contractIfPossible;
- (void)expandIfPossible;
- (void)reloadData;
@property(retain, nonatomic) UIColor *baseColor;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

