//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UILabel;

@interface WACallAcceptRejectButton : UIButton
{
    UILabel *_bottomLabel;
    UIImageView *_circleView;
    unsigned long long _buttonState;
}

+ (id)button;
@property(nonatomic) unsigned long long buttonState; // @synthesize buttonState=_buttonState;
- (void).cxx_destruct;
- (id)accessibilityValue;
- (void)setButtonState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setFillColor:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

