//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CADisplayLink, CAShapeLayer, UIImageView, _WAWaterWave;

@interface WACallQualityVisualizerView : UIView
{
    _WAWaterWave *_wave1;
    _WAWaterWave *_wave2;
    CAShapeLayer *_maskLayer;
    UIImageView *_blurredImageView;
    CADisplayLink *_displayLink;
    float _smoothedCallQuality;
    _Bool _animating;
    float _callQuality;
    id <WACallQualityVisualizerViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WACallQualityVisualizerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float callQuality; // @synthesize callQuality=_callQuality;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
- (void).cxx_destruct;
- (void)willMoveToWindow:(id)arg1;
- (void)update:(id)arg1;
- (void)updateBlurredImage;
- (void)layoutSubviews;
- (void)applicationDidDismissCallScreen:(id)arg1;
- (void)applicationWillPresentCallScreen:(id)arg1;
- (void)proximityStateDidChange:(id)arg1;
- (void)dealloc;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

