//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBarDelegate.h"

@class WAChatListSearchBar;

@protocol WAChatListSearchBarDelegate <UISearchBarDelegate>
- (void)chatListSearchBarWillShowArchivedChats:(WAChatListSearchBar *)arg1;
@end

