//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UILabel, UIView, WALabel, WAProfilePictureThumbnailView, _WAChatSessionCellIndicatorsView;

@interface WAChatSessionCell : UITableViewCell
{
    double _currentFontSize;
    _Bool _muted;
    _Bool _archived;
    _Bool _showMoreButton;
    _Bool _showExitInsteadOfDelete;
    _Bool _showGroupParticipants;
    _Bool _unknownContact;
    _Bool _showLocationIcon;
    _Bool _showCameraIcon;
    _Bool _showCamcorderIcon;
    NSString *_jid;
    id <WAChatSessionCellDelegate> _delegate;
    UIView *_containerView;
    WALabel *_nameLabel;
    UILabel *_senderLabel;
    UILabel *_timeLabel;
    _WAChatSessionCellIndicatorsView *_indicatorsView;
    UIView *_lastMessageContainer;
    WALabel *_messageLabel;
    UILabel *_activityLabel;
    WAProfilePictureThumbnailView *_imageViewContactPicture;
    NSString *_messageText;
    long long _unreadCount;
    unsigned long long _pushToTalkIconType;
    NSString *_chatActivityText;
}

+ (id)camcorderIconImageHighlighted;
+ (id)camcorderIconImage;
+ (id)cameraIconImageHighlighted;
+ (id)cameraIconImage;
+ (id)locationIconImageHighlighted;
+ (id)locationIconImage;
+ (id)microphoneImageHighlighted;
+ (id)microphoneImageForPTTIconType:(unsigned long long)arg1;
+ (id)cellWithReuseIdentifier:(id)arg1;
@property(copy, nonatomic) NSString *chatActivityText; // @synthesize chatActivityText=_chatActivityText;
@property(nonatomic) unsigned long long pushToTalkIconType; // @synthesize pushToTalkIconType=_pushToTalkIconType;
@property(nonatomic) _Bool showCamcorderIcon; // @synthesize showCamcorderIcon=_showCamcorderIcon;
@property(nonatomic) _Bool showCameraIcon; // @synthesize showCameraIcon=_showCameraIcon;
@property(nonatomic) _Bool showLocationIcon; // @synthesize showLocationIcon=_showLocationIcon;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(copy, nonatomic) NSString *messageText; // @synthesize messageText=_messageText;
@property(nonatomic) _Bool unknownContact; // @synthesize unknownContact=_unknownContact;
@property(retain, nonatomic) WAProfilePictureThumbnailView *imageViewContactPicture; // @synthesize imageViewContactPicture=_imageViewContactPicture;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(retain, nonatomic) WALabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIView *lastMessageContainer; // @synthesize lastMessageContainer=_lastMessageContainer;
@property(retain, nonatomic) _WAChatSessionCellIndicatorsView *indicatorsView; // @synthesize indicatorsView=_indicatorsView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *senderLabel; // @synthesize senderLabel=_senderLabel;
@property(retain, nonatomic) WALabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <WAChatSessionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool showGroupParticipants; // @synthesize showGroupParticipants=_showGroupParticipants;
@property(nonatomic) _Bool showExitInsteadOfDelete; // @synthesize showExitInsteadOfDelete=_showExitInsteadOfDelete;
@property(nonatomic) _Bool showMoreButton; // @synthesize showMoreButton=_showMoreButton;
@property(nonatomic) _Bool archived; // @synthesize archived=_archived;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
- (void)xmppConnectionChatStateDidChange:(id)arg1;
- (void)waMessageUpdated:(id)arg1;
- (void)reloadFonts;
- (void)reconfigureWithMessage:(id)arg1;
- (void)configureWithChatSession:(id)arg1 message:(id)arg2;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
@property(nonatomic, getter=isSideSwipeGestureEnabled) _Bool sideSwipeGestureEnabled;
- (void)setChatActivityText:(id)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

