//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator, NSURL, WAChatStorage;

@interface WAChatDatabaseStatsManager : NSObject
{
    WAChatStorage *_chatStorage;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectModel *_managedObjectModel;
    NSManagedObjectContext *_managedObjectContext;
    NSURL *_persistentStoreURL;
    _Bool _isLoading;
    float _loadingProgress;
    NSArray *_allChatJIDs;
}

@property(retain, nonatomic) NSArray *allChatJIDs; // @synthesize allChatJIDs=_allChatJIDs;
@property(readonly, nonatomic) float loadingProgress; // @synthesize loadingProgress=_loadingProgress;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (void)refreshStatsRecurring:(_Bool)arg1;
- (void)saveContext;
- (void)insertStatsToDB:(id)arg1;
- (id)queryStatsForJID:(id)arg1 isRecurring:(_Bool)arg2;
- (id)statsForChatFromDBForJID:(id)arg1;
- (void)deleteAllNonrecurringStats;
- (void)deleteAllStats;
- (void)deleteDB;
- (void)makeNewDB;
- (id)managedObjectContext;
- (id)persistentStoreCoordinator;
- (id)managedObjectModel;
- (id)persistentStoreURL;
- (id)persistentStorePath;
- (id)initWithStorage:(id)arg1;

@end

