//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "SinglePersonPickerDelegate.h"
#import "WANewGroupViewControllerDelegate.h"
#import "WARecipientsViewControllerDelegate.h"

@class NSString, UIImage;

@interface WAChatComposer : UINavigationController <WARecipientsViewControllerDelegate, WANewGroupViewControllerDelegate, SinglePersonPickerDelegate>
{
    unsigned long long _mode;
    NSString *_groupSubject;
    UIImage *_groupPicture;
}

@property(retain, nonatomic) UIImage *groupPicture; // @synthesize groupPicture=_groupPicture;
@property(copy, nonatomic) NSString *groupSubject; // @synthesize groupSubject=_groupSubject;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (void)singlePersonPickerDidAskToCreateNewGroup:(id)arg1;
- (void)singlePersonPickerDidAskToInviteFriends:(id)arg1;
- (void)singlePersonPickerDidCancel:(id)arg1;
- (void)singlePersonPicker:(id)arg1 didSelectContactInfo:(id)arg2;
- (void)newGroupViewControllerDidCancel:(id)arg1;
- (void)newGroupViewController:(id)arg1 didFinishWithSubject:(id)arg2 picture:(id)arg3;
- (void)recipientsControllerDidCancel:(id)arg1;
- (void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
- (id)recipientsViewController;
- (id)newGroupViewController;
- (id)init;
- (id)initWithMode:(unsigned long long)arg1;
- (id)initWithMode:(unsigned long long)arg1 recipients:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <UINavigationControllerDelegate><WAChatComposerDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

