//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSIndexPath, NSMutableArray, NSString;

@interface WAChatMessagesController : NSObject
{
    NSMutableArray *_sections;
    short _sessionType;
    _Bool _canShowReportSpamCell;
    id <WAChatMessagesControllerDelegate> _delegate;
    NSString *_jid;
    NSArray *_highlightedTerms;
}

@property(retain, nonatomic) NSArray *highlightedTerms; // @synthesize highlightedTerms=_highlightedTerms;
@property(readonly, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(readonly, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(nonatomic) _Bool canShowReportSpamCell; // @synthesize canShowReportSpamCell=_canShowReportSpamCell;
@property(nonatomic) __weak id <WAChatMessagesControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)prependMessages:(id)arg1;
- (_Bool)appendMessages:(id)arg1 currentUnreadCount:(long long)arg2 searchResultMessageIDs:(id)arg3 addingDividerIfNecessary:(_Bool)arg4;
- (void)clearSearchResultIndicators;
- (void)deleteChatCellDataObjects:(id)arg1 updatingIndexPaths:(id)arg2;
- (void)deleteChatCellDataObjects:(id)arg1;
- (unsigned long long)removeMessages:(id)arg1;
- (void)enumerateChatCellDataUsingBlock:(CDUnknownBlockType)arg1;
- (_Bool)removeReportSpamCell;
- (_Bool)removeUnreadDivider;
- (id)chatCellDataForMessage:(id)arg1;
- (id)allSelectedCellDataObjects;
- (id)allUnsentMessagesAroundCellData:(id)arg1 cellDataObjectCount:(unsigned long long *)arg2;
- (_Bool)hasEditableMessages;
- (void)removeChatCellDataAtIndexPath:(id)arg1;
- (id)indexPathOfChatCellData:(id)arg1;
- (id)indexPathOfMessage:(id)arg1;
- (id)chatCellDataAtIndexPath:(id)arg1;
- (id)indexPathOfRowFollowingRowAtIndexPath:(id)arg1;
@property(readonly, nonatomic) NSIndexPath *bottomMostIndexPath;
- (void)removeAllMessages;
- (id)titleForSection:(long long)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfSections;
- (_Bool)isEmpty;
@property(readonly, nonatomic) NSIndexPath *reportSpamCellIndexPath;
@property(readonly, nonatomic) NSIndexPath *dividerIndexPath;
- (void)getDay:(long long *)arg1 month:(long long *)arg2 year:(long long *)arg3 fromDate:(id)arg4;
- (void)turnMessagesIntoFaultsIfPossible;
@property(readonly, nonatomic) unsigned long long messageCount;
- (id)initWithJID:(id)arg1 sessionType:(short)arg2;

@end

