//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage, WAChatBarManager;

@protocol WAChatBarManagerDelegate <NSObject>
- (void)chatBarManager:(WAChatBarManager *)arg1 didCancelPTTRecordingByUser:(_Bool)arg2;
- (void)chatBarManagerDidEndPTTRecording:(WAChatBarManager *)arg1;
- (double)chatBarManagerWillEndPTTRecording:(WAChatBarManager *)arg1;
- (void)chatBarManagerDidBeginPTTRecording:(WAChatBarManager *)arg1;
- (_Bool)chatBarManagerShouldBeginPTTRecording:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToPresentCamera:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToAttachMedia:(WAChatBarManager *)arg1;
- (void)chatBarManager:(WAChatBarManager *)arg1 didPasteImage:(UIImage *)arg2;
- (void)chatBarManager:(WAChatBarManager *)arg1 didEndDraggingChatBarWithAdditionalTranslation:(double)arg2 finalBottomInset:(double)arg3;
- (void)chatBarManagerWillBeginDraggingChatBar:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToScrollToTop:(WAChatBarManager *)arg1;
- (void)chatBarManagerUserDidFocusChatBar:(WAChatBarManager *)arg1;
- (_Bool)chatBarManagerDelegateIsDisappearing:(WAChatBarManager *)arg1;
- (_Bool)chatBarManagerDelegateIsAppearing:(WAChatBarManager *)arg1;
- (void)chatBarManager:(WAChatBarManager *)arg1 needsAdjustBottomInset:(double)arg2 withScrolling:(_Bool)arg3;
- (void)chatBarManagerUserDidSubmitText:(WAChatBarManager *)arg1 completion:(void (^)(_Bool))arg2;
- (void)chatBarManagerDidChangeText:(WAChatBarManager *)arg1;
- (double)chatBarManagerMaximumHeight:(WAChatBarManager *)arg1;
- (unsigned long long)chatBarManagerVisibleConnectionStatus:(WAChatBarManager *)arg1;
@end

