//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage, UIWindow, WAChatBar;

@protocol WAChatBarDelegate <NSObject>
- (void)chatBarWantsToScrollToTop:(WAChatBar *)arg1;
- (void)chatBarUserDidFocusChatBar:(WAChatBar *)arg1;
- (void)chatBarDidMoveToWindow:(WAChatBar *)arg1;
- (void)chatBar:(WAChatBar *)arg1 willMoveToWindow:(UIWindow *)arg2;
- (void)chatBar:(WAChatBar *)arg1 didCancelPTTRecordingByUser:(_Bool)arg2;
- (void)chatBarDidEndPTTRecording:(WAChatBar *)arg1;
- (double)chatBarWillEndPTTRecording:(WAChatBar *)arg1;
- (void)chatBarDidBeginPTTRecording:(WAChatBar *)arg1;
- (_Bool)chatBarShouldBeginPTTRecording:(WAChatBar *)arg1;
- (void)chatBarDidChangeHeight:(WAChatBar *)arg1;
- (void)chatBarUserDidSubmitText:(WAChatBar *)arg1;
- (void)chatBarWantsToPresentCamera:(WAChatBar *)arg1;
- (void)chatBarWantsToAttachMedia:(WAChatBar *)arg1;
- (void)chatBar:(WAChatBar *)arg1 didPasteImage:(UIImage *)arg2;
- (void)chatBarDidChangeText:(WAChatBar *)arg1;
- (void)chatBarDidEndEditing:(WAChatBar *)arg1;
- (void)chatBarWillEndEditing:(WAChatBar *)arg1;
- (void)chatBarDidBeginEditing:(WAChatBar *)arg1;
- (_Bool)chatBarShouldBeginEditing:(WAChatBar *)arg1;
- (double)chatBarMaximumHeight:(WAChatBar *)arg1;
- (unsigned long long)chatBarVisibleConnectionStatus:(WAChatBar *)arg1;
@end

