//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, WAChatButton;

@interface WAChatListHeaderCell : UITableViewCell
{
    WAChatButton *_broadcastButton;
    WAChatButton *_groupButton;
}

@property(readonly, nonatomic) UIButton *groupButton; // @synthesize groupButton=_groupButton;
@property(readonly, nonatomic) UIButton *broadcastButton; // @synthesize broadcastButton=_broadcastButton;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (double)preferredHeight;
- (id)init;

@end

