//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WACloudBackupManager.h"

@class CKContainer, CKDatabase, NSMutableArray, NSString;

@interface WACloudBackupManager_Kit : WACloudBackupManager
{
    CKContainer *_container;
    NSMutableArray *_timers;
    id _database;
    NSString *_localBackupPath;
}

- (void).cxx_destruct;
- (id)createDownloadOperationWithRestore:(id)arg1;
- (id)createUploadOperationWithBackup:(id)arg1 fromOperation:(id)arg2;
- (_Bool)evictFiles;
- (_Bool)logFiles;
- (void)ubiquityIdentityTokenDidChange;
- (void)checkAccountAvailability;
- (void)loadContainer;
- (void)deleteBackup:(id)arg1 exponentialTimer:(id)arg2;
- (void)deleteBackup:(id)arg1;
- (void)scheduleBackup:(id)arg1 forDeletionInAccount:(id)arg2;
- (id)createPreviousBackup;
- (id)currentRecordID;
- (_Bool)initialized;
- (_Bool)available;
- (void)setDatabase:(id)arg1;
@property(readonly, nonatomic) CKDatabase *database; // @synthesize database=_database;
- (id)localRestorePath;
- (id)localBackupPath;
- (id)initWithAutoBackupSettings:(id)arg1 errorManager:(id)arg2;

@end

