//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "ABDisabledControllerDelegate.h"
#import "ABNewPersonViewControllerDelegate.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "WAInfoInputViewControllerDelegate.h"

@class NSString, WAAggregateCallEvent, WAContact, WAMediaManager;

@interface WAContactInfoBaseViewController : WATableViewController <ABNewPersonViewControllerDelegate, ABDisabledControllerDelegate, ABPeoplePickerNavigationControllerDelegate, WAInfoInputViewControllerDelegate>
{
    void *_selectedContact;
    _Bool _dismissOnContactSaveCompletion;
    _Bool _callerIsBlocked;
    WAMediaManager *_mediaManager;
    NSString *_highlightedWhatsAppID;
    NSString *_detailTextForUnknownContact;
    WAAggregateCallEvent *_aggregateCallEvent;
    NSString *_unknownContactPageTitle;
    unsigned long long _unknownContactDataType;
    id _unknownContactData;
}

+ (id)viewControllerWithContact:(id)arg1 merged:(_Bool)arg2 whatsAppID:(id)arg3 detailText:(id)arg4;
@property(readonly, nonatomic) _Bool callerIsBlocked; // @synthesize callerIsBlocked=_callerIsBlocked;
@property(nonatomic) _Bool dismissOnContactSaveCompletion; // @synthesize dismissOnContactSaveCompletion=_dismissOnContactSaveCompletion;
@property(retain, nonatomic) id unknownContactData; // @synthesize unknownContactData=_unknownContactData;
@property(nonatomic) unsigned long long unknownContactDataType; // @synthesize unknownContactDataType=_unknownContactDataType;
@property(retain, nonatomic) NSString *unknownContactPageTitle; // @synthesize unknownContactPageTitle=_unknownContactPageTitle;
@property(retain, nonatomic) WAAggregateCallEvent *aggregateCallEvent; // @synthesize aggregateCallEvent=_aggregateCallEvent;
@property(copy, nonatomic) NSString *detailTextForUnknownContact; // @synthesize detailTextForUnknownContact=_detailTextForUnknownContact;
@property(copy, nonatomic) NSString *highlightedWhatsAppID; // @synthesize highlightedWhatsAppID=_highlightedWhatsAppID;
@property(retain, nonatomic) WAMediaManager *mediaManager; // @synthesize mediaManager=_mediaManager;
- (void).cxx_destruct;
- (void)blockedContactsListUpdated:(id)arg1;
- (void)callerBlockedStatusDidChange;
- (void)blockOrUnblockCaller;
- (void)abDisabledViewControllerDidCancel:(id)arg1;
- (void)presentDisabledAddressBookViewController;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)infoInputViewControllerDidCancel:(id)arg1;
- (void)infoInputViewControllerDidFinish:(id)arg1;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void *)arg2;
- (void)presentABNewPersonViewControllerInNavigationController:(id)arg1;
- (void)addWhatsAppIDToExistingContact;
- (void)createNewContactFromWhatsAppID;
- (void)sendMessageToUnknownContact;
- (void)callUnknownContact;
- (void)viewGroupsInCommon;
- (void)viewAllMedia;
- (void)mediaManagerDidChangeContent:(id)arg1;
- (void)mediaManagerDidChangeContent;
- (void)reportClearChatAction;
- (void)didDeleteMessages;
- (void)chatStorageDidDeleteAllMessagesInChatSession:(id)arg1;
- (void)didAddMessages;
- (void)chatStorageDidAddMessages:(id)arg1;
- (void)chatStorageDidUpdateParticipantsOfChatSession:(id)arg1;
- (void)chatStorageDidReplaceChatSession:(id)arg1;
- (void)chatStorageDidDeleteChatSessions:(id)arg1;
- (void)chatStorageDidInsertChatSessions:(id)arg1;
- (void)dismiss;
@property(readonly, nonatomic) WAContact *contact;
- (void)reloadWithContact:(id)arg1;
- (id)headerTextForLinkedContacts;
- (void)viewDidLoad;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

