//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAContactInfoBaseViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "WAContactEditViewControllerDelegate.h"
#import "WAContactInfoTableViewCellDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WANavigationControllerPopToAnimating.h"

@class NSArray, NSManagedObjectID, NSMutableArray, NSString, WACallEventsTableViewCell, WAContactInfoPageAction, WAContactInfoTableHeaderView, WAContactInfoTableViewCell, WAMergedContact;

@interface WAContactInfoViewController : WAContactInfoBaseViewController <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, UIActionSheetDelegate, WAImageToImageTransitioning, WANavigationControllerPopToAnimating, WAContactEditViewControllerDelegate, WAContactInfoTableViewCellDelegate>
{
    NSManagedObjectID *_contactID;
    WAMergedContact *_mergedContact;
    NSMutableArray *_contactInfoSections;
    NSMutableArray *_sectionHeights;
    WAContactInfoPageAction *_clearChatHistoryAction;
    WAContactInfoPageAction *_emailChatHistoryAction;
    WAContactInfoPageAction *_viewAllMediaAction;
    WAContactInfoPageAction *_blockCallerPageAction;
    WAContactInfoPageAction *_viewGroupsInCommonAction;
    WAContactInfoPageAction *_callUnknownCallerPageAction;
    _Bool _showMergedContact;
    _Bool _hasLinkedContacts;
    NSString *_jidForAnimatedTransition;
    WAContactInfoTableViewCell *_tableViewCellForAnimatedTransition;
    NSArray *_whatsAppPhoneIDs;
    NSArray *_inviteUnits;
    WACallEventsTableViewCell *_callEventsCell;
    WAContactInfoTableHeaderView *_tableHeader;
}

+ (id)viewControllerForUnkownContactWithTitle:(id)arg1 andData:(id)arg2 ofType:(unsigned long long)arg3;
@property(retain, nonatomic) WAContactInfoTableHeaderView *tableHeader; // @synthesize tableHeader=_tableHeader;
- (void).cxx_destruct;
- (_Bool)shouldBeginCustomPopAnimationForAnimationIdentifier:(id)arg1;
- (id)popAnimationControllerFromViewController:(id)arg1;
- (id)popAnimationInteractionControllerFromViewController:(id)arg1;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)profilePictureUpdated:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)cellForContact:(id)arg1 indexPath:(id)arg2 tableView:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)contactEditControllerDidCancel:(id)arg1;
- (void)contactEditControllerDidSave:(id)arg1;
- (void)editAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)setupAsUnknownContactViewer;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)inviteViaEmail:(id)arg1;
- (void)inviteViaSMS:(id)arg1;
- (void)inviteContactViaPhoneOrEmail:(id)arg1;
- (void)inviteContact;
- (void)profilePictureTappedInContactInfoCell:(id)arg1;
- (void)callButtonTappedInContactInfoCell:(id)arg1;
- (void)messageButtonTappedInContactInfoCell:(id)arg1;
- (void)startChatWithJID:(id)arg1;
- (void)sendMessageToContact;
- (void)setUpMediaManager;
- (void)didDeleteMessages;
- (void)didAddMessages;
- (void)clearChatHistory;
- (void)emailChatHistory;
- (void)askToAttachMediaForChatSession:(id)arg1;
- (void)emailChatHistoryForWAChatSession:(id)arg1 withMedia:(_Bool)arg2;
- (void)callerBlockedStatusDidChange;
- (void)updateBlockCallerPageAction;
- (void)setAggregateCallEvent:(id)arg1;
- (void)rebuildContactInfoDataUnitsForKnownContact;
- (void)rebuildContactInfoDataUnitsForUnknownContact;
- (void)reload;
- (id)headerTextForLinkedContacts;
- (void)setContact:(id)arg1;
- (id)contact;
- (void)callStateDidChange:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)reloadWithContact:(id)arg1;
- (id)initWithContact:(id)arg1 merged:(_Bool)arg2 whatsAppID:(id)arg3 detailText:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

