//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, WAChatStorage, WAContactsStorage;

@interface WAContactsSearchController : NSObject
{
    WAChatStorage *_chatStorage;
    WAContactsStorage *_contactsStorage;
    id <WAContactsSearchControllerDelegate> _delegate;
    NSArray *_allContactInfos;
}

@property(retain, nonatomic) NSArray *allContactInfos; // @synthesize allContactInfos=_allContactInfos;
@property(nonatomic) __weak id <WAContactsSearchControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)contactsMatchingText:(id)arg1;
- (id)contactsMatchingJIDs:(id)arg1;
- (void)loadIfNeeded;
- (void)reset;
- (void)syncManagerDidFinishSync:(id)arg1;
- (void)dealloc;
- (id)initWithChatStorage:(id)arg1 contactsStorage:(id)arg2;

@end

