//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

#import "UITextFieldDelegate.h"

@class NSString, UIView, WAGradientView;

@interface WAContactPropertyTextField : UITextField <UITextFieldDelegate>
{
    WAGradientView *_verticalSeparator;
    UIView *_bottomBorder;
    _Bool _showLeftBorder;
    _Bool _showBottomBorder;
    NSString *_value;
    id <WAContactPropertyTextFieldDelegate> _textFieldDelegate;
    struct UIEdgeInsets _textInset;
    struct UIEdgeInsets _bottomSeparatorInset;
}

@property(nonatomic) __weak id <WAContactPropertyTextFieldDelegate> textFieldDelegate; // @synthesize textFieldDelegate=_textFieldDelegate;
@property(nonatomic) struct UIEdgeInsets bottomSeparatorInset; // @synthesize bottomSeparatorInset=_bottomSeparatorInset;
@property(nonatomic) _Bool showBottomBorder; // @synthesize showBottomBorder=_showBottomBorder;
@property(nonatomic) _Bool showLeftBorder; // @synthesize showLeftBorder=_showLeftBorder;
@property(nonatomic) struct UIEdgeInsets textInset; // @synthesize textInset=_textInset;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
- (void).cxx_destruct;
- (void)textFieldValueChanged:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)setPlaceholder:(id)arg1;
- (void)layoutSubviews;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)arg1;
- (struct CGRect)clearButtonRectForBounds:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

