//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImage, UILabel, WALabel;

@interface WAConversationHeaderView : UIView
{
    _Bool _compactHeight;
    _Bool _groupLayout;
    _Bool _profilePictureHidden;
    _Bool _callButtonHidden;
    _Bool _pictureTapable;
    _Bool _tapable;
    _Bool _fadingCaptionLabel;
    _Bool _animating;
    id <WAConversationHeaderViewDelegate> _delegate;
    UIButton *_profilePictureButton;
    UIImage *_profilePicture;
    NSString *_title;
    NSString *_caption;
    NSString *_captionTextForVoiceOver;
    NSString *_activityText;
    WALabel *_titleLabel;
    UILabel *_captionLabel;
    UILabel *_activityLabel;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_headerViewButton;
}

+ (id)captionLabelTextForCaption:(id)arg1 isCompactHeight:(_Bool)arg2 isGroupLayout:(_Bool)arg3;
+ (id)mapHeaderView;
+ (id)headerViewWithDelegate:(id)arg1;
@property(nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) _Bool fadingCaptionLabel; // @synthesize fadingCaptionLabel=_fadingCaptionLabel;
@property(retain, nonatomic) UIButton *headerViewButton; // @synthesize headerViewButton=_headerViewButton;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(retain, nonatomic) UILabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(retain, nonatomic) WALabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *activityText; // @synthesize activityText=_activityText;
@property(copy, nonatomic) NSString *captionTextForVoiceOver; // @synthesize captionTextForVoiceOver=_captionTextForVoiceOver;
@property(copy, nonatomic) NSString *caption; // @synthesize caption=_caption;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *profilePicture; // @synthesize profilePicture=_profilePicture;
@property(retain, nonatomic) UIButton *profilePictureButton; // @synthesize profilePictureButton=_profilePictureButton;
@property(nonatomic, getter=isTapable) _Bool tapable; // @synthesize tapable=_tapable;
@property(nonatomic, getter=isPictureTapable) _Bool pictureTapable; // @synthesize pictureTapable=_pictureTapable;
@property(nonatomic, getter=isCallButtonHidden) _Bool callButtonHidden; // @synthesize callButtonHidden=_callButtonHidden;
@property(nonatomic, getter=isProfilePictureHidden) _Bool profilePictureHidden; // @synthesize profilePictureHidden=_profilePictureHidden;
@property(nonatomic, getter=isGroupLayout) _Bool groupLayout; // @synthesize groupLayout=_groupLayout;
@property(nonatomic, getter=isCompactHeight) _Bool compactHeight; // @synthesize compactHeight=_compactHeight;
@property(nonatomic) __weak id <WAConversationHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)isAccessibilityElement;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setProfilePicture:(id)arg1 animated:(_Bool)arg2;
- (void)headerViewTapped:(id)arg1;
- (void)profilePictureTapped:(id)arg1;
- (id)captionFontForCompactHeight:(_Bool)arg1 groupLayout:(_Bool)arg2;
- (id)titleFontForCompactHeight:(_Bool)arg1 groupLayout:(_Bool)arg2;
- (void)setCaption:(id)arg1 animated:(_Bool)arg2;
- (void)configureVoiceOver;
- (void)configureTitleAndCaption;
- (id)initWithFrame:(struct CGRect)arg1;

@end

