//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WAContactPropertyTextFieldDelegate.h"

@class NSMutableArray, NSString, UIButton, UIFont, UIImageView, WAMergedContact;

@interface WAContactEditingHeaderView : UIView <WAContactPropertyTextFieldDelegate>
{
    _Bool _hasPhoto;
    unsigned int _nameFormat;
    id <WAContactEditingHeaderViewDelegate> _delegate;
    WAMergedContact *_mergedContact;
    UIFont *_textFieldFont;
    UIView *_viewPhoto;
    UIImageView *_imageViewPhoto;
    UIButton *_buttonAddPhoto;
    UIButton *_buttonEditPhoto;
    NSMutableArray *_textFields;
}

+ (void)initialize;
@property(nonatomic) unsigned int nameFormat; // @synthesize nameFormat=_nameFormat;
@property(retain, nonatomic) NSMutableArray *textFields; // @synthesize textFields=_textFields;
@property(retain, nonatomic) UIButton *buttonEditPhoto; // @synthesize buttonEditPhoto=_buttonEditPhoto;
@property(retain, nonatomic) UIButton *buttonAddPhoto; // @synthesize buttonAddPhoto=_buttonAddPhoto;
@property(retain, nonatomic) UIImageView *imageViewPhoto; // @synthesize imageViewPhoto=_imageViewPhoto;
@property(retain, nonatomic) UIView *viewPhoto; // @synthesize viewPhoto=_viewPhoto;
@property(nonatomic) _Bool hasPhoto; // @synthesize hasPhoto=_hasPhoto;
@property(retain, nonatomic) UIFont *textFieldFont; // @synthesize textFieldFont=_textFieldFont;
@property(retain, nonatomic) WAMergedContact *mergedContact; // @synthesize mergedContact=_mergedContact;
@property(nonatomic) __weak id <WAContactEditingHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)isFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)contactPropertyTextFieldValueChanged:(id)arg1;
- (_Bool)contactPropertyTextFieldShouldReturn:(id)arg1;
- (id)unusedContactHeaderProperties;
- (id)allContactHeaderProperties;
- (void)editPhotoAction:(id)arg1;
- (void)reloadContactPhoto;
- (void)reloadContactData;
- (id)addTextFieldForABPropertyID:(int)arg1 withValue:(id)arg2;
- (id)addTextFieldForABPropertyID:(int)arg1 withValue:(id)arg2 makeActive:(_Bool)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

