//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSManagedObjectID, NSMutableDictionary, NSString;

@interface WAContactInfo : NSObject
{
    NSMutableDictionary *_userInfo;
    _Bool _enabled;
    _Bool _selected;
    int _addressBookID;
    NSString *_fullName;
    NSString *_firstName;
    NSString *_jid;
    NSString *_highlightedName;
    NSString *_statusText;
    NSString *_detailText;
    NSArray *_tokens;
    NSManagedObjectID *_waContactObjectID;
}

@property(retain, nonatomic) NSManagedObjectID *waContactObjectID; // @synthesize waContactObjectID=_waContactObjectID;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSArray *tokens; // @synthesize tokens=_tokens;
@property(copy, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(copy, nonatomic) NSString *statusText; // @synthesize statusText=_statusText;
@property(copy, nonatomic) NSString *highlightedName; // @synthesize highlightedName=_highlightedName;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(nonatomic) int addressBookID; // @synthesize addressBookID=_addressBookID;
- (void).cxx_destruct;
- (void)setUserInfoObject:(id)arg1 forKey:(id)arg2;
@property(copy, nonatomic) NSDictionary *userInfo;
- (id)parentContact;
- (id)initWithChatSession:(id)arg1;
- (id)initWithContact:(id)arg1;
- (id)initWithWAContactObjectID:(id)arg1;

@end

