//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WAAddressBookCountryPickerDelegate.h"
#import "WAAddressBookFieldPickerDelegate.h"
#import "WAAddressBookLabelPickerDelegate.h"
#import "WAContactAddressEditingCellDelegate.h"
#import "WAContactEditingHeaderViewDelegate.h"
#import "WAContactMultiValueEditingCellDelegate.h"
#import "WASinglePhotoPickerControllerDelegate.h"

@class NSArray, NSIndexPath, NSString, UITableView, WAContactEditingHeaderView, WAMergedContact;

@interface WAContactEditViewController : WAViewController <UITableViewDataSource, UITableViewDelegate, WAContactEditingHeaderViewDelegate, WAAddressBookLabelPickerDelegate, WAAddressBookCountryPickerDelegate, WAAddressBookFieldPickerDelegate, WAContactMultiValueEditingCellDelegate, WAContactAddressEditingCellDelegate, WASinglePhotoPickerControllerDelegate>
{
    double _keyboardHeight;
    NSArray *_properties;
    long long _addFieldSectionIndex;
    long long _deleteContactSectionIndex;
    NSIndexPath *_indexPathForEditingCell;
    double _labelSectionWidthMain;
    double _labelSectionWidthOthers;
    id <WAContactEditViewControllerDelegate> _delegate;
    UITableView *_tableView;
    WAContactEditingHeaderView *_tableHeader;
    WAMergedContact *_originalContact;
    WAMergedContact *_editingContact;
}

+ (id)controllerForMergedContact:(id)arg1;
@property(readonly, copy, nonatomic) WAMergedContact *editingContact; // @synthesize editingContact=_editingContact;
@property(readonly, nonatomic) WAMergedContact *originalContact; // @synthesize originalContact=_originalContact;
@property(retain, nonatomic) WAContactEditingHeaderView *tableHeader; // @synthesize tableHeader=_tableHeader;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WAContactEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)scrollToEditingTableViewCellAnimated:(_Bool)arg1;
- (void)adjustContentInsetForKeyboardHeight:(double)arg1;
- (void)hideKeyboard;
- (void)contactNoteCellNeedsResize:(id)arg1;
- (void)addressBookCountryPickerDidCancel:(id)arg1;
- (void)addressBookCountryPicker:(id)arg1 didSelectCountryCode:(id)arg2;
- (void)presentCountryPickerForAddressEditingCell:(id)arg1;
- (void)addressBookLabelPickerDidFinish:(id)arg1;
- (void)addressBookLabelPickerDidCancel:(id)arg1;
- (void)handleLabelButtonActionInContactMultiValueEditingCell:(id)arg1;
- (void)contactPropertyEditingCellValueChanged:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldReturn:(id)arg1;
- (void)contactPropertyEditingCellDidEndEditing:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldEndEditing:(id)arg1;
- (void)contactPropertyEditingCellDidBeginEditing:(id)arg1;
- (_Bool)contactPropertyEditingCellShouldBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)validateChanges;
- (void)doneAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidLoad;
- (void)loadView;
- (void)singlePhotoPickerControllerDidCancel:(id)arg1;
- (void)singlePhotoPickerController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)reallyShowImagePickerForSourceType:(long long)arg1;
- (void)showImagePickerForSourceType:(long long)arg1;
- (void)deleteCurrentContactImage;
- (void)editCurrentContactImage;
- (void)setContactImage:(id)arg1;
- (void)contactEditingHeaderEditPhotoTapped:(id)arg1;
- (void)contactEditingHeaderValueChanged:(id)arg1;
- (_Bool)contactEditingHeaderViewShouldReturn:(id)arg1;
- (void)addressBookFieldPickerDidCancel:(id)arg1;
- (void)addressBookFieldPicker:(id)arg1 didFinishWithABPropertyID:(int)arg2;
- (void)addContactPropertyField;
- (void)reloadHeaderView;
- (void)deleteContact;
- (void)reallyDeleteContact;
- (void)calculateLabelSectionWidth;
- (id)contactPropertyForTableIndexPath:(id)arg1;
- (id)contactPropertyForTableSection:(long long)arg1;
- (id)tableIndexPathForContactProperty:(id)arg1;
- (void)addNewValueToMultiValueProperty:(id)arg1;
- (void)rebuildContactData;
- (void)setMergedContact:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

