//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WAContactEditingHeaderView;

@protocol WAContactEditingHeaderViewDelegate <NSObject>
- (void)contactEditingHeaderValueChanged:(WAContactEditingHeaderView *)arg1;
- (void)contactEditingHeaderEditPhotoTapped:(WAContactEditingHeaderView *)arg1;
- (_Bool)contactEditingHeaderViewShouldReturn:(WAContactEditingHeaderView *)arg1;
@end

