//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSFastEnumeration.h"

@class NSArray, NSMutableArray;

@interface WAContactMultiValueProperty : NSObject <NSCopying, NSFastEnumeration>
{
    NSMutableArray *_deletedProperties;
    int _abPropertyID;
    NSArray *_properties;
}

+ (id)propertyWithABProperty:(int)arg1 properties:(id)arg2;
@property(retain, nonatomic) NSArray *properties; // @synthesize properties=_properties;
@property(nonatomic) int abPropertyID; // @synthesize abPropertyID=_abPropertyID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqualToProperty:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)enumeratePropertiesAtIndexes:(id)arg1 options:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)enumeratePropertiesWithOptions:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumeratePropertiesUsingBlock:(CDUnknownBlockType)arg1;
- (id)propertiesPassingTest:(CDUnknownBlockType)arg1;
- (unsigned long long)indexOfPropertyIdenticalTo:(id)arg1;
- (void)removePropertyAtIndex:(unsigned long long)arg1;
- (void)addPropertiesFromArray:(id)arg1;
- (void)addProperty:(id)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)propertyAtIndex:(unsigned long long)arg1;
- (id)lastProperty;
- (id)firstProperty;
@property(readonly) unsigned long long count;
@property(readonly, nonatomic) NSArray *deletedProperties;
- (id)init;
- (id)initWithABProperty:(int)arg1 properties:(id)arg2;

@end

