//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WACloudInteractionBackupOperation_Documents.h"

@class WARestore;

@interface WADownloadBackupOperation_Documents : WACloudInteractionBackupOperation_Documents
{
    WARestore *_restore;
    double _progress;
}

- (void).cxx_destruct;
- (_Bool)processResults:(id)arg1;
- (void)startDownloadingAllBackupFiles;
- (void)run;
- (double)progress;
- (id)initWithRestore:(id)arg1;

@end

