//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WACloudInteractionOperation_Kit.h"

@class CKDatabase, NSDictionary, WARestore;

@interface WADownloadBackupOperation_Kit : WACloudInteractionOperation_Kit
{
    CKDatabase *_database;
    WARestore *_restore;
    NSDictionary *_assets;
}

- (void).cxx_destruct;
- (id)pathForRemoteFile:(id)arg1;
- (void)downloadRecords:(id)arg1;
- (void)discoverFiles;
- (void)run;
- (id)initWithManager:(id)arg1;

@end

