//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, WALabel;

@interface WAEventBubbleView : UIView
{
    UIImageView *_imageViewBubble;
    WALabel *_labelEvent;
}

+ (struct CGSize)sizeForEventText:(id)arg1 forWidth:(double)arg2;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)fontSizeDidChange:(id)arg1;
@property(copy, nonatomic) NSString *eventText;
- (void)dealloc;
- (id)init;

@end

