//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventBroadcastFanout : WAFieldStatsEvent
{
    double _broadcast_fanout_t;
    double _broadcast_sent_recipient_count;
}

@property(nonatomic) double broadcast_sent_recipient_count; // @synthesize broadcast_sent_recipient_count=_broadcast_sent_recipient_count;
@property(nonatomic) double broadcast_fanout_t; // @synthesize broadcast_fanout_t=_broadcast_fanout_t;
- (void)submit;
- (id)init;

@end

