//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventAddressbookSync : WAFieldStatsEvent
{
    double _addressbook_sync_error_code;
    double _addressbook_sync_is_reg;
    double _addressbook_sync_result_type;
    double _addressbook_sync_t;
}

@property(nonatomic) double addressbook_sync_t; // @synthesize addressbook_sync_t=_addressbook_sync_t;
@property(nonatomic) double addressbook_sync_result_type; // @synthesize addressbook_sync_result_type=_addressbook_sync_result_type;
@property(nonatomic) double addressbook_sync_is_reg; // @synthesize addressbook_sync_is_reg=_addressbook_sync_is_reg;
@property(nonatomic) double addressbook_sync_error_code; // @synthesize addressbook_sync_error_code=_addressbook_sync_error_code;
- (void)submit;
- (id)init;

@end

