//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventMessageSend : WAFieldStatsEvent
{
    double _media_caption_present;
    double _message_is_forward;
    double _message_is_international;
    double _message_media_type;
    double _message_send_result;
    double _message_type;
    double _retry_count;
    double _message_send_t;
}

@property(nonatomic) double message_send_t; // @synthesize message_send_t=_message_send_t;
@property(nonatomic) double retry_count; // @synthesize retry_count=_retry_count;
@property(nonatomic) double message_type; // @synthesize message_type=_message_type;
@property(nonatomic) double message_send_result; // @synthesize message_send_result=_message_send_result;
@property(nonatomic) double message_media_type; // @synthesize message_media_type=_message_media_type;
@property(nonatomic) double message_is_international; // @synthesize message_is_international=_message_is_international;
@property(nonatomic) double message_is_forward; // @synthesize message_is_forward=_message_is_forward;
@property(nonatomic) double media_caption_present; // @synthesize media_caption_present=_media_caption_present;
- (void)submit;
- (id)init;

@end

