//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventCrashLog : WAFieldStatsEvent
{
    NSString *_crash_exception;
    NSString *_crash_reason;
}

@property(retain, nonatomic) NSString *crash_reason; // @synthesize crash_reason=_crash_reason;
@property(retain, nonatomic) NSString *crash_exception; // @synthesize crash_exception=_crash_exception;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

