//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventProfilePicUpload : WAFieldStatsEvent
{
    double _profile_pic_upload_result;
    double _retry_count;
    double _profile_pic_size;
    double _profile_pic_upload_t;
}

@property(nonatomic) double profile_pic_upload_t; // @synthesize profile_pic_upload_t=_profile_pic_upload_t;
@property(nonatomic) double profile_pic_size; // @synthesize profile_pic_size=_profile_pic_size;
@property(nonatomic) double retry_count; // @synthesize retry_count=_retry_count;
@property(nonatomic) double profile_pic_upload_result; // @synthesize profile_pic_upload_result=_profile_pic_upload_result;
- (void)submit;
- (id)init;

@end

