//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventBbxHubUpdateInbox : WAFieldStatsEvent
{
    double _bbx_hub_result;
    double _bbx_hub_update_inbox_attempts;
}

@property(nonatomic) double bbx_hub_update_inbox_attempts; // @synthesize bbx_hub_update_inbox_attempts=_bbx_hub_update_inbox_attempts;
@property(nonatomic) double bbx_hub_result; // @synthesize bbx_hub_result=_bbx_hub_result;
- (void)submit;
- (id)init;

@end

