//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventFsBuffer : WAFieldStatsEvent
{
    double _client_ts;
    double _fs_buffer_error;
    double _fs_buffer_age;
    double _fs_buffer_size;
    double _fs_client_time_skew;
    double _fs_num_dimensions;
    double _fs_num_metrics;
    double _fs_time_shift;
}

@property(nonatomic) double fs_time_shift; // @synthesize fs_time_shift=_fs_time_shift;
@property(nonatomic) double fs_num_metrics; // @synthesize fs_num_metrics=_fs_num_metrics;
@property(nonatomic) double fs_num_dimensions; // @synthesize fs_num_dimensions=_fs_num_dimensions;
@property(nonatomic) double fs_client_time_skew; // @synthesize fs_client_time_skew=_fs_client_time_skew;
@property(nonatomic) double fs_buffer_size; // @synthesize fs_buffer_size=_fs_buffer_size;
@property(nonatomic) double fs_buffer_age; // @synthesize fs_buffer_age=_fs_buffer_age;
@property(nonatomic) double fs_buffer_error; // @synthesize fs_buffer_error=_fs_buffer_error;
@property(nonatomic) double client_ts; // @synthesize client_ts=_client_ts;
- (void)submit;
- (id)init;

@end

