//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventICloudBackup : WAFieldStatsEvent
{
    double _icloud_backup_age;
    double _icloud_backup_result;
    double _icloud_calllog_size;
    double _icloud_chatdb_size;
    double _icloud_media_tar_estimate;
    double _icloud_media_tar_size;
    double _icloud_media_tar_t;
    double _icloud_searchdb_size;
    double _icloud_t;
    double _icloud_thumb_tar_estimate;
    double _icloud_thumb_tar_size;
    double _icloud_thumb_tar_t;
}

@property(nonatomic) double icloud_thumb_tar_t; // @synthesize icloud_thumb_tar_t=_icloud_thumb_tar_t;
@property(nonatomic) double icloud_thumb_tar_size; // @synthesize icloud_thumb_tar_size=_icloud_thumb_tar_size;
@property(nonatomic) double icloud_thumb_tar_estimate; // @synthesize icloud_thumb_tar_estimate=_icloud_thumb_tar_estimate;
@property(nonatomic) double icloud_t; // @synthesize icloud_t=_icloud_t;
@property(nonatomic) double icloud_searchdb_size; // @synthesize icloud_searchdb_size=_icloud_searchdb_size;
@property(nonatomic) double icloud_media_tar_t; // @synthesize icloud_media_tar_t=_icloud_media_tar_t;
@property(nonatomic) double icloud_media_tar_size; // @synthesize icloud_media_tar_size=_icloud_media_tar_size;
@property(nonatomic) double icloud_media_tar_estimate; // @synthesize icloud_media_tar_estimate=_icloud_media_tar_estimate;
@property(nonatomic) double icloud_chatdb_size; // @synthesize icloud_chatdb_size=_icloud_chatdb_size;
@property(nonatomic) double icloud_calllog_size; // @synthesize icloud_calllog_size=_icloud_calllog_size;
@property(nonatomic) double icloud_backup_result; // @synthesize icloud_backup_result=_icloud_backup_result;
@property(nonatomic) double icloud_backup_age; // @synthesize icloud_backup_age=_icloud_backup_age;
- (void)submit;
- (id)init;

@end

