//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventMmdDownload : WAFieldStatsEvent
{
    NSString *_app_version;
    double _http_response_code;
    double _mcc;
    double _media_type;
    NSString *_mmd_error_reason;
    double _mnc;
    NSString *_os_version;
    double _platform;
    NSString *_server_name;
    double _user_id;
    double _media_size;
    double _mmd_download_t;
    double _mmd_ref_age;
}

@property(nonatomic) double mmd_ref_age; // @synthesize mmd_ref_age=_mmd_ref_age;
@property(nonatomic) double mmd_download_t; // @synthesize mmd_download_t=_mmd_download_t;
@property(nonatomic) double media_size; // @synthesize media_size=_media_size;
@property(nonatomic) double user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSString *server_name; // @synthesize server_name=_server_name;
@property(nonatomic) double platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSString *os_version; // @synthesize os_version=_os_version;
@property(nonatomic) double mnc; // @synthesize mnc=_mnc;
@property(retain, nonatomic) NSString *mmd_error_reason; // @synthesize mmd_error_reason=_mmd_error_reason;
@property(nonatomic) double media_type; // @synthesize media_type=_media_type;
@property(nonatomic) double mcc; // @synthesize mcc=_mcc;
@property(nonatomic) double http_response_code; // @synthesize http_response_code=_http_response_code;
@property(retain, nonatomic) NSString *app_version; // @synthesize app_version=_app_version;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

