//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventBbxBbidCall : WAFieldStatsEvent
{
    double _bbx_bbid_failure_reason;
    double _bbx_bbid_request;
    double _bbx_bbid_result;
}

@property(nonatomic) double bbx_bbid_result; // @synthesize bbx_bbid_result=_bbx_bbid_result;
@property(nonatomic) double bbx_bbid_request; // @synthesize bbx_bbid_request=_bbx_bbid_request;
@property(nonatomic) double bbx_bbid_failure_reason; // @synthesize bbx_bbid_failure_reason=_bbx_bbid_failure_reason;
- (void)submit;
- (id)init;

@end

