//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface WAFieldStats : NSObject
{
    struct __sFILE *_file;
    long long _fileOffset;
    int _recordCount;
    unsigned int _timestamp;
    int _missedUpdateCount;
    _Bool _rotatedExists;
    _Bool _isInsideEvent;
    _Bool _isNew;
    NSMutableArray *_cachedRecords;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)preCacheKnownDimensions;
- (_Bool)addRecordToCache:(id)arg1;
- (id)findCachedRecord:(int)arg1 uniqueId:(unsigned int)arg2;
- (_Bool)rotateFile;
- (void)appendRecord:(id)arg1;
- (void)postWrite;
- (_Bool)preWrite:(id)arg1;
- (long long)writeRecord:(id)arg1;
- (long long)writeRecord:(id)arg1 offset:(long long)arg2;
- (void)closeFieldStatsFile;
- (_Bool)openFieldStatsFile;
- (_Bool)createFile;
- (_Bool)openFile;
- (int)readRecordFromFile:(struct __sFILE *)arg1 record:(out id *)arg2;
- (id)rotatedFileName;
- (id)fileName;
- (id)fieldStatsDirectory;
- (_Bool)isFileExists:(id)arg1;
- (unsigned int)unixTimestamp;
- (void)numericRecord:(unsigned int)arg1 type:(int)arg2 value:(double)arg3;
- (void)stringRecord:(unsigned int)arg1 stringValue:(id)arg2;
- (double)qNaN;
- (void)event:(int)arg1 records:(id)arg2;
- (void)metric:(int)arg1 timer:(double)arg2;
- (void)metric:(int)arg1 gauge:(double)arg2;
- (void)metric:(int)arg1 increment:(long long)arg2;
- (void)clearNumericDimension:(int)arg1;
- (void)clearStringDimension:(int)arg1;
- (void)dimension:(int)arg1 numericValue:(double)arg2;
- (void)dimension:(int)arg1 stringValue:(id)arg2;
- (void)clearStatsData;
- (id)statsData;
- (_Bool)isReadyToSend;
- (id)init;

@end

