//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventE2eMessageRecv : WAFieldStatsEvent
{
    double _e2e_ciphertext_type;
    double _e2e_ciphertext_version;
    double _e2e_destination;
    double _e2e_failure_reason;
    double _e2e_successful;
    double _retry_count;
}

@property(nonatomic) double retry_count; // @synthesize retry_count=_retry_count;
@property(nonatomic) double e2e_successful; // @synthesize e2e_successful=_e2e_successful;
@property(nonatomic) double e2e_failure_reason; // @synthesize e2e_failure_reason=_e2e_failure_reason;
@property(nonatomic) double e2e_destination; // @synthesize e2e_destination=_e2e_destination;
@property(nonatomic) double e2e_ciphertext_version; // @synthesize e2e_ciphertext_version=_e2e_ciphertext_version;
@property(nonatomic) double e2e_ciphertext_type; // @synthesize e2e_ciphertext_type=_e2e_ciphertext_type;
- (void)submit;
- (id)init;

@end

