//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventContactUsSession : WAFieldStatsEvent
{
    double _contact_us_automatic_email;
    double _contact_us_exit_state;
    double _contact_us_faq;
    double _contact_us_logs;
    double _contact_us_outage;
    double _contact_us_outage_email;
    NSString *_contact_us_problem_description;
    double _search_faq_results_best_id;
    double _contact_us_menu_faq_t;
    double _contact_us_screenshot_c;
    double _contact_us_t;
    double _search_faq_results_best_read_t;
    double _search_faq_results_generated_c;
    double _search_faq_results_read_c;
    double _search_faq_results_read_t;
}

@property(nonatomic) double search_faq_results_read_t; // @synthesize search_faq_results_read_t=_search_faq_results_read_t;
@property(nonatomic) double search_faq_results_read_c; // @synthesize search_faq_results_read_c=_search_faq_results_read_c;
@property(nonatomic) double search_faq_results_generated_c; // @synthesize search_faq_results_generated_c=_search_faq_results_generated_c;
@property(nonatomic) double search_faq_results_best_read_t; // @synthesize search_faq_results_best_read_t=_search_faq_results_best_read_t;
@property(nonatomic) double contact_us_t; // @synthesize contact_us_t=_contact_us_t;
@property(nonatomic) double contact_us_screenshot_c; // @synthesize contact_us_screenshot_c=_contact_us_screenshot_c;
@property(nonatomic) double contact_us_menu_faq_t; // @synthesize contact_us_menu_faq_t=_contact_us_menu_faq_t;
@property(nonatomic) double search_faq_results_best_id; // @synthesize search_faq_results_best_id=_search_faq_results_best_id;
@property(retain, nonatomic) NSString *contact_us_problem_description; // @synthesize contact_us_problem_description=_contact_us_problem_description;
@property(nonatomic) double contact_us_outage_email; // @synthesize contact_us_outage_email=_contact_us_outage_email;
@property(nonatomic) double contact_us_outage; // @synthesize contact_us_outage=_contact_us_outage;
@property(nonatomic) double contact_us_logs; // @synthesize contact_us_logs=_contact_us_logs;
@property(nonatomic) double contact_us_faq; // @synthesize contact_us_faq=_contact_us_faq;
@property(nonatomic) double contact_us_exit_state; // @synthesize contact_us_exit_state=_contact_us_exit_state;
@property(nonatomic) double contact_us_automatic_email; // @synthesize contact_us_automatic_email=_contact_us_automatic_email;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

