//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventLogin : WAFieldStatsEvent
{
    double _login_result;
    double _retry_count;
    double _login_t;
}

@property(nonatomic) double login_t; // @synthesize login_t=_login_t;
@property(nonatomic) double retry_count; // @synthesize retry_count=_retry_count;
@property(nonatomic) double login_result; // @synthesize login_result=_login_result;
- (void)submit;
- (id)init;

@end

