//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventICloudAutoBackupError : WAFieldStatsEvent
{
    double _icloud_backup_error;
    double _icloud_backup_interval;
}

@property(nonatomic) double icloud_backup_interval; // @synthesize icloud_backup_interval=_icloud_backup_interval;
@property(nonatomic) double icloud_backup_error; // @synthesize icloud_backup_error=_icloud_backup_error;
- (void)submit;
- (id)init;

@end

