//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class NSArray, NSString, WAContactInfo;

@interface WAForwardActivity : UIActivity
{
    NSArray *_items;
    NSString *_customActivityTitle;
    WAContactInfo *_selectedContactInfo;
    long long _maximumItemCount;
}

+ (id)forwardActivityForMessages:(id)arg1;
+ (id)activityTitleForForwardingMessages:(id)arg1;
+ (long long)activityCategory;
@property(nonatomic) long long maximumItemCount; // @synthesize maximumItemCount=_maximumItemCount;
@property(readonly, nonatomic) WAContactInfo *selectedContactInfo; // @synthesize selectedContactInfo=_selectedContactInfo;
- (void).cxx_destruct;
- (void)performActivity;
- (id)activityViewController;
- (void)prepareWithActivityItems:(id)arg1;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityType;
- (void)setActivityTitle:(id)arg1;
- (id)activityTitle;
- (id)activitySettingsImage;
- (id)activityImage;

@end

