//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MKMapView, NSMutableDictionary, NSString, NSTimer, UIBarButtonItem, UIToolbar, WAChatSession, WAMapTypeSegmentedControl;

@interface WAFriendsLocationViewController : UIViewController
{
    WAMapTypeSegmentedControl *_segmentedControl;
    UIBarButtonItem *_barButtonSearch;
    UIBarButtonItem *_segmentedControlBarItem;
    NSString *_groupJID;
    WAChatSession *_chatSession;
    NSMutableDictionary *_participantsLocations;
    _Bool _autoScale;
    _Bool _sharingIsActive;
    NSTimer *_annotationsUpdateTimer;
    MKMapView *_mapViewMain;
    UIToolbar *_toolbar;
}

@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) MKMapView *mapViewMain; // @synthesize mapViewMain=_mapViewMain;
- (void).cxx_destruct;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (id)chatSession;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)xmppConnectionLocationSharingChangedNotification:(id)arg1;
- (void)xmppConnectionLocationNotification:(id)arg1;
- (void)requestLocationsWithParticipants:(_Bool)arg1;
- (void)resubscribeForLocations;
- (void)onAnnotationsUpdateTimer;
- (void)setLocation:(id)arg1 forJid:(id)arg2;
- (void)autosetMapRegion;
- (void)nextFriend;
- (void)mapTypeChanged:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 groupJID:(id)arg2;

@end

