//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UITableView, _WAGroupSubjectTableViewCell;

@interface WAGroupInfoHeaderView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _editingAllowed;
    _Bool _activityIndicatorVisible;
    UIImage *_groupPictureOverride;
    UIView *_viewGroupPicture;
    UIButton *_buttonAddPicture;
    UIButton *_buttonEditPicture;
    UIActivityIndicatorView *_aiGroupIcon;
    UITableView *_tableViewSubject;
    _WAGroupSubjectTableViewCell *_cellGroupSubject;
    UIView *_backgroundView;
    UIView *_topSeparatorView;
    UIView *_bottomSeparatorView;
    _Bool _subjectEditingAllowed;
    id <WAGroupInfoHeaderViewDelegate> _delegate;
    UIImageView *_imageViewGroupPicture;
    double _bottomSeparatorInset;
}

@property(nonatomic) _Bool subjectEditingAllowed; // @synthesize subjectEditingAllowed=_subjectEditingAllowed;
@property(nonatomic) double bottomSeparatorInset; // @synthesize bottomSeparatorInset=_bottomSeparatorInset;
@property(readonly, nonatomic) UIImageView *imageViewGroupPicture; // @synthesize imageViewGroupPicture=_imageViewGroupPicture;
@property(nonatomic) __weak id <WAGroupInfoHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)hideActivityIndicator;
- (void)showActivityIndicatorWithGroupPictureOverride:(id)arg1;
- (void)updateWithWAChatSession:(id)arg1;
- (void)updateSubjectCellSelectionState;
- (void)editGroupPictureAction:(id)arg1;
- (void)editSubjectAction;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

