//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageCell.h"

@interface WAGroupEventCell : WAMessageCell
{
}

+ (double)rowHeightForCellData:(id)arg1 maxWidth:(double)arg2;
+ (id)cellReuseIdentifier;
- (id)accessibilityValueText;
- (id)accessibilityLabel;
- (void)layoutSubviews;
- (_Bool)selectable;
- (void)configureCellUpdatingAllContents:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

