//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizerDelegate.h"

@class WAImageToImagePanPopGestureRecognizer;

@protocol WAImageToImagePanPopGestureRecognizerDelegate <UIGestureRecognizerDelegate>
- (void)gestureRecognizerWillFinishManagingInteractivePopTransition:(WAImageToImagePanPopGestureRecognizer *)arg1;
- (void)gestureRecognizerDidBeginManagingInteractivePopTransition:(WAImageToImagePanPopGestureRecognizer *)arg1;
- (void)gestureRecognizerWillBeginManagingInteractivePopTransition:(WAImageToImagePanPopGestureRecognizer *)arg1;
@end

