//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageHelper.h"

@interface WAImageMessageHelper : WAMessageHelper
{
}

+ (double)maximumChatBubbleTransformedImageWidth;
+ (double)maximumChatBubbleImageWidth;
+ (id)stringRepresentationForVoiceOverForMessage:(id)arg1;
+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForMessage:(id)arg1;
+ (double)blurredImageMaximumWidth;
- (id)activitySubjectForActivityType:(id)arg1;
- (id)activityItemForActivityType:(id)arg1;
- (id)activityPlaceholderItem;
- (struct CGSize)chatThumbnailSize;
- (id)internalGenerateImageRepresentationFromSourceMediaAtPath:(id)arg1;
- (void)messageDidStoreIncomingMedia;
- (void)sanitizeIncomingMediaData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)storeOutgoingMedia:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalGenerateMediaBrowserThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

