//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WAImageAttachmentViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIScrollView;

@interface WAImageAttachmentContainerView : UIView <WAImageAttachmentViewDelegate>
{
    UIScrollView *_scrollView;
    NSMutableArray *_attachments;
    _Bool _removeButtonsHidden;
    id <WAImageAttachmentContainerViewDelegate> _delegate;
}

@property(nonatomic) _Bool removeButtonsHidden; // @synthesize removeButtonsHidden=_removeButtonsHidden;
@property(nonatomic) __weak id <WAImageAttachmentContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)imageAttachmentViewDidRequestAddImage:(id)arg1;
- (void)imageAttachmentViewDidRequestRemoveImage:(id)arg1;
- (void)attachImage:(id)arg1;
- (void)addAttachment:(id)arg1;
@property(readonly, nonatomic) NSArray *attachedImages;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

