//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABubbleView.h"

@class UIImage;

@interface WAInstantVoiceBubbleView : WABubbleView
{
    UIImage *_thumbnailImage;
}

+ (struct CGSize)sizeForName:(id)arg1 incoming:(_Bool)arg2 forWidth:(double)arg3;
+ (double)heightForName:(id)arg1;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithIncomingState:(_Bool)arg1 delegate:(id)arg2;

@end

