//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATextView.h"

@class WAMessageCell;

@interface WAInputTextView : WATextView
{
    double _previousContentHeight;
    _Bool _scrollIndicatorsShown;
    struct UIEdgeInsets _fixedInsets;
    WAMessageCell *_popupMenuTargetCell;
    WATextView *_textViewForMeasuring;
    _Bool _ignoreSetContentOffset;
    _Bool _alwaysBecomesFirstResponder;
    _Bool _caretHidden;
    _Bool _alwaysResignsFirstResponder;
    _Bool _neverResignsFirstResponder;
    _Bool _neverBecomesFirstResponder;
    double _minimumHeight;
}

@property(nonatomic) _Bool neverBecomesFirstResponder; // @synthesize neverBecomesFirstResponder=_neverBecomesFirstResponder;
@property(nonatomic) _Bool neverResignsFirstResponder; // @synthesize neverResignsFirstResponder=_neverResignsFirstResponder;
@property(nonatomic) _Bool alwaysResignsFirstResponder; // @synthesize alwaysResignsFirstResponder=_alwaysResignsFirstResponder;
@property(nonatomic, getter=isCaretHidden) _Bool caretHidden; // @synthesize caretHidden=_caretHidden;
@property(readonly, nonatomic) double minimumHeight; // @synthesize minimumHeight=_minimumHeight;
- (void).cxx_destruct;
- (void)dictationRecordingDidEnd;
- (void)dictationRecognitionFailed;
- (void)stopSpeakingMessage:(id)arg1;
- (void)speakMessage:(id)arg1;
- (void)replyMessageSender:(id)arg1;
- (void)addMessageSenderToContacts:(id)arg1;
- (void)forwardMessage:(id)arg1;
- (void)messageDetails:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)copyMessage:(id)arg1;
- (void)paste:(id)arg1;
- (void)menuControllerDidHideMenu:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)showPopupMenuForMessageCell:(id)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)scrollToBottomAnimated:(_Bool)arg1;
- (void)setText:(id)arg1;
- (void)setFont:(id)arg1;
- (void)scrollToVisibleRangeAfterDelay:(double)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateTextViewMetrics;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (double)bestHeightForAttributedText:(id)arg1 inSize:(struct CGSize)arg2 lastLineRect:(struct CGRect *)arg3;
- (double)bestHeightForText:(id)arg1 inSize:(struct CGSize)arg2 lastLineRect:(struct CGRect *)arg3;
- (id)topMostView;
- (double)bestHeightForAttributedText:(id)arg1 inSize:(struct CGSize)arg2;
- (double)bestHeightForText:(id)arg1 inSize:(struct CGSize)arg2;
- (double)bestHeightForAttributedText:(id)arg1;
- (double)bestHeightForText:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)bestHeightForCurrentText;
- (void)logMetrics;
- (void)setUserScrollingEnabled:(_Bool)arg1;
- (id)caretView;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canResignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)resignFirstResponder;
- (void)forceBecomeFirstResponder;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) __weak id <WAInputTextViewDelegate> delegate; // @dynamic delegate;

@end

