//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageCell.h"

#import "WADownloadProgressViewDelegate.h"
#import "WAMediaDataPresentationControllerDelegate.h"
#import "WAMessageTextViewDelegate.h"
#import "WAScrollTracking.h"

@class NSString, UIImageView, UILabel, UIView, WAAutoCropImageView, WADownloadProgressView, WAMessageFooterView, WAMessageTextView;

@interface WALargeMediaMessageCell : WAMessageCell <WADownloadProgressViewDelegate, WAMessageTextViewDelegate, WAScrollTracking, WAMediaDataPresentationControllerDelegate>
{
    UIImageView *_bubbleImageView;
    UIImageView *_roundedCornersImageView;
    UIView *_blackView;
    UIView *_whiteView;
    double _parallaxScaleFactor;
    WAMessageFooterView *_footerView;
    UIImageView *_broadcastImageView;
    UIImageView *_lowerRightShadowView;
    WADownloadProgressView *_progressView;
    _Bool _cellDataLoaded;
    WAMessageTextView *_messageTextView;
    UILabel *_fromNameLabel;
    UILabel *_pushNameLabel;
    _Bool _showFileSize;
    int _selectionState;
}

+ (id)cellReuseIdentifier;
+ (double)rowHeightForCellData:(id)arg1 maxWidth:(double)arg2;
+ (struct UIEdgeInsets)contentInsetsForCellData:(id)arg1;
+ (double)maximumImageWidth;
+ (void)initialize;
@property(readonly, nonatomic) int selectionState; // @synthesize selectionState=_selectionState;
@property(nonatomic) _Bool showFileSize; // @synthesize showFileSize=_showFileSize;
@property(readonly, nonatomic) WADownloadProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (void)configureForAccessibility;
- (id)accessibilityHintText;
- (id)voiceOverStringForMediaUploadOrDownloadStatus;
- (void)didHidePopupMenu;
- (void)didShowPopupMenu;
- (id)referenceViewForPopupMenu;
- (struct CGRect)targetRectForPopupMenu;
- (void)setShowsProgressBar:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setProgress:(float)arg1;
- (void)setProgressViewHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setProgressViewHidden:(_Bool)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)setContentsHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isContentsHighlighted) _Bool contentsHighlighted;
- (void)setDimmed:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)isDimmed;
- (void)setDimmed:(_Bool)arg1;
- (_Bool)isAnimating;
- (void)messageTextView:(id)arg1 willShowMoreOptionsForTextBlock:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)messageTextView:(id)arg1 didSelectTextBlock:(id)arg2;
- (void)downloadProgressViewDidCancel:(id)arg1;
- (void)setDidScrollWithUserInteraction:(_Bool)arg1;
- (void)didMoveToWindow;
- (void)setFrame:(struct CGRect)arg1;
- (void)handleLongPressOnText:(id)arg1;
- (void)handleDoubleTapOnText:(id)arg1;
- (void)mediaDataPresentationController:(id)arg1 didLongPressMediaAtIndex:(unsigned long long)arg2;
- (void)mediaDataPresentationController:(id)arg1 didTapMediaAtIndex:(unsigned long long)arg2;
- (void)mediaDataPresentationControllerDidLayoutView:(id)arg1;
- (void)prepareForReuse;
- (void)updateBlurredImages;
@property(readonly, nonatomic) WAAutoCropImageView *currentImageView;
@property(readonly, nonatomic) UIView *mediaContentView;
- (void)configureCellUpdatingAllContents:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setCellData:(id)arg1 delegate:(id)arg2;
- (void)updatePresentationFromPresentationControllerWithAnimation:(_Bool)arg1;
- (void)mediaDataPresentationControllerContentsDidFinishLoadingMedia:(id)arg1;
- (void)mediaDataPresentationController:(id)arg1 contentsDidChangeWithAnimation:(_Bool)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

