//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WARecipientsViewControllerDelegate.h"

@class NSFetchedResultsController, NSString, UITableView, UIView, WAChatSession;

@interface WAListsViewController : WAViewController <NSFetchedResultsControllerDelegate, WARecipientsViewControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    NSFetchedResultsController *_fetchedResultsController;
    UIView *_emptyListView;
    UITableView *_tableView;
    _Bool _chatStorageAvailable;
    WAChatSession *_activeList;
}

- (void).cxx_destruct;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)chatStorageWillUnloadDatabase:(id)arg1;
- (void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
- (void)recipientsControllerDidCancel:(id)arg1;
- (void)createNewList:(id)arg1;
- (void)deleteExistingList:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerWillChangeContent:(id)arg1;
@property(readonly, nonatomic) unsigned long long fetchedResultsCount;
- (void)setUpFetchRequest;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)navigateToList:(id)arg1 animated:(_Bool)arg2;
- (void)updateInterfaceWithAnimation:(_Bool)arg1;
- (void)setUpEmptyListView;
- (void)setBackButtonHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)resetAllSeparatorInsets;
- (void)wa_fontSizeDidChange;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

