//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageHelper.h"

@interface WALocationMessageHelper : WAMessageHelper
{
}

+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForMessage:(id)arg1;
- (void)internalGenerateXMPPThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (struct CGSize)chatThumbnailSize;
- (id)chatThumbnailReturningPermanentState:(out _Bool *)arg1;

@end

