//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABubbleView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UIView, WAGradientView;

@interface WALocationBubbleView : WABubbleView <UIGestureRecognizerDelegate>
{
    UIActivityIndicatorView *_activityIndicator;
    UIView *_containerView;
    UIImageView *_thumbnailImageView;
    UIView *_thumbnailDimmerView;
    WAGradientView *_gradientView;
    UILabel *_labelPlaceName;
    UILabel *_labelPlaceAddress;
    UIImageView *_imageViewArrow;
    _Bool _mapOnly;
    struct CGSize _imageSize;
}

+ (struct CGSize)sizeForPlaceName:(id)arg1 address:(id)arg2 maxWidth:(double)arg3 timestampString:(id)arg4 messageStatus:(unsigned long long)arg5 fromName:(id)arg6 pushName:(id)arg7 imageSize:(struct CGSize)arg8 showListIcon:(_Bool)arg9 isIncoming:(_Bool)arg10;
+ (id)placeAddressFont;
+ (id)placeNameFont;
+ (double)heightForName:(id)arg1 placeName:(id)arg2 placeAddress:(id)arg3;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)setThumbnailImage:(id)arg1;
- (void)setPlaceAddress:(id)arg1;
- (void)setPlaceName:(id)arg1;
- (void)setDimmed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isAnimating) _Bool animating;
- (id)initWithIncomingState:(_Bool)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

