//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "ABPersonViewControllerDelegate.h"

@class CLLocation, MKPlacemark, NSString, UIView, WAContactInfoNameUnit, WAContactInfoPhotoUnit, WAContactInfoTableHeaderView;

@interface WALocationInfoViewController : WATableViewController <ABPersonViewControllerDelegate>
{
    NSString *_formattedAddress;
    WAContactInfoTableHeaderView *_tableHeader;
    WAContactInfoNameUnit *_contactNameUnit;
    WAContactInfoPhotoUnit *_contactPhotoUnit;
    UIView *_actionsSectionHeaderView;
    int _contactID;
    MKPlacemark *_placemark;
    NSString *_contactName;
    CLLocation *_currentLocation;
}

+ (id)controller;
@property(retain, nonatomic) CLLocation *currentLocation; // @synthesize currentLocation=_currentLocation;
@property(nonatomic) int contactID; // @synthesize contactID=_contactID;
@property(retain, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;
@property(retain, nonatomic) MKPlacemark *placemark; // @synthesize placemark=_placemark;
- (void).cxx_destruct;
- (_Bool)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)actionsSectionHeaderView;
- (void)reloadTableHeader;
- (void)directionsToHere;
- (void)addToContacts;
- (void)wa_fontSizeDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

