//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMediaDataPresentationController.h"

@class WAAutoCropImageView;

@interface WAMediaDataParallaxPresentationController : WAMediaDataPresentationController
{
    WAAutoCropImageView *_currentImageView;
    WAAutoCropImageView *_transientImageView;
    double _parallaxScaleFactor;
    double _maximumParallaxOffset;
}

- (void).cxx_destruct;
- (void)didScrollInWindowWithUserInteraction:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)transitionFromIndex:(unsigned long long)arg1 toCurrentIndexWithAnimation:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)didUpdateImageAtIndex:(unsigned long long)arg1 completed:(_Bool)arg2;
- (id)currentImageView;
- (id)initWithChatCellData:(id)arg1;

@end

