//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAMediaPlayerDelegate.h"
#import "WAMediaPlayerTransportControlViewDelegate.h"

@class NSString, UIImageView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView, WAMediaPlayer, WAMediaPlayerTransportControlView, WAMessage;

@interface WAMediaScrollView : UIScrollView <WAMediaPlayerTransportControlViewDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, WAMediaPlayerDelegate>
{
    UIImageView *_imageView;
    double _fillToScreenScale;
    UIImageView *_audioOnlyBackgroundImageView;
    UIImageView *_audioOnlyLogoImageView;
    WAMessage *_currentMediaMessage;
    NSString *_errorMessageToShowOnNextPlayAttempt;
    WAMediaPlayerTransportControlView *_playerTransportBar;
    UILongPressGestureRecognizer *_longPressGesture;
    UITapGestureRecognizer *_doubleTapGesture;
    _Bool _needsScrollViewZoomAdjustment;
    _Bool _mediaControlsHidden;
    _Bool _suppressLayout;
    id <WAMediaScrollViewDelegate> _mediaDelegate;
    unsigned long long _index;
    double _topLayoutEdge;
    double _offset;
    WAMediaPlayer *_mediaPlayer;
    double _initialZoomScale;
}

@property(nonatomic) _Bool suppressLayout; // @synthesize suppressLayout=_suppressLayout;
@property(readonly, nonatomic) double initialZoomScale; // @synthesize initialZoomScale=_initialZoomScale;
@property(readonly, nonatomic) WAMediaPlayer *mediaPlayer; // @synthesize mediaPlayer=_mediaPlayer;
@property(nonatomic) _Bool mediaControlsHidden; // @synthesize mediaControlsHidden=_mediaControlsHidden;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(nonatomic) double topLayoutEdge; // @synthesize topLayoutEdge=_topLayoutEdge;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) __weak id <WAMediaScrollViewDelegate> mediaDelegate; // @synthesize mediaDelegate=_mediaDelegate;
- (void).cxx_destruct;
- (void)mediaPlayerTransportControlViewDidChangeCurrentTime:(id)arg1;
- (void)mediaPlayerTransportControlViewDidEndScrubbing:(id)arg1;
- (void)mediaPlayerTransportControlViewDidBeginScrubbing:(id)arg1;
- (void)mediaPlayerDidEndScrubbing:(id)arg1;
- (void)mediaPlayerDidBeginScrubbing:(id)arg1;
- (void)mediaPlayerDidPlayToEndTime:(id)arg1;
- (void)mediaPlayerDidFinishLoading:(id)arg1;
- (void)mediaPlayerDidChangeCurrentTime:(id)arg1;
- (void)mediaPlayerStatusDidChange:(id)arg1;
- (void)handlePlaybackError;
- (void)displayMediaInMessage:(id)arg1;
- (id)accessibilityLabelWithMediaType:(struct __CFString *)arg1 size:(struct CGSize)arg2 date:(id)arg3;
@property(readonly, nonatomic, getter=isPlayable) _Bool playable;
- (void)mediaPlayerDidRequestPlaybackStart:(id)arg1;
- (void)pause;
- (void)playInitiatedByAutoPlay:(_Bool)arg1;
- (void)displayQTLogo;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) _Bool isLongPressing;
- (void)handleLongPress:(id)arg1;
- (void)handleDoubleTap:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)showPopupMenuAtPoint:(struct CGPoint)arg1;
- (void)copy:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)configureZooming;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)relayoutAlongsideLayerAnimation;
- (void)toggleZoomInOutAtPoint:(struct CGPoint)arg1;
- (void)setMediaControlsHidden:(_Bool)arg1 animationDuration:(double)arg2;
- (void)animateOutImageView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateDeletionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIView *contentView;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

