//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "UIActivityItemSource.h"
#import "WAMediaUploadable.h"

@class NSData, NSDate, NSDictionary, NSNumber, NSObject<OS_dispatch_group>, NSSet, NSString, UIImage, WAChatSession, WAGroupMember, WAMediaItem, WAMessageHelper, WAMessageInfo;

@interface WAMessage : NSManagedObject <UIActivityItemSource, WAMediaUploadable>
{
    _Bool _observingSendState;
    NSObject<OS_dispatch_group> *_sendDispatchGroup;
    NSObject<OS_dispatch_group> *_locationInfoDispatchGroup;
    _Bool _messageSendInProgress;
    NSString *_mediaThumbnailCacheKey;
    NSObject<OS_dispatch_group> *_thumbnailLoadingDispatchGroup;
    long long _loadRequestsInProgress;
    UIImage *_loadedThumbnail;
    _Bool _scheduledForRemovalFromSearchIndex;
    WAMessageHelper *_helper;
    _Bool _offlineStorage;
    _Bool _sending;
    _Bool _active;
    _Bool _needsLocalNotification;
    _Bool _sentFromWebClient;
    int _retrySendCount;
    long long _multiSendMediaIndex;
    long long _multiSendMediaCount;
    WAMessage *_precedingMessage;
    NSString *_participantJID;
    NSData *_xmppThumbnailData;
}

+ (id)chatThumbnailCache;
+ (id)mediaBrowserThumbnailForUnknownMedia;
+ (id)mediaThumbnailCache;
+ (id)mediaDirectoryForFilename:(id)arg1 JID:(id)arg2;
+ (id)relativeLibraryPathFromAbsolutePath:(id)arg1;
+ (void)createNewOutgoingMessageWithPlace:(id)arg1 inChatSession:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)createNewOutgoingMessageWithVideoURL:(id)arg1 caption:(id)arg2 collectionID:(id)arg3 index:(long long)arg4 count:(long long)arg5 inChatSession:(id)arg6 completion:(CDUnknownBlockType)arg7;
+ (void)createNewOutgoingMessageWithAudioTrack:(id)arg1 inChatSession:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)createNewOutgoingMessageWithImage:(id)arg1 caption:(id)arg2 collectionID:(id)arg3 index:(long long)arg4 count:(long long)arg5 inChatSession:(id)arg6 completion:(CDUnknownBlockType)arg7;
+ (void)createNewOutgoingMessageWithMedia:(id)arg1 caption:(id)arg2 collectionID:(id)arg3 inChatSession:(id)arg4 imageRepresentation:(id)arg5 messageType:(unsigned long long)arg6 mediaOrigin:(unsigned long long)arg7 completion:(CDUnknownBlockType)arg8;
+ (_Bool)areAllMessages:(id)arg1 ofType:(unsigned long long)arg2;
+ (id)URIRepresentationFromDownloadIdentifier:(id)arg1;
+ (unsigned long long)orphanedMessagesCount;
+ (id)mediaSectionIDForMessage:(id)arg1 usingDateFormatter:(id)arg2;
+ (id)dateFormatterForMediaSectionID;
@property(nonatomic, getter=isSentFromWebClient) _Bool sentFromWebClient; // @synthesize sentFromWebClient=_sentFromWebClient;
@property(nonatomic) _Bool needsLocalNotification; // @synthesize needsLocalNotification=_needsLocalNotification;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(retain, nonatomic) NSData *xmppThumbnailData; // @synthesize xmppThumbnailData=_xmppThumbnailData;
@property(copy, nonatomic) NSString *participantJID; // @synthesize participantJID=_participantJID;
@property(nonatomic, getter=isSending) _Bool sending; // @synthesize sending=_sending;
@property(nonatomic) int retrySendCount; // @synthesize retrySendCount=_retrySendCount;
@property(retain, nonatomic) WAMessage *precedingMessage; // @synthesize precedingMessage=_precedingMessage;
@property(nonatomic) long long multiSendMediaCount; // @synthesize multiSendMediaCount=_multiSendMediaCount;
@property(nonatomic) long long multiSendMediaIndex; // @synthesize multiSendMediaIndex=_multiSendMediaIndex;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *mediaCollectionName;
- (void)replaceMediaWithMediaAtPath:(id)arg1;
@property(readonly, nonatomic) long long httpRetryCount;
@property(readonly, nonatomic) _Bool isPTT;
@property(readonly, nonatomic) unsigned long long mediaType;
@property(readonly, copy, nonatomic) NSString *fileHash;
@property(readonly, nonatomic) id <NSObject><NSCopying> uniqueID;
@property(readonly, copy, nonatomic) NSString *textForSearchIndex;
@property(readonly, nonatomic) float searchQualityScore;
@property(readonly, nonatomic, getter=isSearchable) _Bool searchable;
- (id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2;
- (id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
@property(readonly, copy, nonatomic) NSString *stringRepresentationForVoiceOver;
@property(readonly, copy, nonatomic) NSString *stringRepresentationForChat;
@property(readonly, copy, nonatomic) NSString *stringRepresentation;
@property(retain) UIImage *imageRepresentation;
@property(readonly) UIImage *blurredImage;
@property(readonly) UIImage *xmppImage;
- (void)fetchRequiredDataForIncomingLocationWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchRequiredDataForWAPlace:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)repeatedlyFetchBetterThumbnailsWithBlock:(CDUnknownBlockType)arg1;
- (struct CGSize)chatThumbnailSize;
- (id)chatThumbnailReturningPermanentState:(out _Bool *)arg1;
- (id)cachedChatThumbnail;
- (void)generateMediaBrowserThumbnailWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchMediaBrowserThumbnailWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)cachedMediaBrowserThumbnail;
- (void)updateMediaLocalPathWithAbsolutePath:(id)arg1;
- (id)mediaPathForIncomingMediaWithFilename:(id)arg1;
- (id)uniqueMediaPathWithPathExtension:(id)arg1;
@property(readonly, copy, nonatomic) NSString *mediaPath;
@property(readonly, nonatomic) NSString *chatThumbnailPath;
@property(readonly, nonatomic) NSString *xmppThumbnailPath;
@property(readonly, nonatomic) NSString *mediaBrowserThumbnailPath;
- (void)sendServerErrorReceiptIfNeeded;
- (void)updateReceiptInfoFrom:(id)arg1 status:(unsigned long long)arg2 date:(id)arg3;
- (void)attachIncomingXMPPThumbnailData:(id)arg1;
- (void)attachIncomingMediaWithFilename:(id)arg1 data:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)attachMediaAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)incomingFilePathForFileType:(id)arg1;
- (void)populateChildMessage:(id)arg1;
- (id)addChildMessagesIfNeeded;
- (void)prepareThumbnails:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)performBlockAfterSendMessageAttempt:(CDUnknownBlockType)arg1;
- (void)markSendAsCompletedIfNecessary;
- (void)markSendAsStartedIfNecessary;
@property(readonly, nonatomic) _Bool canBeForwarded;
@property(readonly, nonatomic) _Bool needsResend;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (void)unsetFlag:(unsigned long long)arg1;
- (void)setFlag:(unsigned long long)arg1;
- (_Bool)hasFlag:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *downloadIdentifier;
@property(readonly, nonatomic, getter=isEligibleForUnreadMessages) _Bool eligibleForUnreadMessages;
@property(readonly, nonatomic, getter=isEligibleToResortChats) _Bool eligibleToResortChats;
@property(readonly, nonatomic, getter=isEligibleForNotification) _Bool eligibleForNotification;
@property(retain, nonatomic) NSNumber *messageStatus; // @dynamic messageStatus;
@property(nonatomic) _Bool offlineStorage; // @synthesize offlineStorage=_offlineStorage;
- (void)willSave;
- (void)freeCachedData;
- (_Bool)turnMediaItemIntoFaultIfPossible;
- (_Bool)turnIntoFaultIfPossible;
- (void)generateMediaThumbnailCacheKey;
@property(readonly, nonatomic) WAMessageHelper *helper;
- (id)fromName;
- (void)updateMediaSectionID;
@property(readonly, copy, nonatomic) NSDictionary *changedKeyPaths;
- (void)didTurnIntoFault;
- (void)awakeFromInsert;
- (void)awakeFromFetch;

// Remaining properties
@property(retain, nonatomic) WAChatSession *chatSession; // @dynamic chatSession;
@property(retain, nonatomic) NSSet *childMessages; // @dynamic childMessages;
@property(retain, nonatomic) NSNumber *childMessagesDeliveredCount; // @dynamic childMessagesDeliveredCount;
@property(retain, nonatomic) NSNumber *childMessagesPlayedCount; // @dynamic childMessagesPlayedCount;
@property(retain, nonatomic) NSNumber *childMessagesReadCount; // @dynamic childMessagesReadCount;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSNumber *docID; // @dynamic docID;
@property(retain, nonatomic) NSNumber *encRetryCount; // @dynamic encRetryCount;
@property(retain, nonatomic) NSNumber *filteredRecipientCount; // @dynamic filteredRecipientCount;
@property(retain, nonatomic) NSNumber *flags; // @dynamic flags;
@property(retain, nonatomic) NSString *fromJID; // @dynamic fromJID;
@property(retain, nonatomic) NSNumber *groupEventType; // @dynamic groupEventType;
@property(retain, nonatomic) WAGroupMember *groupMember; // @dynamic groupMember;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSNumber *isFromMe; // @dynamic isFromMe;
@property(retain, nonatomic) WAMediaItem *mediaItem; // @dynamic mediaItem;
@property(retain, nonatomic) NSString *mediaSectionID; // @dynamic mediaSectionID;
@property(retain, nonatomic) NSDate *messageDate; // @dynamic messageDate;
@property(retain, nonatomic) NSNumber *messageErrorStatus; // @dynamic messageErrorStatus;
@property(retain, nonatomic) WAMessageInfo *messageInfo; // @dynamic messageInfo;
@property(retain, nonatomic) NSNumber *messageType; // @dynamic messageType;
@property(retain, nonatomic) WAMessage *parentMessage; // @dynamic parentMessage;
@property(retain, nonatomic) NSString *pushName; // @dynamic pushName;
@property(retain, nonatomic) NSDate *sentDate; // @dynamic sentDate;
@property(retain, nonatomic) NSNumber *sort; // @dynamic sort;
@property(retain, nonatomic) NSString *stanzaID; // @dynamic stanzaID;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *text; // @dynamic text;
@property(retain, nonatomic) NSString *toJID; // @dynamic toJID;

@end

