//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"
#import "WABubbleViewDelegate.h"
#import "WAMediaProgressDelegate.h"

@class NSArray, NSString, UIButton, UIImage, UIImageView, UIPanGestureRecognizer, UIProgressView, UIView, WAChatCellData;

@interface WAMessageCell : UITableViewCell <WABubbleViewDelegate, WAMediaProgressDelegate, UIGestureRecognizerDelegate>
{
    WAChatCellData *_cellData;
    UIView *_bubbleView;
    UIImageView *_imageViewBubble;
    UIImageView *_imageViewCheckmark;
    UIButton *_buttonAlert;
    UIButton *_buttonView;
    UIButton *_buttonDownload;
    UIButton *_buttonForward;
    UIButton *_buttonCancel;
    UIProgressView *_progressView;
    UIImageView *_progressViewBox;
    UIImage *_checkMarkNormal;
    UIImage *_checkMarkChecked;
    struct _cellFlags {
        unsigned int showAlertButton:1;
        unsigned int showProgressBar:1;
        unsigned int showDownloadButton:1;
        unsigned int showViewButton:1;
        unsigned int showForwardButton:1;
        unsigned int showCancelButton:1;
        unsigned int cellSelected:1;
    } _flags;
    _Bool _permanentThumbnail;
    _Bool _singleTapDisabled;
    NSArray *_accessibleElements;
    UIPanGestureRecognizer *_swipeGestureRecognizer;
    long long _contentHorizontalAlignment;
    id <WAMessageCellDelegate> _delegate;
}

+ (struct UIEdgeInsets)contentInsetsForCellData:(id)arg1;
+ (struct UIEdgeInsets)baseContentInsetsForCellData:(id)arg1;
+ (struct UIEdgeInsets)bubbleInsetsForCellData:(id)arg1;
+ (struct UIEdgeInsets)bubbleMargins;
+ (_Bool)shouldShowHeaderForCellData:(id)arg1;
+ (double)maxBubbleWidthForCellWidth:(double)arg1;
+ (double)rowHeightForCellData:(id)arg1 maxWidth:(double)arg2;
+ (id)cellReuseIdentifier;
+ (Class)cellClassForCellData:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool singleTapDisabled; // @synthesize singleTapDisabled=_singleTapDisabled;
@property(nonatomic) __weak id <WAMessageCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long contentHorizontalAlignment; // @synthesize contentHorizontalAlignment=_contentHorizontalAlignment;
@property(readonly, nonatomic) UIView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(readonly, nonatomic) UIPanGestureRecognizer *swipeGestureRecognizer; // @synthesize swipeGestureRecognizer=_swipeGestureRecognizer;
@property(retain, nonatomic) NSArray *accessibleElements; // @synthesize accessibleElements=_accessibleElements;
@property(readonly, nonatomic) WAChatCellData *cellData; // @synthesize cellData=_cellData;
- (void).cxx_destruct;
- (void)setProgress:(float)arg1 forMessage:(id)arg2;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (void)configureForAccessibility;
- (id)accessibilityValueText;
- (id)accessibilityHintText;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)bubbleView:(id)arg1 willShowMoreOptionsForTextBlock:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)bubbleView:(id)arg1 didSelectTextBlock:(id)arg2;
- (void)stopSpeakingContentInBubbleView:(id)arg1;
- (void)startSpeakingContentInBubbleView:(id)arg1;
- (void)detailsForMessageInBubbleView:(id)arg1;
- (void)replyMessageSenderFromBubbleView:(id)arg1;
- (void)addMessageSenderInBubbleView:(id)arg1;
- (void)deleteMessageInBubbleView:(id)arg1;
- (void)forwardMessageInBubbleView:(id)arg1;
- (void)copyMessageInBubbleView:(id)arg1;
- (void)openURL:(id)arg1 fromBubbleView:(id)arg2;
- (void)handleDoubleTapActionInBubbleView:(id)arg1;
- (void)handleSingleTapActionInBubbleView:(id)arg1;
- (_Bool)canPerformDoubleTapActionInBubbleView:(id)arg1;
- (_Bool)canPerformSingleTapActionInBubbleView:(id)arg1;
- (_Bool)canDimBubbleView:(id)arg1;
- (_Bool)bubbleView:(id)arg1 canPerformAction:(SEL)arg2 withSender:(id)arg3;
- (void)setHighlightState:(_Bool)arg1 forBubbleView:(id)arg2 animated:(_Bool)arg3;
- (id)shortNameForBubbleView:(id)arg1;
- (void)layoutSubviews;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)resetAppearance;
- (void)setProgress:(float)arg1;
- (_Bool)cellSelected;
- (void)setCellSelected:(_Bool)arg1;
- (void)setShowsProgressBar:(_Bool)arg1;
- (void)setShowCancelButton:(_Bool)arg1;
- (void)setShowForwardButton:(_Bool)arg1;
- (void)setShowViewButton:(_Bool)arg1;
- (void)setShowDownloadButton:(_Bool)arg1;
- (void)setShowAlertButton:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setBubbleHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setDimmed:(_Bool)arg1;
- (_Bool)isAnimating;
- (void)stopSpeakingMessage:(id)arg1;
- (void)speakMessage:(id)arg1;
- (void)replyMessageSender:(id)arg1;
- (void)addMessageSenderToContacts:(id)arg1;
- (void)forwardMessage:(id)arg1;
- (void)messageDetails:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)copyMessage:(id)arg1;
- (void)performCopy;
- (_Bool)canPerformCopy;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)menuControllerDidHideMenu:(id)arg1;
- (void)didHidePopupMenu;
- (void)didShowPopupMenu;
- (void)showPopupMenu;
- (_Bool)canBecomeFirstResponder;
- (id)referenceViewForPopupMenu;
- (struct CGRect)targetRectForPopupMenu;
- (id)shortNameForPopupMenu;
- (void)setCellData:(id)arg1 delegate:(id)arg2;
- (_Bool)selectable;
- (void)refreshUI;
- (id)buttonCancel;
- (id)buttonForward;
- (id)buttonView;
- (id)buttonDownload;
- (id)buttonAlert;
- (void)cancelButtonTapped:(id)arg1;
- (void)forwardButtonTapped:(id)arg1;
- (void)viewButtonTapped:(id)arg1;
- (void)downloadButtonTapped:(id)arg1;
- (void)alertButtonTapped:(id)arg1;
- (void)configureCellUpdatingAllContents:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateDownloadButtonTitle;
- (void)updateViewButtonTitle;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleSwipeGesture:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

