//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class NSDate, NSHTTPURLResponse, NSMutableData, NSMutableDictionary, NSString, NSURLConnection, WAMessage, XMPPConnection;

@interface WAMediaDownloadOperation : NSOperation <NSURLConnectionDelegate>
{
    XMPPConnection *_connection;
    id <WAMediaDownloadOperationDelegate> _delegate;
    NSDate *_startDate;
    NSURLConnection *_urlConnection;
    unsigned int _expectedContentLength;
    NSHTTPURLResponse *_response;
    NSMutableDictionary *_avParams;
    NSMutableData *_receiveData;
    NSMutableData *_partialFileData;
    _Bool _partialDownload;
    NSString *_downloadHost;
    NSString *_originalHost;
    int _connectionAttempt;
    _Bool _isExecuting;
    _Bool _isFinished;
    _Bool _autodownload;
    _Bool _isLocalCopy;
    WAMessage *_message;
    NSString *_fileName;
}

@property(readonly, nonatomic) _Bool isLocalCopy; // @synthesize isLocalCopy=_isLocalCopy;
@property(readonly, nonatomic) _Bool autodownload; // @synthesize autodownload=_autodownload;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) WAMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)fetchDataFromLocalMediaFileAtLibraryPath:(id)arg1;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)tcpConnectionTimeout:(id)arg1;
- (void)performFinalDataCheck;
- (void)startUrlConnection;
- (id)partialUploadFilePath;
- (id)tryAgainError;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (void)reportFieldStatsWithResult:(int)arg1;
- (void)savePartialData;
- (void)cancel;
- (void)finish;
- (void)start;
- (void)dealloc;
- (id)initWithDownloadOperationDelegate:(id)arg1 connection:(id)arg2 message:(id)arg3 autodownload:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

