//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSConditionLock, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, UIImage, WAMessage;

@interface WAMessageHelper : NSObject
{
    int _activeOperationCount;
    NSObject<OS_dispatch_group> *_thumbnailLoadingGroup;
    NSObject<OS_dispatch_queue> *_localThumbnailLoadingQueue;
    NSConditionLock *_xmppLoadingLock;
    NSObject<OS_dispatch_queue> *_generateImageRepresentationQueue;
    _Bool _thumbnailLoadingInProgress;
    WAMessage *_message;
    UIImage *_imageRepresentation;
    UIImage *_loResImageRepresentation;
    UIImage *_xmppImage;
    UIImage *_blurredImage;
    double _cachedMediaDuration;
}

+ (id)messageTimestampForVoiceOverFromDate:(id)arg1;
+ (id)stringRepresentationForVoiceOverForMessage:(id)arg1;
+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForMessage:(id)arg1;
+ (id)senderNameForStringRepresentationForMessage:(id)arg1;
+ (id)cachedThumbnailPathFromMediaPath:(id)arg1;
+ (_Bool)needsBlurredImage;
+ (double)blurredImageMaximumWidth;
+ (id)staticMediaBrowserThumbnail;
+ (struct CGSize)mediaBrowserThumbnailSize;
+ (id)imageForVideoAtPath:(id)arg1;
+ (double)durationOfVideoAtPath:(id)arg1;
+ (id)jpegDataFromImage:(id)arg1 error:(out id *)arg2;
+ (_Bool)checkMediaSize:(id)arg1 error:(out id *)arg2;
+ (id)errorWithDescription:(id)arg1 failureReason:(id)arg2;
+ (void)initialize;
+ (Class)helperClassForMessage:(id)arg1;
+ (id)messageHelperForMessage:(id)arg1;
@property _Bool thumbnailLoadingInProgress; // @synthesize thumbnailLoadingInProgress=_thumbnailLoadingInProgress;
@property(nonatomic) double cachedMediaDuration; // @synthesize cachedMediaDuration=_cachedMediaDuration;
@property(retain) UIImage *blurredImage; // @synthesize blurredImage=_blurredImage;
@property(retain) UIImage *xmppImage; // @synthesize xmppImage=_xmppImage;
@property(retain, nonatomic) UIImage *loResImageRepresentation; // @synthesize loResImageRepresentation=_loResImageRepresentation;
@property(retain) UIImage *imageRepresentation; // @synthesize imageRepresentation=_imageRepresentation;
@property(nonatomic) __weak WAMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)activityDataTypeIdentifierForActivityType:(id)arg1;
- (id)activitySubjectForActivityType:(id)arg1;
- (id)activityItemForActivityType:(id)arg1;
- (id)activityPlaceholderItem;
- (void)internalRepeatedlyFetchBetterThumbnailsWithBlock:(CDUnknownBlockType)arg1;
- (void)repeatedlyFetchBetterThumbnailsWithBlock:(CDUnknownBlockType)arg1;
- (void)prepareForDisplayWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)internalGenerateImageRepresentationFromSourceMediaAtPath:(id)arg1;
- (id)generateImageRepresentationFromSourceMediaAtPath:(id)arg1;
- (struct CGSize)chatThumbnailSize;
- (id)chatThumbnailReturningPermanentState:(out _Bool *)arg1;
- (void)internalGenerateMediaBrowserThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateMediaBrowserThumbnailWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateChatThumbnailWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)internalGenerateXMPPThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateXMPPThumbnailWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)internalFetchImageRepresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchImageRepresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)messageDidStoreIncomingMedia;
- (void)storeIncomingMediaWithFilename:(id)arg1 data:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sanitizeIncomingMediaData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)storeOutgoingMedia:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)isProcessing;
- (void)freeCachedData;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

