//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSArray, NSFetchedResultsController, NSMutableArray, NSString;

@interface WAMediaManager : NSObject <NSFetchedResultsControllerDelegate>
{
    NSMutableArray *_chatSessions;
    _Bool _databaseAccessAvailable;
    _Bool _needsReset;
    _Bool _loadOnChatStorageDidLoadDatabase;
    NSFetchedResultsController *_resultsController;
    long long _cachedPhotoCount;
    long long _cachedVideoCount;
    long long _cachedTotalItemCount;
    long long _currentMonth;
    long long _currentYear;
    NSString *_title;
}

+ (void)initialize;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)titleForHeaderInSection:(long long)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfSections;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)chatStorageWillUnloadDatabase:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerWillChangeContent:(id)arg1;
- (void)deleteMessagesAtIndexPaths:(id)arg1;
- (id)indexPathOfMessage:(id)arg1;
- (id)messageAtIndexPath:(id)arg1;
- (void)loadIfNeeded;
@property(readonly, nonatomic) unsigned long long numberOfVideos;
@property(readonly, nonatomic) unsigned long long numberOfPhotos;
- (_Bool)isForSingleItem;
- (unsigned long long)countOfMessageType:(unsigned long long)arg1;
- (_Bool)isResultSetEmpty;
- (void)reset;
- (void)setNeedsReset;
@property(readonly, nonatomic) unsigned long long numberOfItems;
- (id)indexPathFromIndex:(unsigned long long)arg1;
- (unsigned long long)indexFromIndexPath:(id)arg1;
- (_Bool)isGroupChatMedia;
- (void)chatStorageDidReplaceChatSession:(id)arg1;
@property(retain, nonatomic) NSArray *chatSessions;
- (void)updateDateFormatters;
- (void)currentLocaleDidChange:(id)arg1;
- (void)handleSignificantTimeChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

