//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHPhotoLibraryChangeObserver.h"

@class NSArray, NSObject<OS_dispatch_group>, NSString;

@interface WAMediaPickerLibraryController : NSObject <PHPhotoLibraryChangeObserver>
{
    NSObject<OS_dispatch_group> *_loadingDispatchGroup;
    _Bool _assetsLibraryLoadingInProgress;
    NSArray *_albumControllers;
    _Bool _reloadLibraryAfterEnteringForeground;
    _Bool _containsAssets;
    unsigned long long _mediaType;
}

@property(readonly, nonatomic) unsigned long long mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, nonatomic) _Bool containsAssets; // @synthesize containsAssets=_containsAssets;
@property(readonly, nonatomic) NSArray *albumControllers; // @synthesize albumControllers=_albumControllers;
- (void).cxx_destruct;
- (id)albumControllerForAssetCollection:(id)arg1 fromAvailableAlbums:(id)arg2;
- (void)reloadAssetsLibraryWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)prepareWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)isLibraryReady;
- (void)deferredInvalidateAndReload;
- (void)invalidateAndReload;
- (void)assetsLibraryChanged:(id)arg1;
- (void)photoLibraryDidChange:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)dealloc;
- (id)initWithMediaType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

