//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVPlayer, AVPlayerItem, AVVideoComposition, NSError, NSObject<OS_dispatch_group>, UIImage, WACropAwareImageView, _WAMediaPlayerPlayButtonView, _WAPlayerView;

@interface WAMediaPlayer : UIView
{
    AVPlayer *_player;
    _WAPlayerView *_playerView;
    id _timeObserver;
    float _playerRateBeforeScrubbing;
    CDStruct_1b6d18a9 _desiredSeekTime;
    _WAMediaPlayerPlayButtonView *_playButtonView;
    struct CGRect _frameForPlayButtonSnapshot;
    _Bool _showPlayButtonOnReady;
    id _playbackActivity;
    _Bool _playButtonNormallyVisible;
    NSObject<OS_dispatch_group> *_seekDispatchGroup;
    _Bool _seekInProgress;
    _Bool _alwaysShowPlayButtonOnPause;
    _Bool _suppressPlayButton;
    _Bool _scrubbingInProgress;
    float _playbackRate;
    unsigned long long _status;
    id <WAMediaPlayerDelegate> _delegate;
    NSError *_error;
    WACropAwareImageView *_posterImageView;
    AVPlayerItem *_playerItem;
    CDStruct_1b6d18a9 _playbackStartTime;
}

@property(readonly, nonatomic) _Bool scrubbingInProgress; // @synthesize scrubbingInProgress=_scrubbingInProgress;
@property(nonatomic) _Bool suppressPlayButton; // @synthesize suppressPlayButton=_suppressPlayButton;
@property(nonatomic) _Bool alwaysShowPlayButtonOnPause; // @synthesize alwaysShowPlayButtonOnPause=_alwaysShowPlayButtonOnPause;
@property(nonatomic) CDStruct_1b6d18a9 playbackStartTime; // @synthesize playbackStartTime=_playbackStartTime;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(readonly, nonatomic) WACropAwareImageView *posterImageView; // @synthesize posterImageView=_posterImageView;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) _Bool seekInProgress; // @synthesize seekInProgress=_seekInProgress;
@property(nonatomic) float playbackRate; // @synthesize playbackRate=_playbackRate;
@property(nonatomic) __weak id <WAMediaPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)snapshotImage;
- (void)performBlockAfterSeeking:(CDUnknownBlockType)arg1;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1 tolerance:(CDStruct_1b6d18a9)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)internalSeekWithTolerance:(CDStruct_1b6d18a9)arg1;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1 tolerance:(CDStruct_1b6d18a9)arg2;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
- (void)endScrubbing;
- (void)beginScrubbing;
@property(readonly, nonatomic, getter=isReadyToPlay) _Bool readyToPlay;
@property(readonly, nonatomic, getter=isPlaying) _Bool playing;
@property(readonly, nonatomic) struct CGSize presentationSize;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 currentTime;
- (void)rewind;
- (void)playInitiatedByAutoPlay:(_Bool)arg1;
- (void)pause;
- (void)updatePlayButtonAlphaWithAnimation:(_Bool)arg1;
- (_Bool)isPlayButtonHidden;
- (void)applicationWillResignActive:(id)arg1;
- (void)playerItemDidPlayToEndTime:(id)arg1;
- (void)playerItemDidBecomeReadyToPlay;
- (void)playerDidChangeCurrentTime;
- (void)removeTimeObserverFromPlayer;
- (void)addTimeObserverToPlayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UIImage *posterImage;
- (void)playButtonTapped:(id)arg1;
- (void)setInitialPosterImage:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) AVVideoComposition *playerItemVideoComposition;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)setAccessibilityLabel:(id)arg1;
- (_Bool)isAccessibilityElement;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithContentURL:(id)arg1;

@end

