//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMediaPickerBaseViewController.h"

#import "WAImageToImageTransitioning.h"
#import "WAMediaPickerAlbumControllerDelegate.h"
#import "WAMediaPickerAlbumTableViewCellDelegate.h"

@class NSNumber, NSString, UIImageView, UILabel, UIView, WAMediaPickerAlbumController;

@interface WAMediaPickerAlbumViewController : WAMediaPickerBaseViewController <WAMediaPickerAlbumTableViewCellDelegate, WAMediaPickerAlbumControllerDelegate, WAImageToImageTransitioning>
{
    unsigned long long _assetsCountPerRow;
    UIView *_footerView;
    UILabel *_footerLabel;
    _Bool _albumLoadingInProgress;
    NSNumber *_assetIndexToRestore;
    struct CGPoint _contentOffsetAtStartOfRotation;
    UIImageView *_beforeRotationSnapshotImageView;
    UIImageView *_afterRotationSnapshotImageView;
    UIView *_whiteBackgroundView;
    _Bool _rotatingViewWithNoMedia;
    UILabel *_noMediaTitleLabel;
    UILabel *_noMediaBodyTextLabel;
    _Bool _needsScrollToSelectedPhoto;
    struct CGRect _previousPreheatRect;
    WAMediaPickerAlbumController *_albumController;
}

+ (id)controller;
@property(retain, nonatomic) WAMediaPickerAlbumController *albumController; // @synthesize albumController=_albumController;
- (void).cxx_destruct;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)adjustContentOffsetOfTableViewToNearestValidMultipleOfRowHeight;
- (id)tableViewSnapshot;
- (void)computeDifferenceBetweenRect:(struct CGRect)arg1 andRect:(struct CGRect)arg2 removedHandler:(CDUnknownBlockType)arg3 addedHandler:(CDUnknownBlockType)arg4;
- (struct _NSRange)rangeOfAssetsInRect:(struct CGRect)arg1;
- (void)updateThumbnailCache;
- (void)scrollViewDidScroll:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)mediaPickerAlbumTableViewCell:(id)arg1 didReceiveTapAtIndex:(long long)arg2;
- (void)reconfigureAllVisibleCells;
- (void)updateFooter;
- (id)formattedTextForPhotoAndVideoCount:(long long)arg1;
- (id)formattedTextForVideoCount:(long long)arg1;
- (id)formattedTextForPhotoCount:(long long)arg1;
- (long long)assetsCountPerRow;
- (void)mediaPickerAlbumController:(id)arg1 didFinishLoadingAlbumWithOutcome:(_Bool)arg2;
- (void)mediaPickerAlbumControllerWillBeginLoadingAlbum:(id)arg1;
- (void)scrollToBottom;
- (struct CGPoint)maximumContentOffset;
- (void)scrollToAssetAtIndex:(long long)arg1;
- (long long)indexOfAssetAtCenterOfView;
- (_Bool)scrollEnabled;
- (void)reloadTable;
- (void)relayoutNoMediaViews;
- (void)relayoutViews;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

