//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, TextBlock, UIPanGestureRecognizer, WAMessageCell;

@protocol WAMessageCellDelegate <NSObject>
- (void)messageCell:(WAMessageCell *)arg1 swipeGestureDidChange:(UIPanGestureRecognizer *)arg2;
- (void)messageCell:(WAMessageCell *)arg1 willShowMoreOptionsForTextBlock:(TextBlock *)arg2 completionHandler:(void (^)(void))arg3;
- (void)messageCell:(WAMessageCell *)arg1 didSelectTextBlock:(TextBlock *)arg2;
- (void)replyMessageSenderFromCell:(WAMessageCell *)arg1;
- (void)addMessageSenderInCell:(WAMessageCell *)arg1;
- (void)deleteMessagesInCell:(WAMessageCell *)arg1;
- (void)forwardMessagesInCell:(WAMessageCell *)arg1;
- (void)openURL:(NSURL *)arg1 fromCell:(WAMessageCell *)arg2;
- (void)handleDoubleTapInCell:(WAMessageCell *)arg1;
- (void)handleSingleTapInCell:(WAMessageCell *)arg1;
- (void)invertSelectionForCell:(WAMessageCell *)arg1;
- (void)cancelButtonTappedInCell:(WAMessageCell *)arg1;
- (void)viewButtonTappedInCell:(WAMessageCell *)arg1;
- (void)downloadButtonTappedInCell:(WAMessageCell *)arg1;
- (void)alertButtonTappedInCell:(WAMessageCell *)arg1;

@optional
- (void)messageVCardPersonFromCell:(WAMessageCell *)arg1;
- (void)saveVCardPersonFromCell:(WAMessageCell *)arg1;
- (void)detailsForMessageInCell:(WAMessageCell *)arg1;
@end

