//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray;

@interface WAMediaPickerAlbumTableViewCell : UITableViewCell
{
    NSMutableArray *_assetViews;
    _Bool _allowsMultipleSelection;
    long long _maximumAssetsPerRow;
    id <WAMediaPickerAlbumTableViewCellDelegate> _delegate;
}

+ (id)cellWithReuseIdentifier:(id)arg1;
+ (long long)assetsCountForRowOfWidth:(double)arg1;
+ (struct CGSize)thumbnailSize;
+ (double)cellMargin;
+ (double)rowHeight;
+ (void)initialize;
@property(readonly, nonatomic) NSMutableArray *assetViews; // @synthesize assetViews=_assetViews;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) __weak id <WAMediaPickerAlbumTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long maximumAssetsPerRow; // @synthesize maximumAssetsPerRow=_maximumAssetsPerRow;
- (void).cxx_destruct;
- (void)assetViewTapped:(id)arg1;
- (void)configureWithMediaPickerAssets:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

