//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSError, NSString;

@interface WAMediaUploadOperationBase : NSOperation
{
    _Bool _reuploading;
    id <WAMediaUploadable> _uploadable;
    id <WAMediaUploadOperationDelegate> _delegate;
    NSString *_mediaURL;
    NSString *_serverHash;
    NSError *_error;
}

@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic, getter=isReuploading) _Bool reuploading; // @synthesize reuploading=_reuploading;
@property(retain, nonatomic) NSString *serverHash; // @synthesize serverHash=_serverHash;
@property(retain, nonatomic) NSString *mediaURL; // @synthesize mediaURL=_mediaURL;
@property(retain, nonatomic) id <WAMediaUploadOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <WAMediaUploadable> uploadable; // @synthesize uploadable=_uploadable;
- (void).cxx_destruct;
- (void)didFailWithError:(id)arg1;
- (void)didFinish;
- (id)initWithUploadOperationDelegate:(id)arg1 uploadable:(id)arg2;

@end

