//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAImageToImagePanPopGestureRecognizerDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WAMediaGalleryControllerDelegate.h"
#import "WAMediaScrollViewDelegate.h"
#import "WANavigationControllerPopFromAnimating.h"

@class NSMutableSet, NSString, NSTimer, UIActivityIndicatorView, UIBarButtonItem, UILabel, UINavigationController, UIScrollView, UIToolbar, UIView, WAImageToImagePanPopGestureRecognizer, WAMediaCaptionView, WAMediaManager, WAMessage;

@interface WAMediaViewController : WAViewController <UIScrollViewDelegate, UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, WAMediaScrollViewDelegate, WAMediaGalleryControllerDelegate, WAImageToImageTransitioning, WAImageToImagePanPopGestureRecognizerDelegate, WANavigationControllerPopFromAnimating>
{
    NSMutableSet *_recycledPages;
    NSMutableSet *_visiblePages;
    _Bool _suppressRelayoutInScrollViewDidScroll;
    _Bool _tiling;
    UINavigationController *_lastNavigationController;
    NSTimer *_hideBarsTimer;
    _Bool _shouldAutoPlay;
    _Bool _shouldResumePlayback;
    _Bool _fullScreenMode;
    double _lastStatusBarHeight;
    UIBarButtonItem *_showAllButton;
    UIBarButtonItem *_actionButton;
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_playButton;
    UIBarButtonItem *_pauseButton;
    UIBarButtonItem *_previousButton;
    UIBarButtonItem *_nextButton;
    NSTimer *_holdingTimer;
    _Bool _holding;
    _Bool _mediaManagerUpdateInProgress;
    WAMessage *_currentMessage;
    _Bool _reloadCurrentMessageOnAppear;
    UIView *_busyBackgroundView;
    UIActivityIndicatorView *_busySpinner;
    WAMediaCaptionView *_captionView;
    WAImageToImagePanPopGestureRecognizer *_panPopGesture;
    WAMediaManager *_mediaManager;
    long long _currentPageIndex;
    UIScrollView *_pagingScrollView;
    UIToolbar *_toolbar;
    UIView *_viewMediaInfo;
    UILabel *_labelMediaInfo;
}

@property(retain, nonatomic) UILabel *labelMediaInfo; // @synthesize labelMediaInfo=_labelMediaInfo;
@property(retain, nonatomic) UIView *viewMediaInfo; // @synthesize viewMediaInfo=_viewMediaInfo;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIScrollView *pagingScrollView; // @synthesize pagingScrollView=_pagingScrollView;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) WAMediaManager *mediaManager; // @synthesize mediaManager=_mediaManager;
- (void).cxx_destruct;
- (void)applicationWillPresentCallScreen:(id)arg1;
- (void)gestureRecognizerWillFinishManagingInteractivePopTransition:(id)arg1;
- (void)gestureRecognizerDidBeginManagingInteractivePopTransition:(id)arg1;
- (void)gestureRecognizerWillBeginManagingInteractivePopTransition:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)usesScreenEdgePanGestureRecognizerForCustomPopTransition;
- (id)popFromAnimationIdentifier;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)nonTransitioningContainerView;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)wa_applicationWillEnterForeground;
- (void)wa_applicationDidEnterBackground;
- (void)setCurrentPageIndex:(long long)arg1 scrollToPage:(_Bool)arg2;
- (void)refreshInterfaceOnPageChange;
- (void)mediaGalleryController:(id)arg1 didSelectMediaAtIndexPath:(id)arg2;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)assignImage:(id)arg1 toContactID:(int)arg2;
- (void)presentMoveAndScaleViewControllerForPerson:(void *)arg1;
- (void)assignImageToContact;
- (void)saveCurrentMedia;
- (_Bool)isMediaScrollViewInFullScreenMode:(id)arg1;
- (void)mediaScrollViewDidEndZooming:(id)arg1;
- (void)mediaScrollViewWillBeginZooming:(id)arg1;
- (void)mediaScrollViewWillBeginDragging:(id)arg1;
- (void)mediaScrollViewWillBeginZoomBounceAnimation:(id)arg1;
- (void)mediaScrollViewDidScroll:(id)arg1;
- (void)mediaScrollViewDidZoom:(id)arg1;
- (void)updateImageRectOfCaptionViewForMediaScrollView:(id)arg1;
- (void)mediaScrollViewDidEndScrubbing:(id)arg1;
- (void)mediaScrollViewDidBeginScrubbing:(id)arg1;
- (struct UIEdgeInsets)mediaScrollViewLayoutInset:(id)arg1;
- (_Bool)mediaScrollViewCanShowErrorAlertView:(id)arg1;
- (void)mediaScrollViewWantsFullscreenTimerInvalidated:(id)arg1;
- (void)mediaScrollViewDidFinishLongPress:(id)arg1;
- (void)mediaScrollViewDidReceiveSingleTap:(id)arg1;
- (void)mediaScrollViewPlaybackDidFinish:(id)arg1;
- (void)mediaScrollViewPlaybackStateDidChange:(id)arg1;
- (void)mediaScrollViewLoadStateDidChange:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateCaptionView;
- (void)relayoutCaptionView;
- (void)wa_fontSizeDidChange;
- (void)didReceiveMemoryWarning;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (id)rotatingFooterView;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotate;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)deleteCurrentMedia:(id)arg1;
- (void)showAllMedia:(id)arg1;
- (void)navigateToNextPage:(id)arg1;
- (void)beginSeekingForward:(id)arg1;
- (void)handleNextButtonTouchDown:(id)arg1;
- (void)handleNextButtonTouchUp:(id)arg1;
- (void)navigateToPreviousPage:(id)arg1;
- (void)beginSeekingBackward:(id)arg1;
- (void)handlePreviousButtonTouchDown:(id)arg1;
- (void)handlePreviousButtonTouchUp:(id)arg1;
- (void)showMediaActions:(id)arg1;
- (void)togglePlayPause:(id)arg1;
- (void)reallyDeleteCurrentMedia;
- (void)tilePages;
- (void)configurePage:(id)arg1 forIndex:(unsigned long long)arg2;
- (id)pageForIndex:(unsigned long long)arg1;
- (_Bool)isDisplayingPageForIndex:(unsigned long long)arg1;
- (void)recyclePage:(id)arg1;
- (id)dequeueRecycledPage;
- (void)shareMediaExternally;
- (void)forwardMediaViaWhatsAppToContactInfo:(id)arg1;
- (void)showPersonPickerForMediaForwardViaWhatsApp;
- (void)setProfilePhoto;
- (void)assignCurrentImageToGroup;
- (void)setSpinnerHidden:(_Bool)arg1;
- (void)hideBarsTimer:(id)arg1;
- (void)cancelHideBarsTimer;
- (void)startHideBarsTimer;
- (long long)preferredStatusBarStyle;
- (void)setFullScreenMode:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setFullScreenMode:(_Bool)arg1;
- (_Bool)fullScreenModeAllowed;
- (void)updateToolbar;
- (void)updateInterface;
- (void)reloadPagingScrollView;
- (double)topLayoutEdge;
- (struct CGRect)frameForPageAtIndex:(unsigned long long)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)mediaManagerDidChangeContent:(id)arg1;
- (void)mediaManagerWillChangeContent:(id)arg1;
- (void)reloadMediaViewer;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

