//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAURLDownloadTaskData.h"

@class NSString, NSURL;

@interface WAMMSDownloadTaskData : WAURLDownloadTaskData
{
    NSString *_originalHost;
    NSURL *_transformedURL;
    _Bool _autodownload;
    NSURL *_fallbackRemoteURL;
}

@property(readonly, nonatomic, getter=isAutodownload) _Bool autodownload; // @synthesize autodownload=_autodownload;
@property(readonly, copy, nonatomic) NSURL *fallbackRemoteURL; // @synthesize fallbackRemoteURL=_fallbackRemoteURL;
- (void).cxx_destruct;
- (void)calculateHashOfFileAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transformDownloadedFileAtURLIfNeeded:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)validateDownloadedFileAtURL:(id)arg1 forTask:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)modifyRequestConfigForRetry:(id)arg1 bytesReceived:(long long)arg2 error:(id)arg3;
- (void)dealloc;
- (id)initWithMessage:(id)arg1 autodownload:(_Bool)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

