//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABackupOperation.h"

@class NSString;

@interface WAMoveOperation : WABackupOperation
{
    _Bool _succeeded;
    NSString *_source;
    NSString *_destination;
}

@property(readonly, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(readonly, nonatomic) NSString *source; // @synthesize source=_source;
- (void).cxx_destruct;
- (void)run;
- (_Bool)succeeded;
- (id)initWithSource:(id)arg1 andDestination:(id)arg2;

@end

