//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "WACameraViewControllerDelegate.h"
#import "WACaptionBarDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WAMediaPickerControllerDelegate.h"
#import "WAMultiSendThumbnailBrowserViewDelegate.h"
#import "WAMultiSendTitleViewDelegate.h"
#import "WAPageableItemBrowserViewDelegate.h"

@class NSArray, NSDate, NSMutableArray, NSString, UIBarButtonItem, UIProgressView, UIView, WACaptionBar, WAMediaPickerLibraryController, WAMultiSendThumbnailBrowserView, WAMultiSendTitleView, WAPageableItemBrowserView;

@interface WAMultiSendPreviewViewController : WAViewController <WAPageableItemBrowserViewDelegate, WAMultiSendThumbnailBrowserViewDelegate, WAMediaPickerControllerDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, WAMultiSendTitleViewDelegate, WACaptionBarDelegate, UIGestureRecognizerDelegate, WACameraViewControllerDelegate, WAImageToImageTransitioning>
{
    long long _selectedIndex;
    NSMutableArray *_mediaItems;
    NSString *_selectedItemUUIDBeforePresentingPicker;
    NSArray *_allAssetIdentifiersBeforePresentingPicker;
    NSDate *_imagePickerDelayStartTime;
    UIBarButtonItem *_cancelButton;
    UIBarButtonItem *_cancelExportButton;
    UIBarButtonItem *_doneCroppingButton;
    UIBarButtonItem *_sendButton;
    WAMultiSendTitleView *_titleView;
    WACaptionBar *_captionBar;
    double _captionBarAdjustment;
    _Bool _rotateCurrentItemWhenKeyboardHides;
    _Bool _cropCurrentItemWhenKeyboardHides;
    struct CGRect _cropRectBeforeCropping;
    UIProgressView *_exportProgressView;
    _Bool _cancelExportRequested;
    UIView *_touchTrapperView;
    _Bool _exportingItems;
    WAMediaPickerLibraryController *_libraryController;
    id <WAMultiSendPreviewViewControllerDelegate> _delegate;
    unsigned long long _pickerMode;
    id _lastUsedAssetCollectionIdentifier;
    WAMultiSendThumbnailBrowserView *_thumbnailBrowserView;
    WAPageableItemBrowserView *_pagingBrowserView;
}

+ (_Bool)isMixingImagesAndVideosSupported;
@property(nonatomic, getter=isExportingItems) _Bool exportingItems; // @synthesize exportingItems=_exportingItems;
@property(retain, nonatomic) WAPageableItemBrowserView *pagingBrowserView; // @synthesize pagingBrowserView=_pagingBrowserView;
@property(retain, nonatomic) WAMultiSendThumbnailBrowserView *thumbnailBrowserView; // @synthesize thumbnailBrowserView=_thumbnailBrowserView;
@property(retain, nonatomic) id lastUsedAssetCollectionIdentifier; // @synthesize lastUsedAssetCollectionIdentifier=_lastUsedAssetCollectionIdentifier;
@property(nonatomic) unsigned long long pickerMode; // @synthesize pickerMode=_pickerMode;
@property(nonatomic) __weak id <WAMultiSendPreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAMediaPickerLibraryController *libraryController; // @synthesize libraryController=_libraryController;
- (void).cxx_destruct;
- (void)multiSendTitleViewDidCropCurrentItem:(id)arg1;
- (void)multiSendTitleViewWillCropCurrentItem:(id)arg1;
- (void)multiSendTitleViewWillRotateCurrentItem:(id)arg1;
- (void)multiSendTitleViewWillDeleteCurrentItem:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)browserViewTapped:(id)arg1;
- (void)captionBarDidFinishEditing:(id)arg1;
- (void)captionBarDidChangeText:(id)arg1;
- (void)captionBarDidHideKeyboard:(id)arg1;
- (void)captionBarWillHideKeyboard:(id)arg1;
- (void)captionBarWillShowKeyboard:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)updateCaption;
- (void)setCaptionOfCurrentItem:(id)arg1;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)moveThumbnailBrowserViewToBottom;
- (void)multiSendThumbnailBrowserView:(id)arg1 willChangeFrame:(struct CGRect)arg2;
- (void)multiSendThumbnailBrowserViewDidRequestItemSort:(id)arg1;
- (_Bool)areMultiSendMediaItemsSorted;
- (id)indicesOfMultiSendMediaItemsSortedByDate;
- (void)multiSendThumbnailBrowserViewDidChangeEditingMode:(id)arg1;
- (void)multiSendThumbnailBrowserView:(id)arg1 didMoveItemAtIndex:(long long)arg2 toIndex:(long long)arg3;
- (void)multiSendThumbnailBrowserView:(id)arg1 didRequestSelectionOfItemAtIndex:(long long)arg2;
- (id)multiSendMediaItemAtIndex:(long long)arg1;
- (long long)multiSendThumbnailBrowserViewItemCount;
- (void)multiSendThumbnailBrowserViewDidRequestAddItem:(id)arg1;
- (void)multiSendThumbnailBrowserView:(id)arg1 didRequestRemovalOfItemAtIndex:(long long)arg2;
- (void)multiSendThumbnailBrowserViewDidRequestSend:(id)arg1;
- (_Bool)pageableItemBrowserViewKeyboardIsShown:(id)arg1;
- (void)pageableItemBrowserViewDidScroll:(id)arg1;
- (void)pageableItemBrowserViewDidEndFocusedTask:(id)arg1;
- (void)pageableItemBrowserViewWillBeginFocusedTask:(id)arg1;
- (void)pageableItemBrowserView:(id)arg1 didFinishRotatingItemAtIndex:(long long)arg2;
- (void)pageableItemBrowserView:(id)arg1 willAnimateRotationOfItemAtIndex:(long long)arg2 angle:(float)arg3;
- (void)pageableItemBrowserView:(id)arg1 didEndEditingAnimationForItemAtIndex:(long long)arg2;
- (void)pageableItemBrowserView:(id)arg1 willBeginEditingAnimationForItemAtIndex:(long long)arg2;
- (void)pageableItemBrowserView:(id)arg1 didUpdateThumbnailOfItemAtIndex:(long long)arg2;
- (void)pageableItemBrowserView:(id)arg1 wantsToDeleteItemAtIndex:(long long)arg2;
- (void)pageableItemBrowserViewCurrentIndexDidChange:(id)arg1;
- (long long)pageableItemCount:(id)arg1;
- (id)pageableItemBrowserView:(id)arg1 itemAtIndex:(long long)arg2;
- (void)mediaPickerControllerDidFinishPresenting:(id)arg1;
- (void)mediaPickerController:(id)arg1 didFinishWithSelectedItems:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)cameraViewController:(id)arg1 didSelectMediaPickerAsset:(id)arg2 cancelSelectionHandler:(CDUnknownBlockType)arg3;
- (void)cameraViewControllerDidCancel:(id)arg1;
- (void)cameraViewController:(id)arg1 didFinishWithMediaItems:(id)arg2;
- (void)cancelCropping;
@property(nonatomic, getter=isCroppingCurrentItem) _Bool croppingCurrentItem;
- (void)doneCropping:(id)arg1;
- (id)mediaItemWithUUID:(id)arg1;
- (id)mediaItemWithAssetIdentifier:(id)arg1;
- (void)updateExportProgress;
- (void)cancelExport:(id)arg1;
- (void)sendMediaItems:(id)arg1 fromItems:(id)arg2 atIndex:(long long)arg3 saveToCameraRoll:(_Bool)arg4;
- (void)finishWithProcessedItems:(id)arg1;
- (void)sendAllMediaItems:(id)arg1;
- (void)removeImageAtIndex:(long long)arg1;
- (void)takeMorePhotos;
- (void)takeAnotherPhoto;
- (void)selectAnotherImageFromPhotoLibrary;
- (void)selectAnotherImage;
- (void)cancelAllExport;
- (void)cancel:(id)arg1;
- (void)setSelectedIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)addMediaItem:(id)arg1;
- (void)cancelExportingAndDisableAutoExportingForAllMediaItems;
- (void)mediaItemDidUpdatePreviewContent:(id)arg1;
- (void)stopMonitoringMediaItem:(id)arg1;
- (void)startMonitoringMediaItem:(id)arg1;
- (unsigned long long)indexOfMediaItemWithIdentifier:(id)arg1;
- (void)updateInterface;
- (void)notifyVoiceOverOfPageChange;
- (void)reload;
- (void)updateLayout;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)resetStats;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

