//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, WAMultiSendPreviewViewController;

@protocol WAMultiSendPreviewViewControllerDelegate <NSObject>
- (void)multiSendPreviewViewControllerDidRequestRetakePhoto:(WAMultiSendPreviewViewController *)arg1;
- (void)multiSendPreviewViewControllerDidCancel:(WAMultiSendPreviewViewController *)arg1;
- (void)multiSendPreviewViewController:(WAMultiSendPreviewViewController *)arg1 didConfirmItems:(NSArray *)arg2;
@end

