//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface WAMultiSendTitleView : UIView
{
    UIButton *_deleteButton;
    UIButton *_rotateButton;
    UIButton *_cropButton;
    _Bool _cropping;
    _Bool _editingButtonsHidden;
    id <WAMultiSendTitleViewDelegate> _delegate;
}

+ (struct CGSize)preferredSize;
@property(nonatomic, getter=isEditingButtonsHidden) _Bool editingButtonsHidden; // @synthesize editingButtonsHidden=_editingButtonsHidden;
@property(nonatomic, getter=isCropping) _Bool cropping; // @synthesize cropping=_cropping;
@property(nonatomic) __weak id <WAMultiSendTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cropButtonTapped:(id)arg1;
- (void)rotateButtonTapped:(id)arg1;
- (void)deleteButtonTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

