//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMultiSendMediaItem.h"

@class NSObject<OS_dispatch_queue>, NSString, UIImage;

@interface WAMultiSendEditableImage : WAMultiSendMediaItem
{
    NSObject<OS_dispatch_queue> *_fileCacheQueue;
    NSString *_cachedOriginalImageForPreviewPath;
    NSString *_cachedRenderedImagePath;
    UIImage *_renderedContent;
    UIImage *_originalImageForPreviewToCacheToDisk;
}

- (void).cxx_destruct;
- (void)saveRenderedImageToDiskAsync;
- (void)renderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)didChangeImageOrientationFrom:(long long)arg1;
- (void)didChangeCropRectFrom:(struct CGRect)arg1;
- (id)renderedContent;
- (void)cacheOriginalImageForPreviewToDisk:(id)arg1;
- (id)generateOriginalImageForPreview;
- (void)reallyExportWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithImageURL:(id)arg1 renderedImage:(id)arg2 assetIdentifier:(id)arg3;

@end

