//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;

@interface WANetworkChangedViewController : WAViewController <UITableViewDataSource, UITableViewDelegate>
{
    UIImageView *_imageViewTower;
    UILabel *_labelHelperTextTop;
    UILabel *_labelHelperTextBottom;
    UIView *_viewButtons;
    UIButton *_buttonChangeNumber;
    UIButton *_buttonKeepNumber;
    id <WANetworkChangedControllerDelegate> _delegate;
}

+ (id)controller;
@property(nonatomic) __weak id <WANetworkChangedControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keepNumber:(id)arg1;
- (void)changeNumber:(id)arg1;
- (void)finishControllerWithResult:(_Bool)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

