//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "WASinglePhotoPickerControllerDelegate.h"
#import "WebImagePickerDelegate.h"

@class NSString, UIButton, UIImage, UIImageView, UILabel, UITableViewCell, UITextField, UIView;

@interface WANewGroupViewController : WATableViewController <WebImagePickerDelegate, WASinglePhotoPickerControllerDelegate>
{
    UIImage *_groupPicture;
    id <WANewGroupViewControllerDelegate> _delegate;
    UITableViewCell *_cellGroupSubject;
    UITextField *_textFieldSubject;
    UILabel *_labelCharCount;
    UIView *_viewTableHeader;
    UILabel *_labelHelperText;
    UIView *_viewAddPhoto;
    UIImageView *_imageGroupPicture;
    UIButton *_buttonAddPhoto;
    UIButton *_buttonEditPhoto;
}

@property(retain, nonatomic) UIButton *buttonEditPhoto; // @synthesize buttonEditPhoto=_buttonEditPhoto;
@property(retain, nonatomic) UIButton *buttonAddPhoto; // @synthesize buttonAddPhoto=_buttonAddPhoto;
@property(retain, nonatomic) UIImageView *imageGroupPicture; // @synthesize imageGroupPicture=_imageGroupPicture;
@property(retain, nonatomic) UIView *viewAddPhoto; // @synthesize viewAddPhoto=_viewAddPhoto;
@property(retain, nonatomic) UILabel *labelHelperText; // @synthesize labelHelperText=_labelHelperText;
@property(retain, nonatomic) UIView *viewTableHeader; // @synthesize viewTableHeader=_viewTableHeader;
@property(retain, nonatomic) UILabel *labelCharCount; // @synthesize labelCharCount=_labelCharCount;
@property(retain, nonatomic) UITextField *textFieldSubject; // @synthesize textFieldSubject=_textFieldSubject;
@property(retain, nonatomic) UITableViewCell *cellGroupSubject; // @synthesize cellGroupSubject=_cellGroupSubject;
@property(nonatomic) __weak id <WANewGroupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)singlePhotoPickerControllerDidCancel:(id)arg1;
- (void)singlePhotoPickerController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)webImagePickerDidCancel:(id)arg1;
- (void)webImagePicker:(id)arg1 didSelectImage:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)layoutTableHeader;
- (void)showImageSearchController;
- (void)reallyShowImagePickerForSourceType:(long long)arg1;
- (void)showImagePickerForSourceType:(long long)arg1;
- (void)updateGroupPicture;
- (void)updateCharCount;
- (void)textFieldValueChanged:(id)arg1;
- (void)editPhotoAction:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

