//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAudioPlayer, CTCallCenter, NSArray, NSMutableDictionary, NSString, SoundEffect, WAPushSound;

@interface WANotificationCenter : NSObject
{
    CTCallCenter *_callCenter;
    SoundEffect *_incomingSoundEffect;
    SoundEffect *_outgoingSoundEffect;
    AVAudioPlayer *_incomingSoundShort;
    NSMutableDictionary *_lastIncomingSounds;
    _Bool _playOfflineMessageSound;
    _Bool _chatSoundsEnabled;
    _Bool _chatVibrateEnabled;
    _Bool _showMessagePreview;
    _Bool _personalMessageAlertsEnabled;
    _Bool _groupMessageAlertsEnabled;
    _Bool _callAlertsEnabled;
    unsigned long long _inAppAlertStyle;
    NSString *_personalMessageSound;
    NSString *_groupMessageSound;
    NSString *_callSound;
    NSArray *_pushSoundSets;
    NSArray *_ringtoneSets;
    WAPushSound *_defaultRingtone;
}

+ (id)titleForWAAlertStyle:(unsigned long long)arg1;
@property(readonly, nonatomic) WAPushSound *defaultRingtone; // @synthesize defaultRingtone=_defaultRingtone;
@property(readonly, nonatomic) NSArray *ringtoneSets; // @synthesize ringtoneSets=_ringtoneSets;
@property(readonly, nonatomic) NSArray *pushSoundSets; // @synthesize pushSoundSets=_pushSoundSets;
@property(nonatomic) _Bool callAlertsEnabled; // @synthesize callAlertsEnabled=_callAlertsEnabled;
@property(copy, nonatomic) NSString *callSound; // @synthesize callSound=_callSound;
@property(nonatomic) _Bool groupMessageAlertsEnabled; // @synthesize groupMessageAlertsEnabled=_groupMessageAlertsEnabled;
@property(copy, nonatomic) NSString *groupMessageSound; // @synthesize groupMessageSound=_groupMessageSound;
@property(nonatomic) _Bool personalMessageAlertsEnabled; // @synthesize personalMessageAlertsEnabled=_personalMessageAlertsEnabled;
@property(copy, nonatomic) NSString *personalMessageSound; // @synthesize personalMessageSound=_personalMessageSound;
@property(nonatomic) _Bool showMessagePreview; // @synthesize showMessagePreview=_showMessagePreview;
@property(nonatomic) unsigned long long inAppAlertStyle; // @synthesize inAppAlertStyle=_inAppAlertStyle;
@property(nonatomic) _Bool chatVibrateEnabled; // @synthesize chatVibrateEnabled=_chatVibrateEnabled;
@property(nonatomic) _Bool chatSoundsEnabled; // @synthesize chatSoundsEnabled=_chatSoundsEnabled;
@property _Bool playOfflineMessageSound; // @synthesize playOfflineMessageSound=_playOfflineMessageSound;
- (void).cxx_destruct;
- (void)playOutgoingSoundEffect;
- (void)resetIncomingMessageSoundSquelchFor:(id)arg1;
- (void)playIncomingSoundEffectShort:(id)arg1;
- (void)playIncomingSoundEffect;
- (void)playOutgoingSoundEffectIfAllowed;
- (void)playIncomingSoundEffectForWAMessage:(id)arg1;
- (void)loadNotificationSounds;
- (void)resetToDefaults;
- (void)migrateSettings;
- (void)loadSettings;
- (void)initializeDefaults;
- (id)init;

@end

