//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class _WACustomSeparatorView;

@interface WANotificationSoundPickerCell : UITableViewCell
{
    _WACustomSeparatorView *_separator;
    _Bool _soundSelected;
    _Bool _doubleSeparator;
}

@property(nonatomic) _Bool doubleSeparator; // @synthesize doubleSeparator=_doubleSeparator;
@property(nonatomic) _Bool soundSelected; // @synthesize soundSelected=_soundSelected;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;

@end

