//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UIColor, UIImage, UIView;

@interface WAOverlayImageView : UIImageView
{
    UIView *_overlayView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *overlayColor;
@property(retain, nonatomic) UIImage *originalImage;
- (void)setImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

