//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAImageCropToolViewDelegate.h"

@class NSString, UITapGestureRecognizer, WACropAwareImageView, WAImageCropToolView, WAMultiSendMediaItem;

@interface WAPageableImageScrollView : UIScrollView <WAImageCropToolViewDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    WACropAwareImageView *_imageView;
    float _scaleToRestoreAfterResize;
    struct CGPoint _pointToCenterAfterResize;
    _Bool _zoomingInProgress;
    _Bool _suppressLayout;
    WAImageCropToolView *_cropToolView;
    _Bool _interactiveCroppingInProgress;
    UITapGestureRecognizer *_singleTapGesture;
    UITapGestureRecognizer *_doubleTapGesture;
    struct CGRect _previousCropRect;
    _Bool _performRotationAfterZooming;
    _Bool _toggleCroppingAfterZooming;
    _Bool _allowsEditing;
    WAMultiSendMediaItem *_item;
    id <WAPageableImageScrollViewEditingDelegate> _editingDelegate;
    double _editButtonsAlpha;
    struct UIEdgeInsets _edgeInsetsForMinimumZoom;
}

@property(nonatomic) double editButtonsAlpha; // @synthesize editButtonsAlpha=_editButtonsAlpha;
@property(nonatomic) __weak id <WAPageableImageScrollViewEditingDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
@property(nonatomic) _Bool allowsEditing; // @synthesize allowsEditing=_allowsEditing;
@property(readonly, nonatomic) WACropAwareImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) struct UIEdgeInsets edgeInsetsForMinimumZoom; // @synthesize edgeInsetsForMinimumZoom=_edgeInsetsForMinimumZoom;
@property(retain, nonatomic) WAMultiSendMediaItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)setInteractiveCroppingEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)recenterImageView;
- (void)setZoomingEnabled:(_Bool)arg1;
- (void)configureImageViewWithCropping:(_Bool)arg1;
- (id)rotatedFullScreenImage;
- (void)setUpFullImageView:(id)arg1 croppedImageView:(id)arg2 withReferenceFrame:(struct CGRect)arg3 referenceFrameIsCropped:(_Bool)arg4;
@property(nonatomic) _Bool interactiveCroppingEnabled;
- (void)imageCropToolViewNormalizedCropRectDidFinishChanging:(id)arg1;
- (void)imageCropToolViewNormalizedCropRectDidChange:(id)arg1;
- (void)imageCropToolViewNormalizedCropRectWillBeginChanging:(id)arg1;
- (void)rotateViews:(id)arg1 byAngle:(float)arg2 aroundPoint:(struct CGPoint)arg3 scaleChange:(float)arg4 animationDuration:(double)arg5 animationBlock:(CDUnknownBlockType)arg6 completion:(CDUnknownBlockType)arg7;
- (void)setImageOrientation:(long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)toggleZoomInOutAtPoint:(struct CGPoint)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)calculateForImageOfSize:(struct CGSize)arg1 displaySize:(struct CGSize *)arg2 minimumZoomScale:(double *)arg3 maximumZoomScale:(double *)arg4 initialZoomScale:(double *)arg5;
- (void)recalculateZoom;
- (void)didChangeFrameSize;
- (void)willChangeFrameSize;
- (void)setFrame:(struct CGRect)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)shouldShowEditButtons;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)doubleTapReceived:(id)arg1;
- (void)singleTapReceived:(id)arg1;
- (id)cloneButtonForRotationAnimation:(id)arg1;
- (void)setVisibility:(float)arg1;
- (float)visibility;
- (void)toggleCropMode;
- (void)toggleCropMode:(id)arg1;
@property(nonatomic, getter=isCropping) _Bool cropping;
- (void)reallyRotateCounterClockwise;
- (void)rotateCounterClockwise;
- (void)relayoutAlongsideLayerAnimation;
- (void)reset;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

