//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UIView, WAPhotoMoveAndScaleCropView;

@interface WAPhotoMoveAndScaleViewController : WAViewController <UIScrollViewDelegate>
{
    WAPhotoMoveAndScaleCropView *_cropView;
    UIActivityIndicatorView *_spinner;
    _Bool _statusBarWasHidden;
    UIView *_imageContainerView;
    UIImageView *_imageView;
    UIImage *_blurredImage;
    UIImageView *_blurredImageView;
    double _blurredImageScaleFactor;
    _Bool _adjustsStatusBarAutomatically;
    unsigned long long _mode;
    UIImage *_originalImage;
    double _minimumWidth;
    double _maximumWidth;
    id <WAPhotoMoveAndScaleViewControllerDelegate> _delegate;
    CDUnknownBlockType _completionHandler;
    UIScrollView *_scrollView;
    UILabel *_titleLabel;
    UIButton *_cancelButton;
    UIButton *_doneButton;
    UIView *_bottomView;
    UIImageView *_bottomViewBackgroundView;
    UIImageView *_bottomViewShadowView;
    UIView *_footerContentView;
    UIImageView *_staticImageView;
}

@property(retain, nonatomic) UIImageView *staticImageView; // @synthesize staticImageView=_staticImageView;
@property(retain, nonatomic) UIView *footerContentView; // @synthesize footerContentView=_footerContentView;
@property(retain, nonatomic) UIImageView *bottomViewShadowView; // @synthesize bottomViewShadowView=_bottomViewShadowView;
@property(retain, nonatomic) UIImageView *bottomViewBackgroundView; // @synthesize bottomViewBackgroundView=_bottomViewBackgroundView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool adjustsStatusBarAutomatically; // @synthesize adjustsStatusBarAutomatically=_adjustsStatusBarAutomatically;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak id <WAPhotoMoveAndScaleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(nonatomic) double minimumWidth; // @synthesize minimumWidth=_minimumWidth;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (id)rotatingHeaderView;
- (id)rotatingFooterView;
- (void)scrollViewDidZoom:(id)arg1;
- (void)recenterContainerView;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)configureScrollViewForZooming;
- (id)imageForCurrentZoomRect;
- (void)cancel:(id)arg1;
- (void)done:(id)arg1;
- (void)layoutFooter;
- (void)relayout;
- (void)updateInterfaceForMode;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)makeBlurredImage;
- (void)resetImageViewLayout;
- (long long)preferredStatusBarStyle;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

