//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MKAnnotation.h"

@class CLLocation, NSObject<OS_dispatch_group>, NSString, UIImage;

@interface WAPlace : NSObject <MKAnnotation>
{
    NSObject<OS_dispatch_group> *_infoLoadingGroup;
    NSString *_placeId;
    NSString *_name;
    NSString *_shortAddress;
    NSString *_fullAddress;
    NSString *_urlString;
    NSString *_iconURLString;
    CLLocation *_location;
    double _distance;
    UIImage *_loResMapThumbnail;
    UIImage *_hiResMapThumbnail;
    unsigned long long _source;
}

+ (void)fetchAppleMapsThumbnailWithScale:(float)arg1 forLocation:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)fetchGoogleMapsThumbnailWithScale:(float)arg1 forLocation:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) unsigned long long source; // @synthesize source=_source;
@property(retain, nonatomic) UIImage *hiResMapThumbnail; // @synthesize hiResMapThumbnail=_hiResMapThumbnail;
@property(retain, nonatomic) UIImage *loResMapThumbnail; // @synthesize loResMapThumbnail=_loResMapThumbnail;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *iconURLString; // @synthesize iconURLString=_iconURLString;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) NSString *fullAddress; // @synthesize fullAddress=_fullAddress;
@property(retain, nonatomic) NSString *shortAddress; // @synthesize shortAddress=_shortAddress;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *placeId; // @synthesize placeId=_placeId;
- (void).cxx_destruct;
- (void)fetchHiResThumbnailWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)hiResThumbnailFetchNeeded;
- (void)fetchLoResThumbnailWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)loResThumbnailFetchNeeded;
- (void)fetchGooglePlaceDetailsWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)placeDetailsFetchNeeded;
@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (long long)compare:(id)arg1;
- (id)initWithSource:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

