//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWaitOperation.h"

@class NSArray, NSString, WABackup, WACleanUpBackupOperation;

@interface WAPrepareBackupOperation : WAWaitOperation
{
    WABackup *_backup;
    NSArray *_tarOperations;
    WACleanUpBackupOperation *_cleanUp;
    NSString *_localBackupPath;
}

@property(retain, nonatomic) NSString *localBackupPath; // @synthesize localBackupPath=_localBackupPath;
- (void).cxx_destruct;
- (id)createUploadOperationWithDependencies:(id)arg1;
- (id)createCleanUpOperationWithDependencies:(id)arg1;
- (id)createCopyFileFromPath:(id)arg1 toPath:(id)arg2;
- (id)createDatabaseOperations;
- (id)createCopyTARFromPath:(id)arg1 toPath:(id)arg2;
- (id)createTARCopyOperations:(id)arg1 withUpload:(id)arg2;
- (id)prepareTAROperations;
- (void)saveNetworkUsageStatistics;
- (void)saveBackupInformation;
- (id)buildBackupInformation;
- (void)createLocalBackupDirectory;
- (void)lockSyncManager;
- (void)drop;
- (void)disconnect;
- (long long)temporaryBackupSize;
- (_Bool)calculatePotentialBackupSize;
- (_Bool)checkForRegistration;
- (_Bool)checkForCorruption;
- (_Bool)requireChatStore;
- (_Bool)requireConnection;
- (_Bool)checkBattery;
- (void)cancel;
- (void)performDroppedActions;
- (void)performDisconnectedActions;
- (void)run;
- (void)main;
- (id)initWithBackup:(id)arg1;

@end

