//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

@class NSDate, NSString, WAActivityLabel, WAPrivacyPolicy, WATableRow;

@interface WAPrivacySettingsPicker : WAStaticTableViewController
{
    WATableRow *_nooneRow;
    WATableRow *_contactsRow;
    WATableRow *_allUsersRow;
    WAActivityLabel *_activityLabel;
    NSDate *_activityStartTime;
    unsigned long long _privacyCategory;
    NSString *_titleString;
    WAPrivacyPolicy *_privacyPolicy;
}

@property(retain) WAPrivacyPolicy *privacyPolicy; // @synthesize privacyPolicy=_privacyPolicy;
- (void).cxx_destruct;
- (void)privacyPolicyDidChange:(id)arg1;
- (void)hideActivity;
- (void)showActivity;
- (void)selectValue:(unsigned long long)arg1;
- (void)updateCheckMarks;
- (void)setupTableView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initForCategory:(unsigned long long)arg1 title:(id)arg2;

@end

