//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAPreviousBackup.h"

@class NSDictionary, WASharedMetadataQuery;

@interface WAPreviousBackup_Documents : WAPreviousBackup
{
    _Bool _loading;
    _Bool _uploadingInProgress;
    double _uploadingProgress;
    WASharedMetadataQuery *_query;
    unsigned long long _size;
    NSDictionary *_data;
}

@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (double)progress;
- (_Bool)backupUploadInProgress;
- (id)size;
- (id)photos;
- (id)messages;
- (id)date;
- (_Bool)exists;
- (_Bool)initialized;
- (void)cloudAccountChanged:(id)arg1;
- (void)jidDidChange:(id)arg1;
- (void)restartQuery;
- (void)destroyQuery:(_Bool)arg1;
- (void)startQuery;
- (void)processQuery:(id)arg1;
- (void)processFiles:(id)arg1;
- (void)reloadFile;
- (void)dealloc;
- (id)initWithManager:(id)arg1;

@end

