//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

@class NSDate, NSString, UISwitch, WAActivityLabel, WAPrivacyPolicy, WATableRow;

@interface WAPrivacySettingsViewController : WAStaticTableViewController
{
    WATableRow *_lastSeenRow;
    WATableRow *_profilePicRow;
    WATableRow *_statusRow;
    WATableRow *_blockedRow;
    WATableRow *_readReceiptsRow;
    UISwitch *_readReceiptsSwitch;
    WAActivityLabel *_activityLabel;
    NSDate *_activityStartTime;
    _Bool _needPrivacyRefresh;
    WAPrivacyPolicy *_privacyPolicy;
    NSString *_lastSeenTitle;
    NSString *_profilePhotoTitle;
    NSString *_statusMessageTitle;
}

@property(retain) NSString *statusMessageTitle; // @synthesize statusMessageTitle=_statusMessageTitle;
@property(retain) NSString *profilePhotoTitle; // @synthesize profilePhotoTitle=_profilePhotoTitle;
@property(retain) NSString *lastSeenTitle; // @synthesize lastSeenTitle=_lastSeenTitle;
@property(retain) WAPrivacyPolicy *privacyPolicy; // @synthesize privacyPolicy=_privacyPolicy;
- (void).cxx_destruct;
- (void)privacyPolicyDidChange:(id)arg1;
- (void)blockedContactsListUpdated:(id)arg1;
- (void)wa_applicationWillEnterForeground;
- (_Bool)isSafeToUnload;
- (void)switchReadReceiptsAction:(id)arg1;
- (void)updateBlockedContactsCountDisplay;
- (void)showBlacklistController;
- (void)updatePrivacyValues;
- (void)setupTableView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

