//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WAProgress : NSObject
{
    unsigned long long _expectedSectionCount;
    double _current;
    double _internalProgress;
    double _currentSize;
    unsigned long long _section;
    NSMutableArray *_sizes;
    double _multiplier;
}

@property(nonatomic) double multiplier; // @synthesize multiplier=_multiplier;
@property(retain, nonatomic) NSMutableArray *sizes; // @synthesize sizes=_sizes;
@property(nonatomic) unsigned long long section; // @synthesize section=_section;
@property(nonatomic) double currentSize; // @synthesize currentSize=_currentSize;
@property(nonatomic) double internalProgress; // @synthesize internalProgress=_internalProgress;
@property(nonatomic) double current; // @synthesize current=_current;
@property(nonatomic) unsigned long long expectedSectionCount; // @synthesize expectedSectionCount=_expectedSectionCount;
- (void).cxx_destruct;
- (void)finishSection;
- (void)updateCurrentSize;
- (void)setProgressForCurrentSection:(double)arg1;
- (void)addSectionWithSize:(double)arg1;
- (void)reset;
- (id)init;

@end

