//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSManagedObjectContext, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString;

@interface WAProfilePictureManager : NSObject
{
    NSOperationQueue *_thumbnailingQueue;
    NSObject<OS_dispatch_queue> *_personalPictureProcessingQueue;
    NSManagedObjectContext *_contactsStorageContext;
    CDUnknownBlockType _contactsContextReleaseBlock;
    NSObject<OS_dispatch_queue> *_groupPictureProcessingQueue;
    NSManagedObjectContext *_chatStorageContext;
    CDUnknownBlockType _chatContextReleaseBlock;
    NSMutableDictionary *_profilePictureDatabase;
    NSCache *_profilePictureCache;
    NSMutableDictionary *_pendingSetRequests;
    NSMutableSet *_pendingGetFullsizeRequests;
    NSString *_storageDirectory;
}

+ (_Bool)isProfilePictureValid:(id)arg1;
+ (id)sanitizedProfilePictureFromImage:(id)arg1;
+ (id)thumbnailForProfilePicture:(id)arg1;
+ (id)jpegDataForProfileThumbnail:(id)arg1;
+ (id)jpegDataForProfilePicture:(id)arg1;
+ (void)disallowProfilePictureRequests;
+ (_Bool)profilePictureRequestsAllowed;
+ (id)thumbnailFromProfilePicture:(id)arg1;
+ (id)groupPicturePlaceholder;
+ (id)personalPicturePlaceholder;
+ (id)fullPathToProfilePictureThumbnailForJID:(id)arg1;
+ (id)thumnbailFilenameForJID:(id)arg1;
+ (id)prepareToSaveFile:(id)arg1 inDirectory:(id)arg2 relativeToDirectory:(id)arg3;
+ (void)cancelBlock:(CDUnknownBlockType)arg1;
+ (CDUnknownBlockType)performBlock:(CDUnknownBlockType)arg1 onQueue:(id)arg2 afterDelay:(double)arg3;
+ (void)moveAllPicturesFromDirectory:(id)arg1 toDirectory:(id)arg2;
@property(readonly, nonatomic) NSString *storageDirectory; // @synthesize storageDirectory=_storageDirectory;
- (void).cxx_destruct;
- (void)reuploadMyProfilePictureOnlyIfNeeded:(_Bool)arg1;
- (void)requestMyProfilePictureIfNeeded;
- (void)deleteMyProfilePicture;
- (void)saveMyProfilePicture:(id)arg1;
- (void)saveMyProfilePictureData:(id)arg1 thumbnailData:(id)arg2;
- (id)myProfilePictureThumbnailData;
- (id)myProfilePictureData;
- (id)myProfilePictureThumbnail;
- (id)myProfilePictureReturningFullsizeImageAvailability:(_Bool *)arg1;
- (id)fullpathToMyProfilePicture;
- (id)pendingProfilePictureForJID:(id)arg1;
- (_Bool)hasPendingSetRequestForJID:(id)arg1;
- (void)requestProfilePictureDeleteForJID:(id)arg1 requestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestProfilePictureDeleteForJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setLargePictureData:(id)arg1 smallPictureData:(id)arg2 pictureID:(id)arg3 forWAChatSession:(id)arg4;
- (void)requestProfilePictureSetForJID:(id)arg1 picture:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestProfilePictureSetForJID:(id)arg1 withLargePictureData:(id)arg2 smallPictureData:(id)arg3 requestID:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)requestProfilePictureSetForJID:(id)arg1 withLargePictureData:(id)arg2 smallPictureData:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)requestSmallProfilePictureForJID:(id)arg1 onlyIfNecessary:(_Bool)arg2;
- (void)deleteProfilePictureForJID:(id)arg1;
- (void)fetchProfilePictureForJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)bestAvailablePictureForJID:(id)arg1 returningFullsizeImageAvailability:(_Bool *)arg2;
- (id)bestAvailablePictureForJID:(id)arg1;
- (void)deleteProfilePictureForWAStatus:(id)arg1;
- (void)deletePictureOfType:(unsigned long long)arg1 forWAStatus:(id)arg2;
- (id)savePictureData:(id)arg1 pictureType:(unsigned long long)arg2 pictureIdentifier:(id)arg3 forWAStatus:(id)arg4;
- (id)bestAvailablePictureForWAStatus:(id)arg1 returningFullsizeImageAvailability:(_Bool *)arg2;
- (id)bestAvailablePictureForWAStatus:(id)arg1;
- (void)processPictureChangeNotificationForContactWithJID:(id)arg1 pictureIdentifier:(id)arg2;
- (void)requestSmallProfilePictureForWAStatus:(id)arg1 onlyIfNecessary:(_Bool)arg2;
- (void)deleteGroupPictureForWAChatSession:(id)arg1;
- (void)deletePictureOfType:(unsigned long long)arg1 forWAChatSession:(id)arg2;
- (id)savePictureData:(id)arg1 pictureType:(unsigned long long)arg2 pictureIdentifier:(id)arg3 forWAChatSession:(id)arg4;
- (id)bestAvailablePictureForWAChatSession:(id)arg1 returningFullsizeImageAvailability:(_Bool *)arg2;
- (id)bestAvailablePictureForWAChatSession:(id)arg1;
- (void)processPictureChangeNotificationForGroupWithJID:(id)arg1 pictureIdentifier:(id)arg2 changeAuthorJID:(id)arg3 timestamp:(id)arg4;
- (void)requestSmallGroupPictureForWAChatSession:(id)arg1 onlyIfNecessary:(_Bool)arg2;
- (void)generateProfilePictureThumbnailFromPicture:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchGroupPictureForWAChatSession:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchPersonalProfilePictureForWAStatus:(id)arg1 fallbackToAddressBookPicture:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)createProfilePictureThumbnailForJID:(id)arg1 loadingOptions:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)shouldRequestPictureForWAStatus:(id)arg1;
- (void)setPictureData:(id)arg1 forJID:(id)arg2;
- (id)pictureDataForJID:(id)arg1;
- (void)resetProfilePictureRequestDateForJID:(id)arg1;
- (void)updateProfilePictureRequestDateForJID:(id)arg1;
- (_Bool)shouldRequestPictureForJID:(id)arg1;
- (void)deleteProfilePictureDatabase;
- (void)saveProfilePictureDatabase;
- (void)loadProfilePictureDatabase;
- (id)profilePictureDatabaseFilepath;
- (void)resetProfilePictureThumbnailCacheForJID:(id)arg1;
- (id)profilePictureThumbnailForJID:(id)arg1;
- (id)profilePictureThumbnailForJID:(id)arg1 loadingOptions:(int)arg2;
- (_Bool)hasPendingGetFullsizeRequestForJID:(id)arg1;
- (void)requestLargeProfilePictureForJID:(id)arg1 forced:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)bestAvailablePictureForJID:(id)arg1 addressBookPictureAllowed:(_Bool)arg2 fullsizeAvailable:(out _Bool *)arg3;
- (void)copyGroupPictureCachedThumbnailsFromJID:(id)arg1 toJID:(id)arg2;
- (void)deleteTemporaryGroupPictureForJID:(id)arg1;
- (id)temporaryGroupPictureForJID:(id)arg1;
- (void)storeTemporaryGroupPicture:(id)arg1 forWAChatSession:(id)arg2;
- (id)saveImageData:(id)arg1 forPictureOfType:(unsigned long long)arg2 withFilename:(id)arg3;
- (void)deletePictureOfType:(unsigned long long)arg1 atRelativePath:(id)arg2;
- (id)bestAvailablePictureWithRelativeFilePath:(id)arg1 returningFullsizeImageAvailability:(_Bool *)arg2;
- (void)useGeneratedProfilePictureThumbnail:(id)arg1 forJID:(id)arg2 isAddressBookPicture:(_Bool)arg3;
- (void)generateThumbnailFromImage:(id)arg1 forJID:(id)arg2 isAddressBookPicture:(_Bool)arg3;
- (void)deleteAllCachedThumbnailsAndResetRequestDates;
- (void)deleteProfilePictureThumbnailForJID:(id)arg1;
- (void)saveProfilePictureThumbnailPlaceholderForJID:(id)arg1;
- (id)profilePictureThumbnailForJID:(id)arg1 isPlaceholder:(_Bool *)arg2;
- (void)saveProfilePictureThumbnail:(id)arg1 forJID:(id)arg2;
- (void)releaseContactsMOC;
- (id)acquireContactsMOC;
- (void)releaseChatMOC;
- (id)acquireChatMOC;
- (id)init;
- (id)initWithStorageDirectory:(id)arg1;

@end

