//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAPushSound : NSObject
{
    _Bool _defaultSound;
    NSString *_name;
    NSString *_filename;
}

+ (id)pushSoundWithName:(id)arg1 filename:(id)arg2;
@property(nonatomic, getter=isDefaultSound) _Bool defaultSound; // @synthesize defaultSound=_defaultSound;
@property(readonly, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (id)initWithName:(id)arg1 filename:(id)arg2;

@end

