//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABaseReceiptTableViewCell.h"

@class UIFont, UIImageView, UILabel;

@interface WAReceiptTableViewCell : WABaseReceiptTableViewCell
{
    UILabel *_nameLabel;
    UIImageView *_receiptIcon;
    UIFont *_nameLabelFont;
}

@property(retain, nonatomic) UIFont *nameLabelFont; // @synthesize nameLabelFont=_nameLabelFont;
- (void).cxx_destruct;
- (void)setReceiptDate:(id)arg1;
- (void)layoutSubviews;
- (void)setReceiptType:(int)arg1 isMediaMessage:(_Bool)arg2;
- (id)initWithReuseIdentifier:(id)arg1;

@end

