//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAChatCellData.h"

@interface WASampleChatCellData : WAChatCellData
{
    _Bool _incoming;
    unsigned long long _type;
}

+ (id)cellDataWithText:(id)arg1 isIncoming:(_Bool)arg2;
- (id)nameColor;
- (id)shortName;
- (id)pushName;
- (id)fromName;
- (id)messageID;
- (_Bool)needToShowAlert;
- (_Bool)isSenderUnknown;
- (_Bool)isGroupMessage;
- (_Bool)isSending;
- (_Bool)isFromMe;
- (id)messageTimestampString;
- (unsigned long long)messageStatus;
- (unsigned long long)mediaOrigin;
- (unsigned long long)messageType;
- (id)message;
- (id)initWithText:(id)arg1 isIncoming:(_Bool)arg2;

@end

