//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSSet, UILabel, UIView, WALabel;

@interface WASearchResultTableViewCell : UITableViewCell
{
    UIView *_containerView;
    UILabel *_titleLabel;
    WALabel *_snippetLabel;
    UILabel *_dateLabel;
    NSSet *_searchTokens;
}

- (void).cxx_destruct;
- (void)configureWithSearchResultMessage:(id)arg1 searchTokens:(id)arg2;
- (void)configureFonts;
- (void)setUpPlaceholderForSizing;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1;

@end

