//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface WAShareContactTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UIImageView *_checkmarkView;
    UIView *_bottomEdgeView;
}

+ (double)heightForSharingUnit:(id)arg1 displayWidth:(double)arg2;
+ (double)preferredContentInset;
+ (id)cellWithReuseIdentifier:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool showBottomEdge;
@property(nonatomic) _Bool checked;
- (void)configureWithSharingUnit:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

