//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSMutableArray, NSString, NSURL;

@interface WASharedItemOutbox : NSObject <NSCoding>
{
    NSString *_outboxID;
    NSURL *_fileURL;
    NSMutableArray *_items;
}

+ (id)sharedItemOutboxAtURL:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *items;
- (void)dispose;
- (void)moveToTemporaryDirectory;
- (void)save;
- (void)addItem:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

