//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "WAPhotoMoveAndScaleViewControllerDelegate.h"

@class NSString;

@interface WASinglePhotoPickerController : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate, WAPhotoMoveAndScaleViewControllerDelegate>
{
    long long _lastStatusBarStyle;
    _Bool _lastStatusBarHidden;
    id <WASinglePhotoPickerControllerDelegate> _delegate;
    long long _sourceType;
    double _minimumWidth;
    double _maximumWidth;
}

@property(nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(nonatomic) double minimumWidth; // @synthesize minimumWidth=_minimumWidth;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(nonatomic) __weak id <WASinglePhotoPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)performCustomPushTransitionOnNavigationController:(id)arg1 toViewController:(id)arg2;
- (void)photoMoveAndScaleViewController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)presentFromViewController:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

