//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMediaManager.h"

@class WAMessage;

@interface WASingleMediaManager : WAMediaManager
{
    WAMessage *_message;
}

- (void).cxx_destruct;
- (void)deleteMessagesAtIndexPaths:(id)arg1;
- (_Bool)isForSingleItem;
- (id)indexPathOfMessage:(id)arg1;
- (id)messageAtIndexPath:(id)arg1;
- (id)indexPathFromIndex:(unsigned long long)arg1;
- (unsigned long long)indexFromIndexPath:(id)arg1;
- (unsigned long long)numberOfItems;
- (id)initWithMessage:(id)arg1;

@end

