//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "ProblemInputControllerDelegate.h"

@class NSString, UIViewController, WAServerStatus;

@interface WASupportEmailComposer : NSObject <ProblemInputControllerDelegate, MFMailComposeViewControllerDelegate>
{
    WAServerStatus *_serverStatus;
    WASupportEmailComposer *_retainedSelf;
    unsigned long long _numberOfFAQSearchResultsReturned;
    unsigned long long _numberOfFAQSearchResultsOpened;
    _Bool _skipServerStatusCheck;
    _Bool _registration;
    _Bool _suppressHUD;
    CDUnknownBlockType _completion;
    NSString *_context;
    NSString *_initialText;
    UIViewController *_controller;
}

+ (id)composer;
@property(retain, nonatomic) UIViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) _Bool suppressHUD; // @synthesize suppressHUD=_suppressHUD;
@property(nonatomic) _Bool registration; // @synthesize registration=_registration;
@property(nonatomic) _Bool skipServerStatusCheck; // @synthesize skipServerStatusCheck=_skipServerStatusCheck;
@property(copy, nonatomic) NSString *initialText; // @synthesize initialText=_initialText;
@property(copy, nonatomic) NSString *context; // @synthesize context=_context;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)probleminputControllerDidCancel:(id)arg1;
- (void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3 imageAttachments:(id)arg4;
- (void)cancel;
- (void)presentFromViewController:(id)arg1;
- (void)finishComposerWithResult:(_Bool)arg1;
- (void)composeEmailWithProblemDescription:(id)arg1 attachment:(id)arg2 imageAttachments:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

