//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSCondition, NSDate, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface WASyncManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_fullSyncTimer;
    NSObject<OS_dispatch_source> *_syncPollingTimer;
    NSMutableArray *_syncHistory;
    NSDate *_nextSyncDate;
    unsigned long long _nextSyncMode;
    unsigned long long _nextSyncContext;
    NSMutableArray *_pengingDeletes;
    NSArray *_processedDeletes;
    _Bool _syncEnabled;
    _Bool _syncInProgress;
    _Bool _locked;
    id <WASyncManagerDelegate> _delegate;
    NSCondition *_condition;
}

@property(readonly) NSCondition *condition; // @synthesize condition=_condition;
@property _Bool locked; // @synthesize locked=_locked;
@property _Bool syncInProgress; // @synthesize syncInProgress=_syncInProgress;
@property _Bool syncEnabled; // @synthesize syncEnabled=_syncEnabled;
@property(nonatomic) __weak id <WASyncManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)saveSyncHistory;
- (void)cleanSyncHistory;
- (void)loadSyncHistory;
- (void)addDeletedJIDs:(id)arg1;
- (void)reset;
- (void)enableSync;
- (void)processContactsSyncResponse:(id)arg1 mode:(unsigned long long)arg2 context:(unsigned long long)arg3;
- (int)runSyncIfNecessary;
- (void)runFullSyncIfNecessary;
- (void)setNextFullSyncDate:(id)arg1;
- (void)requestInteractiveSyncWithMode:(unsigned long long)arg1;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2;
- (id)init;

@end

