//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WATaskManager;

@interface WATask : NSObject
{
    _Bool _active;
    CDUnknownBlockType _handler;
    WATaskManager *_taskManager;
}

@property(nonatomic) __weak WATaskManager *taskManager; // @synthesize taskManager=_taskManager;
@property(readonly, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (void).cxx_destruct;
- (void)rescheduleIfNeeded;
- (id)initWithHandler:(CDUnknownBlockType)arg1;

@end

