//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVSpeechSynthesizerDelegate.h"

@class AVSpeechSynthesizer, NSString;

@interface WATextToSpeechEngine : NSObject <AVSpeechSynthesizerDelegate>
{
    AVSpeechSynthesizer *_synthesizer;
}

+ (id)sharedEngine;
- (void).cxx_destruct;
- (void)speechSynthesizer:(id)arg1 didFinishSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didCancelSpeechUtterance:(id)arg2;
- (void)pause;
- (void)speakUtterance:(id)arg1;
- (void)stopSpeakingImmediately;
@property(readonly, nonatomic, getter=isSpeechSelectionEnabled) _Bool speechSelectionEnabled;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

