//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageHelper.h"

@interface WAudioTrackMessageHelper : WAMessageHelper
{
}

+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForMessage:(id)arg1;
- (id)activitySubjectForActivityType:(id)arg1;
- (id)activityItemForActivityType:(id)arg1;
- (id)activityPlaceholderItem;
- (id)chatThumbnailReturningPermanentState:(out _Bool *)arg1;
- (void)storeOutgoingMedia:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)internalFetchImageRepresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)internalGenerateMediaBrowserThumbnailFromImageRepresentation:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

