//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABackupOperation.h"

@class NSString;

@interface WAUntarFileOperation : WABackupOperation
{
    _Bool _succeeded;
    NSString *_path;
    NSString *_destination;
    unsigned long long _extracted;
    unsigned long long _total;
}

- (void).cxx_destruct;
- (void)run;
- (double)progress;
- (_Bool)succeeded;
- (id)initWithPath:(id)arg1 destination:(id)arg2;

@end

