//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSURL, WAURLSessionDownloadTaskHandlerOS6;

@protocol WAURLSessionDownloadTaskHandlerOS6Delegate <NSObject>
- (void)downloadTaskOS6:(WAURLSessionDownloadTaskHandlerOS6 *)arg1 didCompleteWithError:(NSError *)arg2;
- (void)downloadTaskOS6:(WAURLSessionDownloadTaskHandlerOS6 *)arg1 didFinishDownloadingToURL:(NSURL *)arg2;
- (void)downloadTaskOS6:(WAURLSessionDownloadTaskHandlerOS6 *)arg1 didWriteData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
@end

