//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSString, WAURLRequestConfig, WAURLTaskStats;

@interface WAURLTaskData : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _suppressNotifications;
    NSString *_identifier;
    long long _retryCount;
    WAURLRequestConfig *_requestConfig;
    WAURLTaskStats *_stats;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool suppressNotifications; // @synthesize suppressNotifications=_suppressNotifications;
@property(retain, nonatomic) WAURLTaskStats *stats; // @synthesize stats=_stats;
@property(retain, nonatomic) WAURLRequestConfig *requestConfig; // @synthesize requestConfig=_requestConfig;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *shortIdentifier;
- (id)request;
- (id)modifyRequestConfigForRetry:(id)arg1 bytesReceived:(long long)arg2 error:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

