//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAVCardSharingUnit.h"

@class UIImage;

@interface WAVCardProfilePhotoSharingUnit : WAVCardSharingUnit
{
    UIImage *_image;
}

@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)stringForVCard;
- (id)initWithMergedContact:(id)arg1 index:(unsigned long long)arg2;

@end

