//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageHelper.h"

@interface WAVCardMessageHelper : WAMessageHelper
{
}

+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForMessage:(id)arg1;
- (id)activityDataTypeIdentifierForActivityType:(id)arg1;
- (id)activitySubjectForActivityType:(id)arg1;
- (id)activityItemForActivityType:(id)arg1;
- (id)activityPlaceholderItem;

@end

