//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAVCard : NSObject
{
    NSString *_contactName;
    NSString *_vCardString;
}

+ (id)mergedContactFromVCardString:(id)arg1;
+ (id)labelFromFieldDescriptions:(id)arg1;
+ (_Bool)isFieldNameForIMServiceValid:(id)arg1;
+ (_Bool)canShareInstantMessagingService:(id)arg1;
@property(copy, nonatomic) NSString *vCardString; // @synthesize vCardString=_vCardString;
@property(copy, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;
- (void).cxx_destruct;

@end

