//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WACaptionBarDelegate.h"

@class NSObject<OS_dispatch_group>, NSString, NSTimer, NSURL, UIBarButtonItem, WACaptionBar, WADoneWithSpinnerBarButtonItem, WAVideoPreviewStatusView, WAVideoTranscoder;

@interface WAVideoPreviewViewController : WAViewController <WACaptionBarDelegate, UIGestureRecognizerDelegate>
{
    WAVideoTranscoder *_transcoder;
    NSTimer *_progressTimer;
    NSObject<OS_dispatch_group> *_transcodeDispatchGroup;
    int _transcodeJobID;
    UIBarButtonItem *_cancelButton;
    _Bool _requiresTranscoding;
    _Bool _sendButtonTapped;
    _Bool _showsBackButton;
    NSString *_caption;
    NSURL *_videoURL;
    unsigned long long _videoFileSize;
    NSURL *_outputFileURL;
    NSURL *_referenceURL;
    NSURL *_assetLibraryURL;
    id _assetIdentifier;
    id <WAVideoPreviewViewControllerDelegate> _delegate;
    WAVideoPreviewStatusView *_progressView;
    WADoneWithSpinnerBarButtonItem *_sendButton;
    WACaptionBar *_captionBar;
}

+ (int)captionBarStyle;
+ (_Bool)movieFileAtURL:(id)arg1 hasSameDurationAsMovieFileAtURL:(id)arg2;
+ (void)controllerWithURL:(id)arg1 identifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)controllerWithURL:(id)arg1;
+ (id)controller;
@property(nonatomic) _Bool showsBackButton; // @synthesize showsBackButton=_showsBackButton;
@property(readonly, nonatomic) WACaptionBar *captionBar; // @synthesize captionBar=_captionBar;
@property(readonly, nonatomic) _Bool sendButtonTapped; // @synthesize sendButtonTapped=_sendButtonTapped;
@property(readonly, nonatomic) WADoneWithSpinnerBarButtonItem *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) WAVideoPreviewStatusView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak id <WAVideoPreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) id assetIdentifier; // @synthesize assetIdentifier=_assetIdentifier;
@property(copy, nonatomic) NSURL *assetLibraryURL; // @synthesize assetLibraryURL=_assetLibraryURL;
@property(copy, nonatomic) NSURL *referenceURL; // @synthesize referenceURL=_referenceURL;
@property(copy, nonatomic) NSURL *outputFileURL; // @synthesize outputFileURL=_outputFileURL;
@property(nonatomic) _Bool requiresTranscoding; // @synthesize requiresTranscoding=_requiresTranscoding;
@property(nonatomic) unsigned long long videoFileSize; // @synthesize videoFileSize=_videoFileSize;
@property(copy, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(copy, nonatomic) NSString *caption; // @synthesize caption=_caption;
- (void).cxx_destruct;
- (void)captionBarDidChangeText:(id)arg1;
- (void)captionBarDidFinishEditing:(id)arg1;
- (void)captionBarDidHideKeyboard:(id)arg1;
- (void)captionBarWillHideKeyboard:(id)arg1;
- (void)captionBarWillShowKeyboard:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)viewTapped:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didProcessVideo;
- (void)willProcessVideo;
- (void)processTranscodedVideoOfDuration:(double)arg1 atURL:(id)arg2 referenceURL:(id)arg3;
- (id)videoCompositionForTranscode;
- (id)assetToTranscode;
- (void)reallyProcessVideo;
- (void)setNeedsVideoProcessing;
- (void)cancelVideoProcessing;
- (CDStruct_e83c9415)timeRangeToExport;
- (_Bool)internalRequiresTranscoding;
- (void)waitForVideoProcessingToFinish;
- (void)sendVideo:(id)arg1;
- (void)updateSendButton;
- (void)updateProgress:(id)arg1;
@property(nonatomic, getter=isProgressViewHidden) _Bool progressViewHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)cancel:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

