//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UILabel, UIProgressView;

@interface WAVideoPreviewStatusView : UIView
{
    UILabel *_progressLabel;
    UIProgressView *_progressView;
}

- (void).cxx_destruct;
@property(nonatomic) float progress;
@property(retain, nonatomic) UIColor *textColor;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

