//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "WAViewControllerExtensions.h"
#import "WAViewControllerPrivateExtensions.h"

@class NSString, _WAViewControllerHelper;

@interface WAViewController : UIViewController <WAViewControllerPrivateExtensions, WAViewControllerExtensions>
{
    _WAViewControllerHelper *_wa_helper;
}

- (void).cxx_destruct;
- (void)visibleConnectionStatusDidChange;
@property(readonly, nonatomic) unsigned long long visibleConnectionStatus;
- (void)performAfterTransitionEnds:(CDUnknownBlockType)arg1;
- (void)wa_applicationDidEnterBackground;
- (void)wa_applicationWillEnterForeground;
- (void)wa_tintColorDidChange;
- (void)wa_fontSizeDidChange;
- (void)dismissAllDropDownAlertViewsWithAnimation:(_Bool)arg1;
- (void)dismissDropDownAlertView:(id)arg1 animated:(_Bool)arg2;
- (void)showDropDownAlertView:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)uniqueIdentifier;
@property(readonly, nonatomic) _WAViewControllerHelper *wa_helper;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

