//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABackupOperation.h"

@class NSObject<OS_dispatch_semaphore>;

@interface WAWaitOperation : WABackupOperation
{
    NSObject<OS_dispatch_semaphore> *_semaphore;
}

- (void).cxx_destruct;
- (void)finish;
- (void)cancel;
- (void)run;
- (id)init;

@end

