//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIFont, UILabel;

@interface WAWarningView : UIView
{
    UILabel *_label;
    UIView *_topBorder;
    UIView *_bottomBorder;
    UIView *_backgroundView;
    _Bool _translucentBackground;
    _Bool _showsTopBorder;
    _Bool _showsBottomBorder;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) _Bool showsBottomBorder; // @synthesize showsBottomBorder=_showsBottomBorder;
@property(nonatomic) _Bool showsTopBorder; // @synthesize showsTopBorder=_showsTopBorder;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) _Bool translucentBackground; // @synthesize translucentBackground=_translucentBackground;
- (void).cxx_destruct;
@property(nonatomic, getter=isTextShadowEnabled) _Bool textShadowEnabled;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) UIFont *font;
@property(copy, nonatomic) NSString *text;
- (struct CGSize)preferredSizeForWidth:(double)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

