//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSLock, NSString;

@interface XMPPClient : NSObject
{
    unsigned long long _lastSentChatState;
    NSLock *_outgoingChatStateLock;
    unsigned long long _lastReceivedChatState;
    NSLock *_incomingChatStateLock;
    unsigned long long _presence;
    NSDate *_outgoingChatStateTimestamp;
    NSDate *_incomingChatStateTimestamp;
    NSString *_groupJIDForChatState;
    NSDate *_lastSeenTimestamp;
    NSString *_jid;
}

@property(retain) NSString *jid; // @synthesize jid=_jid;
@property(retain) NSDate *lastSeenTimestamp; // @synthesize lastSeenTimestamp=_lastSeenTimestamp;
@property(retain) NSString *groupJIDForChatState; // @synthesize groupJIDForChatState=_groupJIDForChatState;
@property(retain) NSDate *incomingChatStateTimestamp; // @synthesize incomingChatStateTimestamp=_incomingChatStateTimestamp;
@property(retain) NSDate *outgoingChatStateTimestamp; // @synthesize outgoingChatStateTimestamp=_outgoingChatStateTimestamp;
@property unsigned long long presence; // @synthesize presence=_presence;
- (void).cxx_destruct;
@property unsigned long long lastReceivedChatState;
@property unsigned long long lastSentChatState;
- (void)reset;
- (id)initWithJID:(id)arg1;

@end

