//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendThumbnailPreview : _XMPPWebClientRequest
{
}

- (id)initForPictureId:(id)arg1 picture:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4 completion:(CDUnknownBlockType)arg5;

@end

