//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendChatSessions : _XMPPWebClientRequest
{
}

- (id)initWithChatSessions:(id)arg1 requestID:(id)arg2 isDuplicate:(_Bool)arg3 isPreemptive:(_Bool)arg4 forWebSession:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

