//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPStanza.h"

@interface XMPPChatStateStanza : XMPPStanza
{
}

+ (id)stringForChatState:(unsigned long long)arg1;
+ (id)chatStateStrings;
- (id)log;
@property(nonatomic) unsigned long long state;
- (id)initWithState:(unsigned long long)arg1;

@end

