//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XMPPIQStanza;

@interface XMPPRequest : NSObject
{
    long long _retriesRemaining;
    XMPPIQStanza *_iq;
    double _timeout;
    unsigned long long _state;
    XMPPIQStanza *_response;
    id _completion;
}

@property(copy, nonatomic) id completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) XMPPIQStanza *response; // @synthesize response=_response;
@property(readonly, nonatomic) unsigned long long state; // @synthesize state=_state;
@property(readonly, nonatomic) long long retriesRemaining; // @synthesize retriesRemaining=_retriesRemaining;
@property(readonly, nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(retain, nonatomic) XMPPIQStanza *iq; // @synthesize iq=_iq;
- (void).cxx_destruct;
- (void)didFailWithError:(id)arg1;
- (void)didSuceedWithResponse:(id)arg1;
- (void)processResponse:(id)arg1;
- (_Bool)cancelAndPrepareForRetry:(_Bool)arg1;
- (void)failOnNoConnection;
- (void)sendOnStream:(id)arg1;
- (id)initWithTimeout:(double)arg1;
- (id)init;

@end

