//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface XMPPTokenizer : NSObject
{
    NSDictionary *_textToTokenDictionaries[240];
    NSDictionary *_tokenToTextDictionaries[240];
}

+ (id)webClientTokenizer;
+ (id)mainTokenizer;
- (void).cxx_destruct;
- (id)convertTokenToText:(unsigned char)arg1 usingDictionaryType:(int)arg2;
- (id)convertTextToToken:(id)arg1;
- (void)setTokenToTextDictionary:(id)arg1 forDictionaryType:(int)arg2;
- (void)setTextToTokenDictionary:(id)arg1 forDictionaryType:(int)arg2;
- (void)dealloc;
- (id)init;

@end

