//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, NSNumber, NSString, WAMessage, XMPPAckStanza, XMPPConnection, XMPPGroup, XMPPGroupNotification, XMPPReceiptStanza, XMPPStanza, XMPPStanzaElement, XMPPStatus;

@protocol XMPPConnectionDelegate <NSObject>
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveOfflineReceiptWithStanzaIDs:(NSArray *)arg2 fromJID:(NSString *)arg3 participantJID:(NSString *)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveServerRejectRetryForReceipt:(XMPPStanzaElement *)arg2 registrationId:(int)arg3 fromJID:(NSString *)arg4 participanr:(NSString *)arg5;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveRetryReceiptForStanzaID:(NSString *)arg2 fromJID:(NSString *)arg3 participantJID:(NSString *)arg4 registrationId:(int)arg5 retryCount:(int)arg6;
- (void)xmppConnection:(XMPPConnection *)arg1 didRequestDownloadOfMediaInMessage:(WAMessage *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveServerErrorForOutgoingMessagesWithStanzaIDs:(NSArray *)arg2 fromJID:(NSString *)arg3 participantJID:(NSString *)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveServerErrorAckForIncomingMessageWithStanzaID:(NSString *)arg2 fromJID:(NSString *)arg3 participantJID:(NSString *)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveCallOfferReceipt:(XMPPReceiptStanza *)arg2;
- (void)xmppConnectionDidChangeNetworkStateDuringCall:(XMPPConnection *)arg1;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveCallAck:(XMPPAckStanza *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 didReceiveIncomingCallStanza:(XMPPStanza *)arg2;
- (void)xmppConnectionDidReceiveOfflineMarker:(XMPPConnection *)arg1;
- (void)xmppConnection:(XMPPConnection *)arg1 callStanzaDidTimeOut:(XMPPStanza *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 callabilityChangedForJID:(NSString *)arg2 callability:(int)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 accountChangedWithAccountInfo:(NSDictionary *)arg2 receitInfo:(NSDictionary *)arg3 offlineStorage:(_Bool)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 contactUpdated:(NSString *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 contactsSyncRequest:(NSNumber *)arg2 timestamp:(NSDate *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 contactRemoved:(NSString *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 contactAdded:(NSString *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 statusChanged:(XMPPStatus *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 profilePictureUploadRequestFor:(NSString *)arg2 timestamp:(NSDate *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 profilePictureChangedFor:(NSString *)arg2 identifier:(NSString *)arg3 author:(NSString *)arg4 name:(NSString *)arg5 timestamp:(NSDate *)arg6;
- (void)xmppConnectionStopGroupLocationSharing:(XMPPConnection *)arg1;
- (_Bool)xmppConnection:(XMPPConnection *)arg1 startLocationSharingForGroup:(NSString *)arg2 duration:(int)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 dirtyFlagsReceived:(NSString *)arg2 timestamp:(NSDate *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 groupLockStateChanged:(_Bool)arg2 notification:(XMPPGroupNotification *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 groupDeletedNotification:(XMPPGroupNotification *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 groupCreated:(XMPPGroup *)arg2 notification:(XMPPGroupNotification *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 userModified:(NSString *)arg2 toJID:(NSString *)arg3 inGroupWithJID:(NSString *)arg4 timestamp:(NSDate *)arg5;
- (void)xmppConnection:(XMPPConnection *)arg1 participantsDemoted:(NSArray *)arg2 notification:(XMPPGroupNotification *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 participantsPromoted:(NSArray *)arg2 notification:(XMPPGroupNotification *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 participantsRemoved:(NSArray *)arg2 groupSubject:(NSString *)arg3 notification:(XMPPGroupNotification *)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 participantsAdded:(NSArray *)arg2 notification:(XMPPGroupNotification *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 groupSubjectChanged:(NSString *)arg2 notification:(XMPPGroupNotification *)arg3;
- (NSDictionary *)pushSettingsForXMPPConnection:(XMPPConnection *)arg1;
- (_Bool)xmppConnection:(XMPPConnection *)arg1 didReceiveMessages:(NSArray *)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 chatStateChanged:(unsigned long long)arg2 forJID:(NSString *)arg3 participantJID:(NSString *)arg4;
- (void)xmppConnection:(XMPPConnection *)arg1 presenceChanged:(unsigned long long)arg2 forJID:(NSString *)arg3;
- (void)xmppConnection:(XMPPConnection *)arg1 presenceChanged:(unsigned long long)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 statusChanged:(unsigned long long)arg2 forIncomingMessageWithStanzaID:(NSString *)arg3 fromJID:(NSString *)arg4 participantJID:(NSString *)arg5;
- (void)xmppConnection:(XMPPConnection *)arg1 statusChanged:(unsigned long long)arg2 forOutgoingMessagesWithStanzaIDs:(NSArray *)arg3 fromJID:(NSString *)arg4 participantJID:(NSString *)arg5 userData:(NSDictionary *)arg6;
- (void)xmppConnectionDidDisconnect:(XMPPConnection *)arg1;
- (void)xmppConnectionDidNotAuthenticate:(XMPPConnection *)arg1 lockDuration:(double)arg2 retryAfter:(double)arg3 reasonCode:(long long)arg4;
- (void)xmppConnectionDidAuthenticate:(XMPPConnection *)arg1;
- (void)xmppConnectionDidConnect:(XMPPConnection *)arg1;
- (void)xmppConnection:(XMPPConnection *)arg1 networkStatusChanged:(unsigned long long)arg2;
- (void)xmppConnection:(XMPPConnection *)arg1 stateChanged:(unsigned long long)arg2;
- (void)xmppConnectionDidBecomeIdle:(XMPPConnection *)arg1;
@end

