//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, XMPPAckStanza, XMPPChatStateStanza, XMPPIQStanza, XMPPNotificationStanza, XMPPPresenceStanza, XMPPReceiptStanza, XMPPStanza, XMPPStream;

@protocol XMPPStreamDelegate <NSObject>
- (void)xmppStreamDidBecomeIdle:(XMPPStream *)arg1;
- (_Bool)xmppStream:(XMPPStream *)arg1 didReceiveLoginResponseStanza:(XMPPStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 initialConfigurationAsync:(void (^)(NSArray *, NSDictionary *))arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveCustomStanza:(XMPPStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveNotification:(XMPPNotificationStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveChatState:(XMPPChatStateStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveAck:(XMPPAckStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveReceipt:(XMPPReceiptStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceivePresence:(XMPPPresenceStanza *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveMessages:(NSArray *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveIQ:(XMPPIQStanza *)arg2;
- (void)xmppStreamDidClose:(XMPPStream *)arg1;
- (void)xmppStreamDidOpen:(XMPPStream *)arg1;
- (void)xmppStreamDidNotAuthenticate:(XMPPStream *)arg1 lockDuration:(double)arg2 retryAfter:(double)arg3 reasonCode:(long long)arg4;
- (void)xmppStreamDidAuthenticate:(XMPPStream *)arg1 attributes:(NSDictionary *)arg2;
@end

