//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_XMPPRequestWebClientLogin.h"

@interface XMPPRequestWebClientAcceptPersistentLogin : _XMPPRequestWebClientLogin
{
    _Bool _isResume;
}

- (id)syncElementWithWebReference:(id)arg1;
- (id)initWithWebReference:(id)arg1 clientToken:(id)arg2 isResume:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;

@end

