//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPGroupRequest.h"

@interface XMPPRequestCreateGroup : XMPPGroupRequest
{
}

- (void)didFailWithError:(id)arg1;
- (void)didSuceedWithResponse:(id)arg1;
- (id)initWithSubject:(id)arg1 participantJIDs:(id)arg2 key:(id)arg3 locked:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType completion; // @dynamic completion;

@end

