//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendMessages : _XMPPWebClientRequest
{
}

- (id)initWithMessages:(id)arg1 requestID:(id)arg2 forWebSession:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

