//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPStanza.h"

@class NSString;

@interface XMPPNotificationStanza : XMPPStanza
{
}

+ (unsigned long long)typeForString:(id)arg1;
+ (id)stringForType:(unsigned long long)arg1;
+ (id)stringsForTypes;
- (id)log;
@property(readonly, nonatomic) NSString *nickname;
@property(readonly, nonatomic) NSString *text;
@property(nonatomic) unsigned long long type;
- (id)initWithType:(unsigned long long)arg1;

@end

