//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPRequest.h"

@interface XMPPRequestPrivacySettingSet : XMPPRequest
{
}

- (void)didFailWithError:(id)arg1;
- (void)didSuceedWithResponse:(id)arg1;
- (id)initWithSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType completion; // @dynamic completion;

@end

